// English catalog copy, keyed exactly like catalogs.zhHant.js (original
// record indices). PRODUCT_AUTHORED, 2026-09-29: translated from the approved
// zh-Hant text, not from the cartridge, and not yet reviewed by a native
// English editor. Species names and quoted team or person names inside a
// description have no approved English form and keep their approved zh-Hant
// names (docs/reports/settings-2026-09-29/GLOSSARY_ZH_TW.md).

export const CATALOG_TRANSLATION_EVIDENCE_EN = "PRODUCT_AUTHORED";

export const SHOP_NAMES_EN = Object.freeze([
  // Training Goods, records 0..3.
  "Feed", "Protein", "Salve", "Medicine",

  // Hunt Items, records 4..52.
  "Digi Rope α", "Digi Rope β", "Digi Rope γ",
  "Power Rope α", "Power Rope β", "Power Rope γ",
  "Clone Rope α", "Clone Rope β", "Clone Rope γ",
  "Ultimate Rope α", "Ultimate Rope β", "Ultimate Rope γ",
  "Pistol α", "Pistol β", "Repeater α", "Repeater β",
  "Sleep Rifle α", "Sleep Rifle β", "Stun Rifle α", "Stun Rifle β",
  "Shotgun α", "Shotgun β", "Stun Shotgun α", "Stun Shotgun β",
  "Standard Wire α", "Standard Wire β", "Magnet Wire α", "Magnet Wire β", "Shock Wire α", "Shock Wire β",
  "Meat Bait", "Large Meat Bait", "Poison Meat Bait", "Stun Meat Bait",
  "Decoy", "Evolved Decoy", "Yellow Lure Light", "Blue Lure Light",
  "Bomb", "Sleep Bomb", "Stun Bomb", "Flash Bomb",
  "Mine", "Giant Mine", "Digi Catcher", "Digi Prison",
  "Memory Card 32G", "Memory Card 64G", "Memory Card 96G",

  // Plugins, records 53..82.
  "Generation Analyzer", "Family Analyzer", "Attribute Analyzer", "HP Analyzer", "Personality Analyzer", "Capacity Analyzer",
  "Multi Analyzer α", "Multi Analyzer β", "Multi Analyzer Ω",
  "Shot Checker", "Wire Checker", "Lure Checker", "Damage Trap Checker", "All-Item Checker",
  "Generation Radar α", "Generation Radar β", "Generation Radar γ", "Generation Radar Ω",
  "Data Search", "Vaccine Search", "Virus Search",
  "Dragon Radar", "Beast Radar", "Bird Radar", "Aquatic Radar", "Holy Radar", "Dark Radar", "Insect & Plant Radar", "Machine Radar",
  "Memory Card Checker",

  // Cages, records 83..117.
  "Vacant Lot", "Mini Sports Ground", "Sports Ground", "Arena", "Dojo", "Mini Gym", "Gym", "Temple",
  "Grassland", "Mini Volcano", "Volcano", "Mini Beach", "Beach", "Mini Mountain", "Mountain", "Forest", "Jungle", "Factory",
  "Mini Garden", "Flower Garden", "Graveyard", "Desert", "Ice Field", "Power Plant", "Sanctuary", "Cave", "Laboratory", "Hospital", "Gas Room",
  "Mini Infirmary", "Infirmary", "Hot Spring", "Zoo", "Ranch", "Ring"
]);

export const SHOP_DESCRIPTIONS_EN = Object.freeze([
  // Training Goods, records 0..3.
  "Nutritious meat. Feed it to your Digimon when they're hungry!",
  "Eat it to enter battle with raised attack. Too much makes injuries more likely.",
  "A salve for treating injuries. The higher the generation, the harder some injuries are to heal.",
  "Medicine for treating illness. The lower the generation, the harder some illnesses are to cure.",

  // Hunt Items, records 4..52.
  "A rope for Baby Digimon. Durability 10.",
  "A rope for Baby Digimon. Durability 15.",
  "A rope for Baby Digimon. Durability 20.",
  "A rope for Child Digimon. Durability 32.",
  "A rope for Child Digimon. Durability 44.",
  "A rope for Child Digimon. Durability 56.",
  "A rope for Adult Digimon. Durability 60.",
  "A rope for Adult Digimon. Durability 80.",
  "A rope for Adult Digimon. Durability 100.",
  "A rope for Perfect Digimon. Durability 150.",
  "A rope for Perfect Digimon. Durability 200.",
  "A rope for Perfect Digimon. Durability 250.",
  "A gun for stopping a Digimon in its tracks. Power 10.",
  "A gun for stopping a Digimon in its tracks. Power 20.",
  "Fires rounds in quick succession. Power 10.",
  "Fires rounds in quick succession. Power 20.",
  "Fires tranquilizer rounds. Power 10. Effect: sleep.",
  "Fires tranquilizer rounds. Power 20. Effect: sleep.",
  "Special rounds that paralyze a Digimon. Power 10. Effect: paralysis.",
  "Special rounds that paralyze a Digimon. Power 20. Effect: paralysis.",
  "Fires 6 rounds at once. Power 10×6.",
  "Fires 6 rounds at once. Power 20×6.",
  "Fires 6 paralyzing rounds at once. Power 10×6. Effect: paralysis.",
  "Fires 6 paralyzing rounds at once. Power 20×6. Effect: paralysis.",
  "Laid on the ground to block Digimon from passing. Length 24.",
  "Laid on the ground to block Digimon from passing. Length 48.",
  "A wire that draws Digimon onto it. Length 24.",
  "A wire that draws Digimon onto it. Length 48.",
  "Damages Digimon with an electric shock. Length 24, power 10.",
  "Damages Digimon with an electric shock. Length 48, power 20.",
  "Digimon's favorite meat! Its smell draws Digimon in.",
  "An extra-large cut of meat. Its smell carries twice as far as ordinary meat.",
  "Meat laced with poison. Effect: poison.",
  "Meat that paralyzes whoever eats it. Effect: paralysis.",
  "A walking pumpkin toy that Digimon can't help chasing.",
  "An evolved walking toy that Digimon want to chase even more.",
  "A light that draws out certain Digimon. Night use only.",
  "Draws out Digimon with a mysterious blue light. Night use only.",
  "Deals damage with an explosion. Power 40.",
  "Explodes and releases sleeping gas. Power 40. Effect: sleep.",
  "Explodes and releases paralyzing gas. Power 40. Effect: paralysis.",
  "Gives off a blinding flash. Power 40. Effect: blindness.",
  "Explodes when a Digimon steps on it. Power 50.",
  "Sets off a big explosion when stepped on. Power 70.",
  "Placed on the ground to capture Digimon.",
  "A placed capture trap that works on many kinds of Digimon.",
  "Holds up to 32G of Digimon on a hunt.",
  "Holds up to 64G of Digimon on a hunt.",
  "Holds up to 96G of Digimon on a hunt.",

  // Plugins, records 53..82.
  "Shows a Digimon's species and generation.",
  "Shows a Digimon's species and family.",
  "Shows a Digimon's species and attribute.",
  "Shows a Digimon's species and maximum HP.",
  "Shows a Digimon's species and personality.",
  "Shows a Digimon's species and the capacity it needs.",
  "Shows a Digimon's species, generation and family.",
  "Shows a Digimon's species, generation, family and attribute.",
  "Shows everything about a Digimon: generation, family, attribute, HP, personality, the capacity it needs, and more.",
  "Shows how many shooting items you hold.",
  "Shows how many wire items you hold.",
  "Shows how many lure items you hold.",
  "Shows how many damage traps you hold.",
  "Shows how many of every item you hold.",
  "Shows Baby Digimon on the radar.",
  "Shows Child Digimon on the radar.",
  "Shows Adult Digimon on the radar.",
  "Shows Perfect Digimon on the radar.",
  "Shows Data and Free attribute Digimon on the radar.",
  "Shows Vaccine attribute Digimon on the radar.",
  "Shows Virus attribute Digimon on the radar.",
  "Shows Digimon of the Dragon family on the radar.",
  "Shows Digimon of the Beast family on the radar.",
  "Shows Digimon of the Bird family on the radar.",
  "Shows Digimon of the Aquatic family on the radar.",
  "Shows Digimon of the Holy family on the radar.",
  "Shows Digimon of the Dark family on the radar.",
  "Shows Digimon of the Insect & Plant family on the radar.",
  "Shows Digimon of the Machine family on the radar.",
  "Shows the memory card's capacity.",

  // Cages, records 83..117.
  "A small, relaxing open space. Raises defense. Suggested for 2 Digimon.",
  "A mini version of the Sports Ground. Raises HP. Suggested for 2 Digimon.",
  "Builds stamina through steady running. Raises HP. Suggested for 6 Digimon.",
  "A wide space to run to their heart's content. Raises speed. Suggested for 10 Digimon.",
  "A place to hone moves and train. Raises TP. Suggested for 6 Digimon.",
  "A mini version of the Gym. Raises attack. Suggested for 2 Digimon.",
  "Full of equipment for building up the body. Raises attack. Suggested for 8 Digimon.",
  "A quiet place to focus the mind. Raises wisdom. Suggested for 2 Digimon.",
  "A grassland with short grass. Raises the Beast family. Suggested for 6 Digimon.",
  "A mini version of the Volcano. Raises the Dragon family. Suggested for 2 Digimon.",
  "A burning volcano. Raises the Dragon family. Suggested for 8 Digimon.",
  "A mini version of the Beach. Raises the Aquatic family. Suggested for 2 Digimon.",
  "A seaside where waves break on the shore. Raises the Aquatic family. Suggested for 8 Digimon.",
  "A mini version of the Mountain. Raises the Bird family. Suggested for 2 Digimon.",
  "A windswept mountain. Raises the Bird family. Suggested for 8 Digimon.",
  "A forest full of mystery. Raises the Insect & Plant family. Suggested for 6 Digimon.",
  "A thickly overgrown jungle. Raises the Insect & Plant family. Suggested for 6 Digimon.",
  "A factory that builds machines. Raises the Machine family. Suggested for 6 Digimon.",
  "A mini version of the Flower Garden. Raises the Holy family. Suggested for 2 Digimon.",
  "Beautiful flowers in bloom that purify the heart. Raises the Holy family. Suggested for 4 Digimon.",
  "A graveyard where the dead rest. Raises the Dark family. Suggested for 6 Digimon.",
  "A desert that is hot all year round. Raises heat resistance. Suggested for 6 Digimon.",
  "Surrounded by biting cold and snow. Raises cold resistance. Suggested for 8 Digimon.",
  "A power plant with current flowing through it. Raises thunder resistance. Suggested for 6 Digimon.",
  "A sanctuary devoted to the god of light. Raises light resistance. Suggested for 6 Digimon.",
  "A dark, narrow cave. Raises dark resistance. Suggested for 2 Digimon.",
  "A research facility that processes data. Raises the Data attribute. Suggested for 8 Digimon.",
  "A hospital that researches vaccines. Raises the Vaccine attribute. Suggested for 6 Digimon.",
  "A gas room full of germs. Raises the Virus attribute. Suggested for 4 Digimon.",
  "A mini version of the Infirmary. Recovers HP and stress. Suggested for 2 Digimon.",
  "An infirmary that heals Digimon. Recovers HP and stress. Suggested for 6 Digimon.",
  "A hot spring that heals Digimon. Recovers HP and stress. Suggested for 8 Digimon.",
  "Takes care of feeding and droppings automatically, though it's a little cramped. Suggested for 2 Digimon.",
  "Takes care of feeding and droppings automatically, with plenty of comfortable room. Suggested for 8 Digimon.",
  "Sparring again and again in a practice ring. Raises battle count. Suggested for 6 Digimon."
]);

// Help, keyed by entryIndex. A heading has no body.
const HELP_ROWS = [
  ["Hunting"],
  ["Hunting gear"],
  ["Digital World"],
  ["Gates"],
  ["How to capture"],
  ["Rope", "The most basic piece of hunting gear, used to bind a Digimon and deal damage. It can be used again and again, even after it breaks. The higher its durability, the less easily it breaks."],
  ["Shooter", "Gear that fires pellets to make a Digimon flinch. It is mainly used to stop a Digimon moving and to help with a capture. Ammo is limited, so keep an eye on how many rounds are left."],
  ["Wire", "Gear laid on the field to block or guide Digimon. It breaks after it has been in place for a while. It can't be placed on top of a Digimon or an object on the field."],
  ["Lure", "Trap-type gear that attracts Digimon. Some baits cause paralysis or poison; lights draw Digimon in, and moving decoys can lead them into traps."],
  ["Damage trap", "Trap-type gear that damages Digimon directly. Some go off on their own once set; others go off when a Digimon touches them."],
  ["Plug-ins", "Essential gear for hunting Digimon. Plug-ins show a Digimon's stats or put Digimon on the radar. Combine them to handle different situations."],
  ["Memory card", "Every Digimon takes up its own capacity. Mind your memory card's capacity when bringing Digimon back from the Digital World or taking them there."],
  ["Time", "A day in the Digital World lasts about ten minutes of real time. There are no weeks or months: eight days make a season, and four seasons make a year."],
  ["Hunting time", "Once you set out on a hunt, you are called back automatically when time runs out. Plan the time you have left before you go."],
  ["Seasons", "The Digital World has seasons too. Different Digimon are easier to catch in different seasons, and some Digimon move to new habitats. The number of tournaments also varies by season, so many tamers also go hunting in the seasons with the most tournaments."],
  ["Weather", "The Digital World has weather as well, and it changes in many ways with place and season."],
  ["Gates", "Gates take you to particular regions of the Digital World. How many gates you can use, and which ones, depends mainly on your tamer rank."],
  ["Entry fee", "Going to the Digital World means using a gate and paying its entry fee. Each gate costs a different amount, taken automatically from the Bits you hold. You can't use a gate you can't afford, so check your funds before setting out."],
  ["Habitats", "Digimon are living things and live in surroundings that suit them. The regions reached through different gates are home to different Digimon."],
  ["Release", "When you release a Digimon you brought on your memory card, it lives in that area for a while. Releasing can change what lives there, so take care."],
  ["Capture basics", "Use your gear to bring a Digimon's HP down to zero, then grab it with the hand icon to capture it onto your memory card."],
  ["Resistance", "Some Digimon take no damage from certain gear, and some can only have their HP lowered by particular gear. Some gear may deal no damage at all, so take care."],
  ["Raising"],
  ["Digimon evolution"],
  ["Digimon classification"],
  ["Status"],
  ["Cages"],
  ["How to raise"],
  ["Tamer info"],
  ["Baby I and II", "A newborn Digimon and its next stage are called the Baby stages. Baby I can't battle yet; from Baby II on, a Digimon can take part in battles."],
  ["Child", "Digimon that have grown out of the Baby stages. Their attack rises, and they begin to branch into many kinds to cope with different surroundings."],
  ["Adult", "Digimon that have left the Child stage and can hold their own. Attack and intelligence rise further, and many kinds have features suited to particular surroundings."],
  ["Perfect", "The stage after Adult, where a Digimon becomes complete. In the wild, it is said to be very hard to grow into a Perfect."],
  ["Ultimate", "The stage of ultimate power, reached only after a Perfect meets even harsher conditions. As a rule, a Digimon can't grow this far without a tamer's help."],
  ["Digi-Egg", "A Digimon's egg. Digimon have no sexes and do not breed; each generation is renewed by returning to a Digi-Egg."],
  ["Attribute", "Most Digimon have one of three attributes: Vaccine, Virus or Data. There are also Free Digimon with no attribute. Baby Digimon have no attribute."],
  ["Family", "Classified by the direction of their evolution, Digimon fall broadly into eight families. Adjusting a Digimon's family lets you steer its evolution to some extent."],
  ["Type", "A classification researchers have long used, usually written as \"such-and-such type Digimon\". It tends to be very detailed and isn't fully consistent; you can look it up in the Database."],
  ["Personality", "Digimon have personalities too, which affect whether they follow their tamer's instructions and how they act in their cage. Personality does not change with evolution or with returning to a Digi-Egg."],
  ["Lifespan", "Every Digimon has its own span of activity; when it runs out, the Digimon disappears or returns to a Digi-Egg. Evolving before the span ends extends its active time."],
  ["HP", "A Digimon's stamina. When it drops to zero, the Digimon is near death and can't move."],
  ["TP", "The points needed to use special moves and support skills."],
  ["Resistance", "Digimon have resistance to five kinds of attack: heat, cold, thunder, light and dark. Moving to a different cage changes their resistances."],
  ["Stress", "Digimon are sensitive creatures. Built-up stress leads to illness, and even to disappearing. Cage space, cleanliness, personality, size and how Digimon get along all affect stress."],
  ["Capacity", "Each Digimon needs a different amount of capacity, and the total you can raise at once is limited. Capacity grows when a Digimon evolves; without enough free capacity, it can't evolve."],
  ["Battle count", "How many battles a Digimon has taken part in. Battle count also affects evolution."],
  ["Returning to a Digi-Egg", "A Digimon that disappears through battle or old age sometimes becomes a Digi-Egg. Each return raises its base stats, so it gradually grows stronger."],
  ["Digimon cages", "Fenced facilities for raising Digimon. They can restore HP or change stats, and each cage changes different stats more easily."],
  ["Cage layout", "Tamers can freely rearrange and combine their cages. Raising your tamer rank also widens the area where cages can go."],
  ["Suggested capacity", "The number of Digimon each cage suits best. You may go over it, but Digimon then build up stress more easily."],
  ["Cage effects", "Each cage has a particular effect: training there can change stats or restore HP."],
  ["Training", "Training falls into two kinds: raising battle abilities such as HP and resistances, and changing the family and attribute that shape evolution."],
  ["Raising seasons", "Seasons affect raising as well as hunting. Training works better in summer, and injuries happen more easily in winter."],
  ["Food", "Digimon get hungry too. Going hungry for too long leaves a Digimon near death, and if nothing is done it will eventually die."],
  ["Protein", "Feeding protein raises attack for a while, but also raises the chance of injury. Leftover protein spoils too, so take care."],
  ["Cleaning", "Digimon relieve themselves every so often. Staying in a cage with droppings or spoiled food can make them sick."],
  ["Injury", "Digimon can get injured in battle or training. Left untreated, an injury leaves a Digimon near death, so treat it with salve."],
  ["Illness", "Staying a long time in a cage with droppings or spoiled food causes illness. Left untreated, it leaves a Digimon near death, and Digimon living with a sick one may catch it. Treat illness with medicine."],
  ["Near death and disappearing", "A Digimon left near death will disappear. Once it disappears it breaks down into data of zeros and ones and can never come back. Under certain conditions, though, it becomes a Digi-Egg and is born again."],
  ["Other actions", "With the hand icon selected, you can pick up a Digimon and move it to another cage, or pet it and poke it. Sometimes the record shows what a Digimon is getting ready to evolve into."],
  ["Tamer", "The name for people who raise Digimon. Tamers are divided into ranks by conditions such as their Digimon's battle record."],
  ["Tamer rank", "A higher rank gives more evolution choices, more room for cages, and lets you raise more Digimon at once. It also opens more title matches."],
  ["Raising license", "Your tamer rank limits the generation your Digimon can evolve into. To raise strong Digimon, raising your rank and earning licenses is important."],
  ["Cage space", "The size of the area where cages can go, counted in hexes. Raising your tamer rank widens it."],
  ["Maximum capacity", "Every Digimon takes capacity, and the total you can raise at once has a limit. Raising your tamer rank increases the capacity you can raise at once."],
  ["Battle"],
  ["Battle types"],
  ["Battle preparation"],
  ["Support skills"],
  ["Practice Battle", "Your own Digimon battle each other. It counts toward their battle count and win rate, but pays no appearance prize."],
  ["Free Battle", "Enter any time you meet the entry conditions. The teams change every day, so look carefully before you decide. It pays an appearance prize and is good for testing strength and getting in shape."],
  ["Title Match", "Each title sets conditions on Digimon and arena. Matches are held on fixed dates; miss one and you must wait a year, so take care."],
  ["Championship", "The Championship qualifier is held once a year. You must win a qualifier at least once to enter the final. The Championship is a knockout tournament: you keep battling until you win it all."],
  ["Link Battle", "Uses the wireless features of Nintendo's dual-screen handheld to let Digimon battle each other, either between nearby consoles or over a wireless network."],
  ["Password Battle", "Digimon saved as passwords battle each other. Since their strength never changes, they make good practice opponents."],
  ["Battle strategy", "Sets what your Digimon in battle should prefer to do. \"Special moves first\" uses special moves often, \"Support first\" uses support skills often, and \"Normal attack\" balances the two."],
  ["Special moves", "Powerful attacks unique to each Digimon; some add extra effects besides damage. Special moves have attributes, so damage changes with the target's resistances. Using one costs TP, and it can't be used without enough TP."],
  ["Arenas", "The places where Digimon battle. Each Digimon adapts differently to each kind of arena."],
  ["Password saving", "Digimon are living things and can't stay the same forever, but a password can save their state at a moment in time. This lets you keep your strongest Digimon from the past, or share them with others."],
  ["What are support skills?", "Special abilities Digimon use to support a battle; which ones a Digimon has depends on its species and personality. Using one costs TP."],
  ["Stat boosts", "Support skills that raise stats such as attack, defense and speed."],
  ["Special skills", "\"Revive\" guarantees that a Digimon gets back up once after its HP drops to zero. \"Taunt\" provokes the opposing team so their attacks focus on the user."],
  ["Recovery", "Support skills that restore HP."],
  ["Resistance boosts", "Support skills that raise resistance, one for each of the five types: heat, cold, thunder, light and dark."]
];
export const HELP_EN = Object.freeze(HELP_ROWS.map(([title, body], entryIndex) => Object.freeze({ entryIndex, title, body: body ?? null })));

// Title events, keyed by recordIndex: the event name and its description.
const EVENT_ROWS = [
  ["Access Striker", "A head-to-head, one-on-one duel with the Child-stage 玩具亞古獸!\n1-on-1 battle."],
  ["Legion Captain", "Take on the pair they call invincible! The title holders field only two Adult Digimon, one fewer than you, but don't let your guard down.\nAdult only, 3-on-2 battle."],
  ["Sunshine Revolution", "One of the \"Seven Top Titles\", the highest rank of title there is! Write your name into its history!\n3-on-3 battle."],
  ["Vector Sector", "Holding back the moves of the team captain, 妖狐獸, is the key to winning!\n3-on-3 battle."],
  ["Bit Agent", "Watch out for 獨角獸's power and they're not a hard team to beat!\n3-on-3 battle."],
  ["Tough Digitizer", "A duo proud of their strength! Raise your HP before you take them on!\nChild only, 3-on-3 battle."],
  ["Core Crusher", "The Ultimate 法老獸 enters the ring! A one-on-one showdown that every tamer is watching!\n1-on-1 battle."],
  ["Silver Freeze", "The title holders are three tricky Adult Digimon! You must take on their team of three alone!\n1-on-3 battle."],
  ["Spring Ace", "The rule is a one-on-one duel! Send out your team's ace!\n1-on-1 battle."],
  ["Summer Phantom", "A special three-on-one match! Can three Digimon work together to beat 巨鯨獸 and rule the height of summer?\nAdult only, 3-on-1 battle."],
  ["Autumn Survivor", "The title holder is one calm Perfect, 祖利獸! Fighting alone, balance attack with recovery!\n1-on-1 battle."],
  ["Winter General", "Take on the title-holding team of three Digimon alone! A title match that every tamer is watching!\n1-on-3 battle."],
  ["Million Solo Attack", "One of the \"Seven Top Titles\", the highest rank of title there is! Take on three opponents alone!\n1-on-3 battle."],
  ["Dragon Lord", "A battle to master the strongest dragons! A title match that every tamer is watching!\nDragon family only, 3-on-3 battle."],
  ["Beast Champion", "Master wild power and make your way to king of the beasts!\nBeast family only, 3-on-3 battle."],
  ["Aqua Centurion", "The stage is a water arena! Take on the team built around 雪亞古獸將軍!\nWater arena, 3-on-3 battle."],
  ["Wing Master", "In a battle in the sky, the one who uses the wind wins the upper hand.\nBird family only, 1-on-1 battle."],
  ["King of Nature", "Many teams have fallen to the attacks of their captain, 「薔薇」!\nAdult only, 3-on-3 battle."],
  ["Sanctuary Warrior", "In a battle between Holy Digimon, fighting fair and square is everything.\nHoly family only, 3-on-3 battle."],
  ["Nightmare Leader", "A machine team born of experiment after experiment, and still unbeaten!\nAdult only, 3-on-3 battle."],
  ["Steel Emperor", "Sparks fly as Machine Digimon fight for ever greater power.\nMachine family only, 3-on-3 battle."],
  ["Sky Walker", "Digimon battle fiercely for rule of the skies.\nDragon or Bird family only, 3-on-3 battle."],
  ["Dark Warrior", "A tournament only the Dark and Machine families can enter. Hand-picked warriors of darkness clash!\nMachine or Dark family only, 3-on-3 battle."],
  ["Wild Hunter", "The opponent is a strong beast team gathered from power fighters!\nChild only, 3-on-3 battle."],
  ["Clear Fighter", "A fine team balanced in both color and strength!\n3-on-3 battle."],
  ["Small Challenger", "The title holder 基扎獸 has powerful claws, but find its weak point and you might win easily!\n1-on-1 battle."],
  ["Big Fighter", "A special three-on-one match! Break the unbelievable power of 祖頓獸 with teamwork!\nAdult only, 3-on-1 battle."],
  ["Giant Extreme", "A special three-on-one match! Can you withstand 小丑皇's attacks and beat it with teamwork?\nPerfect only, 3-on-1 battle."],
  ["Perfect Fighter", "A title match that every tamer is watching! Face it with your strongest line-up!\nUltimate only, 3-on-3 battle."],
  ["Virus Slayer", "The Virus-type Digimon they call invaders are about to unleash their power!\nVirus attribute only, 3-on-3 battle."],
  ["Gene Guardian", "Your opponents are three Baby II Digimon, and you must face them alone! You're outnumbered, but none of them is that strong!\n1-on-3 battle."],
  ["Data Killer", "To master battle, you must understand data!\nData attribute only, 3-on-3 battle."],
  ["Noise Divider", "Can you beat the elite squad of 「Ｄ無限」?\nVirus attribute and Ultimate only, 3-on-3 battle."],
  ["Security Line Decider", "The title match that decides the strongest Vaccine attribute Digimon!\nVaccine attribute and Ultimate only, 3-on-3 battle."],
  ["Giant Gatekeeper", "A one-on-one duel to decide the strongest Data attribute Digimon!\nData attribute and Ultimate only, 1-on-1 battle."],
  ["Aqua Crusher", "The arena is water. Aquatic Digimon have the advantage.\nWater arena, 3-on-3 battle."],
  ["Blizzard Field", "The stage is a snowy mountain! Beware 冰惡魔獸's icy claws and 雪人獸's punches!\nSnow arena, 3-on-3 battle."],
  ["Volcano Striker", "A title match held on a volcano. Waves of heat from raging magma sweep over the Digimon!\nVolcano arena, 3-on-3 battle."],
  ["Desert Storm", "Set in a desert arena, for the teams that can beat the scorching heat!\nDesert arena, 3-on-3 battle."],
  ["Top of the Arena", "A title match held in the arena that every tamer is watching!\nArena, 1-on-1 battle."],
  ["Top of the World", "The title holders are masters of magic! Don't be fooled: overwhelm them with power!\n3-on-3 battle."],
  ["Duel Queen", "The title holders are a team of women. The winning Digimon will be honored as a goddess of battle!\n3-on-3 battle."],
  ["Dancing Puppet", "A special one-on-three match! Deftly beat the three 齒輪獸 that come at you!\nAdult only, 1-on-3 battle."],
  ["Emerald Seed", "A title match that brings together only Plant-type Digimon!\nPlant type only, 3-on-3 battle."],
  ["Bean World", "A rare battle that only 豆豆獸 can enter. They say whoever masters 豆豆獸 masters every Digimon.\n豆豆獸 type only, 3-on-3 battle."],
  ["Steel Doom", "The title holders vary in strength, but every one of them is armored in metal from head to toe!\n3-on-3 battle."],
  ["Insect King", "To beat the hard-armored Insect-type Digimon, you need enough power!\n3-on-3 battle."],
  ["Ancient Destroyer", "Rare Ancient-type Digimon, long asleep, gather in one place.\n3-on-3 battle."],
  ["Origin Survivor", "Only the first Digimon ever discovered can enter!\nOnly Digimon that appeared in 《數碼怪獸》, 1-on-1 battle."],
  ["Pendulum Twist", "A battle only Digimon from the Pendulum era can enter!\nOnly Digimon that appeared in 《數碼怪獸擺錘機》, 3-on-3 battle."],
  ["Hundred Souls", "Only Digimon that have been with you a long time can enter!\nOnly Digimon that have returned to a Digi-Egg at least three times, 3-on-3 battle."],
  ["Thousand Souls", "One of the \"Seven Top Titles\", the highest rank of title there is!\nOnly Digimon that have returned to a Digi-Egg at least five times, 3-on-3 battle."],
  ["Infinite Soul", "One of the \"Seven Top Titles\", the highest rank of title there is!\nOnly Digimon that have returned to a Digi-Egg at least ten times, 3-on-3 battle."],
  ["Gravity Knight", "One of the \"Seven Top Titles\", the highest rank of title there is!\nCapacity of at least twenty-four only, 3-on-3 battle."],
  ["Lonely Paradise", "Only Timid Digimon can enter, so good command skills are a must.\nTimid personality only, 3-on-3 battle."],
  ["Challenge Gear", "The rule is a one-on-one duel! If you can't even take this title, your future as a tamer looks worrying!\n1-on-1 battle."],
  ["Rainbow Flyer", "Colorful Digimon such as 妖狐九尾獸 and 迷幻獸 take the stage!\n3-on-3 battle."],
  ["Lunar Evolution", "One of the \"Seven Top Titles\", the highest rank of title there is! Your opponent is 「黛莉西亞薔薇」, who seeks ultimate beauty!\n3-on-3 battle."],
  ["Blade Guardian", "One of the \"Seven Top Titles\", the highest rank of title there is! Your opponent is 「艾克斯龍騎士」, who knows everything about dragons!\n3-on-3 battle."],
  ["Golden Wings", "Take on the dazzling title holders! A title match that every tamer is watching!\n3-on-3 battle."],
  ["Reflection War", "Among Ultimates, this may be one of the easier opponents. A title match that every tamer is watching!\n3-on-3 battle."],
  ["Tutorial Battle", "A battle for learning the ropes. It's fine if you lose!"]
];
export const TITLE_EVENTS_EN = Object.freeze(EVENT_ROWS.map(([name, description], recordIndex) => Object.freeze({ recordIndex, name, description })));
