// Preview-only controls use the existing locale owner. Existing five-language
// tutorial/brand dictionaries are read unchanged, including player names.
import {getLocale} from "./locale.js";
const COPY={
 "zh-Hant":{title:"教學預覽",invite:"要試玩互動教學嗎？此預覽包含育成照護、狩獵與示範對戰，完成或結束時會還原起始進度。",accept:"開始預覽",decline:"返回牧場",next:"繼續",waiting:"請等待夥伴完成目前動作。",boundary:"本段預覽到此為止；育成照護已結束；Gate16、狩獵與對戰接線待後續完成。可保留此進度稍後接續，或結束預覽還原起始牧場。",keep:"保留進度",exit:"結束預覽",retry:"重試保存",failed:"尚未保存成功。請重試；保存成功前不會進入下一步。"},
 en:{title:"Tutorial preview",invite:"Try the interactive tutorial? This preview covers ranch care, hunting and a demo battle. Finishing or exiting restores your starting progress.",accept:"Start preview",decline:"Return to ranch",next:"Continue",waiting:"Wait for your partner to finish the current action.",boundary:"This preview ends here. Ranch care is complete. Gate16, hunting and battle integration follow in a later slice. Keep this checkpoint to continue later, or exit to restore the starting ranch.",keep:"Keep progress",exit:"Exit preview",retry:"Retry save",failed:"Saving failed. Retry to continue; progress will not advance until it is saved."},
 ja:{title:"チュートリアルのプレビュー",invite:"体験しますか？育成のお世話、狩り、体験用の対戦を遊べます。完了または終了すると開始時の進行状況に戻ります。",accept:"プレビューを開始",decline:"牧場に戻る",next:"続ける",waiting:"パートナーの動作が終わるのを待ちましょう。",boundary:"今回のプレビューはここまでです。お世話は終了です。Gate16・狩り・対戦の接続は今後の段階です。進行状況を残して後で続けるか、終了して開始時の牧場に戻れます。",keep:"進行状況を残す",exit:"プレビューを終了",retry:"保存を再試行",failed:"保存できませんでした。保存が成功するまで次へ進みません。再試行してください。"},
 th:{title:"ตัวอย่างบทสอน",invite:"ลองบทสอนแบบโต้ตอบไหม? ตัวอย่างนี้มีการดูแลในฟาร์ม การล่า และการต่อสู้สาธิต เมื่อจบหรือออกจะคืนความคืบหน้าเริ่มต้น",accept:"เริ่มตัวอย่าง",decline:"กลับฟาร์ม",next:"ต่อไป",waiting:"รอให้คู่หูทำการกระทำนี้เสร็จ",boundary:"ตัวอย่างนี้จบที่นี่ การดูแลเสร็จแล้ว ส่วน Gate16 การล่า และการต่อสู้จะเชื่อมต่อในขั้นถัดไป เก็บความคืบหน้าไว้เล่นต่อภายหลัง หรือออกเพื่อคืนฟาร์มเริ่มต้น",keep:"เก็บความคืบหน้า",exit:"ออกจากตัวอย่าง",retry:"ลองบันทึกอีกครั้ง",failed:"บันทึกไม่สำเร็จ กรุณาลองอีกครั้ง จะยังไม่ไปขั้นถัดไปจนกว่าจะบันทึกสำเร็จ"},
 vi:{title:"Bản xem trước hướng dẫn",invite:"Thử hướng dẫn tương tác? Bản xem trước bao gồm chăm sóc ở trang trại, săn bắt và trận đấu mẫu. Khi hoàn thành hoặc thoát, tiến độ ban đầu sẽ được khôi phục.",accept:"Bắt đầu xem trước",decline:"Về trang trại",next:"Tiếp tục",waiting:"Đợi bạn đồng hành hoàn thành hành động hiện tại.",boundary:"Bản xem trước kết thúc tại đây. Đã xong phần chăm sóc. Gate16, săn bắt và chiến đấu sẽ được kết nối ở giai đoạn sau. Giữ tiến độ để tiếp tục sau hoặc thoát để khôi phục trang trại ban đầu.",keep:"Giữ tiến độ",exit:"Thoát xem trước",retry:"Thử lưu lại",failed:"Lưu thất bại. Hãy thử lại; hướng dẫn chỉ tiếp tục sau khi lưu thành công."}
};
const NORMAL={
 "zh-Hant":{title:"新手教學",invite:"要學習育成、狩獵和對戰的操作嗎？教學使用示範隊伍；完成或結束後，會回到初始進度，保留你設定的馴獸師和夥伴名字。",accept:"開始教學",decline:"略過教學",exit:"結束教學"},
 en:{title:"Getting started",invite:"Learn how to raise partners, hunt and battle? The tutorial uses a demo team. After finishing or leaving it, you will return to your starting progress, keeping the trainer and partner names you chose.",accept:"Start tutorial",decline:"Skip tutorial",exit:"End tutorial"},
 ja:{title:"はじめての遊び方",invite:"育成・狩り・対戦の操作を学びますか？体験用のチームで練習します。完了または終了した後は、決めたテイマーとパートナーの名前を保って最初の状態から始めます。",accept:"チュートリアルを開始",decline:"スキップ",exit:"チュートリアルを終了"},
 th:{title:"เริ่มเล่น",invite:"เรียนรู้วิธีเลี้ยงคู่หู ล่า และต่อสู้ไหม? บทสอนใช้ทีมสาธิต เมื่อเรียนจบหรือออก คุณจะกลับสู่ความคืบหน้าเริ่มต้น โดยคงชื่อผู้ฝึกและคู่หูที่คุณตั้งไว้",accept:"เริ่มบทสอน",decline:"ข้ามบทสอน",exit:"จบบทสอน"},
 vi:{title:"Bắt đầu chơi",invite:"Bạn muốn học cách chăm sóc, săn bắt và chiến đấu không? Hướng dẫn dùng đội hình mẫu. Khi hoàn thành hoặc thoát, bạn sẽ trở về tiến độ ban đầu, giữ nguyên tên huấn luyện viên và bạn đồng hành.",accept:"Bắt đầu hướng dẫn",decline:"Bỏ qua hướng dẫn",exit:"Kết thúc hướng dẫn"}
};
export function tutorialPreviewText(preview=true){const locale=getLocale(),copy=COPY[locale]??COPY["zh-Hant"];
 return preview?copy:{...copy,boundary:copy.failed,...(NORMAL[locale]??NORMAL["zh-Hant"])};}
