// English display copy. PRODUCT_AUTHORED, 2026-09-29 (settings round).
//
// Not yet reviewed by a native English editor; the report says so.
//
// Three tables, one per kind of source string:
//   UI_COPY_EN  the English design keys in uiText.js (their zh-Hant is there)
//   TEXT_EN     zh-Hant source strings, including `{name}` templates; an entry
//               may be { one, other } when English needs a plural
//   PATTERNS_EN English-key patterns with a variable part
// Proper nouns follow docs/reports/settings-2026-09-29/GLOSSARY: names the
// project has not approved in English (species, the starter's automatic
// names) are not translated here and keep their approved zh-Hant form.
// Player-typed names are never looked up at all.

import { uiText } from "./uiText.js";
import { SPECIES_NAMES_ZH } from "./catalogs.zhHant.js";
import { STARTER_NAMES_ZH } from "./zhHant.js";

export const UI_COPY_EN = Object.freeze({
  "MUSIC_VOLUME": "Music",
  "MUSIC_VOLUME_HINT": "Music for the title, ranch, exploration and battles.",
  "MUSIC_GESTURE_NOTE": "Music starts after a tap or key press and pauses in the background.",
  "RESIDENT_ART_LOADING": "Loading companion artwork…",
  "RESIDENT_ART_ERROR": "Companion artwork could not load. Your game data is retained.",
  "RESIDENT_ART_RETRY": "Retry artwork",
  "OPENING_COMIC_LOADING": "Loading the story…",
  "輕觸數碼獸查看": "Tap a partner to see it",
  "野生數碼獸": "Wild Creatures",

  "SWIPE TO VIEW": "Swipe to look around", "Waiting Room": "Waiting Room",
  "Moonwell Pool": "Moonwell Pool", "Quiet Hollow": "Quiet Hollow",
  "TAMER RANK": "Tamer rank", "ENTRY FEE": "Entry fee",
  "durability": "Durability", "length": "Length",
  "HP 分析": "HP analysis",
  "ON MEMORY CARD": "On the memory card", "MEMORY CARD": "Memory card",
  "RELEASE": "Release", "CANCEL": "Cancel", "CONFIRM RELEASE": "Confirm release", "NAME THIS ONE": "Name", "NAMING": "Naming",
  "Memory card and Home roster": "Memory card and ranch partners", "Confirm release": "Confirm release",
  "Release is not yet available for this resident.": "This partner cannot be released yet.",
  "Save failed. Your Digimon is still on the memory card. Return Home again to retry.": "Save failed. Your partner is still on the memory card. Head back to the ranch again to retry.",
  "Your home roster is full. Your Digimon remains on the memory card.": "Your ranch is full. The partner stays on the memory card.",
  "The full cage footprint must fit in free, unlocked cells.": "Every hex a cage covers must be open and free.",
  "Waiting Room stays at the ranch entrance.": "The Waiting Room stays at the ranch entrance.",
  "Exploration field. Drag empty ground to look around. Touch a creature to select it.": "Hunt field. Drag open ground to look around. Tap a creature to select it.",
  "Rotatable world destination view": "Rotatable world map", "World destination nodes": "World regions",
  "DIGIMON CHAMPIONSHIP · 2026": "Cable Partners: Championship Beyond the Noise · 2026",
  "RAISING HOME": "Raising Home", "Raising Home": "Raising Home", "Training": "Raising",
  "Spring": "Spring", "Summer": "Summer", "Autumn": "Autumn", "Winter": "Winter",
  "SPRING": "Spring", "SUMMER": "Summer", "AUTUMN": "Autumn", "WINTER": "Winter",
  "Day": "Day", "END DAY": "End day", "End the day": "End the day",
  "SAVE": "Save", "BACK": "Back", "RETURN HOME": "Back to ranch", "RETURN TO RANCH": "Back to ranch", "CONTINUE": "Continue",
  "NEXT": "Next", "LEAVE": "Leave", "CONFIRM": "Confirm", "LIST": "List",
  "SHOP": "Shop", "Shop": "Shop", "HUNT": "Hunt", "Hunt": "Hunt",
  "Battle": "Battle", "Battle result": "Battle result", "DATABASE": "Database", "Database": "Database",
  "HOME": "Raising", "CAGE": "Cage layout", "CAGES": "Cages", "GOODS": "Raising goods",
  "PLUGINS": "Plug-ins", "EGG": "Egg", "EGGS": "Eggs", "REGULAR": "Regular species",
  "SPECIES": "Species", "REGISTERED": "Registered", "STARTER": "Starter partner", "NEW": "New",
  "HELD": "Max held", "BUY": "Buy", "Undiscovered": "Undiscovered", "Unknown gate": "Unknown gate",
  "GIVEN NAME": "Nickname", "Given name": "Nickname", "NAME": "Name", "FAMILY": "Family",
  "GEN.": "Generation", "ATTR. INDEX": "Attribute no.", "none set": "Not set",
  "HP": "HP", "TP": "TP", "DIGIMON": "PARTNER", "Digimon": "Partner",
  "ROSTER": "Partners", "NAME EDIT": "Rename", "DELETE": "Remove", "ENTRY": "Enter",
  "TAMER": "Tamer", "Tamer": "Tamer", "TAMER INFO": "Tamer info",
  "SCHEDULE": "Schedule", "Schedule": "Schedule", "TITLE MATCHES": "Title matches", "RECORD": "No.",
  "HELP": "Help", "Help": "Help", "Cage Edit": "Cage layout", "End Day": "End day",
  "Save & Quit": "Save & quit", "MANAGE": "Manage", "SYSTEM": "Menu", "Settings": "Settings",
  "Retry": "Retry", "Saving...": "Saving…",
  "HAND": "Hand", "FEED": "Feed", "CLEAN": "Clean", "MED": "Meds", "WOUND": "Salve", "PROTEIN": "Protein",
  "Move a resident, or stroke it": "Move a partner, or pet it", "Place food beside a resident": "Put food next to a partner",
  "Clear droppings and leftovers": "Clear droppings and leftovers", "Cure sickness": "Cure sickness",
  "Heal injury": "Heal an injury", "Raise attack for a time": "Raise attack for a while",
  "Contextual toolbar": "Toolbar", "In the original, not yet in this build": "Not available yet",
  "Changes are waiting to be saved.": "Changes are waiting to be saved.", "Raising Home is up to date.": "Raising is up to date.",
  "Raising Home saved.": "Raising saved.", "Raising Home restored from save.": "Raising loaded from your save.",
  "The last safe Raising Home state was recovered.": "The last safe raising state was recovered.",
  "Save did not complete. You can try again.": "The save did not finish. Please try again.",
  "Raising Home status updated.": "Raising updated.", "Raising Home is ready.": "Raising Home is ready.",
  "Saved game restored.": "Saved game loaded.", "Raising Home is ready. Tap a creature to look after them.": "Raising Home is ready. Tap a partner to see how it is doing.",
  "Raising Home time": "Raising time", "Playable Raising field": "Raising field",
  "LIVE HABITAT": "Habitat", "FIELD ONLINE": "Field ready", "COMPANION LINK": "Partner status",
  "SELECT A RESIDENT": "Select a partner", "Touch a resident in the habitat.": "Tap a partner in the habitat.",
  "TAP A RESIDENT": "Tap a partner to see its status",
  "Original toolbar structure, commands unverified": "Toolbar layout; commands not yet confirmed",
  "TRAINING TOOLBAR · MODE 1": "Raising toolbar · Mode 1", "8-SLOT SHELL · ROM VERIFIED": "8-slot toolbar · layout verified",
  "Commands, icons, submenu membership, enable mask and slot 7 identity remain unverified.": "Commands, icons, submenu membership, enable conditions and the eighth slot are not yet confirmed.",
  "No Digimon in the roster.": "No partner yet.", "Empty roster.": "Your partner list is empty.",
  "No topic selected.": "No topic selected.", "No fixture selected.": "No event selected.",
  "The original draws this field; this build has no traced source for it": "The source of this field is not yet confirmed",
  "Buy goods, hunt gear, plugins and cages.": "Buy raising goods, hunt gear, plug-ins and cages.",
  "Shop categories": "Shop categories", "Purchased.": "Purchased.", "Not enough Bits.": "Not enough Bits.",
  "You already hold the maximum.": "You already hold the maximum.", "That item is not for sale.": "That item is not on sale yet.",
  "That quantity cannot be bought.": "That quantity cannot be bought.", "Nothing listed in this category yet.": "Nothing in this category yet.",
  "224 encyclopedia slots. Unlock filters remain untraced.": "224 entries in the Database. Unlock filters are not yet confirmed.",
  "Database families": "Database categories", "Return to Raising Home": "Back to ranch", "Return to database list": "Back to the Database list",
  "This slot is in the 224-entry book. Unlock/filter logic is untraced.": "This entry is part of the 224-entry Database. Its unlock and filter conditions are not yet confirmed.",
  "Registered by the opening partner. No Hunt instance yet.": "Registered through your starter partner. None brought back from a hunt yet.",
  "Cage editor": "Cage layout", "One cage per hex. Rank opens 14–20. Overfill is allowed; extra Digimon stress more easily.": "One cage per hex. Your rank opens 14 to 20 hexes. You may go over the suggested capacity, but partners then build up stress more easily.",
  "Ranch hex slots": "Ranch hexes", "Owned cages": "Owned cages", "Keep this ranch layout": "Keep this layout",
  "Lower stand-in rank until title matches write it": "Lower the test rank", "Raise stand-in rank until title matches write it": "Raise the test rank",
  "Placed.": "Placed.", "Removed from the ranch.": "Removed from the ranch.",
  "Layout kept. Save on Home to write it to disk.": "Layout kept. Head back to the ranch to save it.",
  "Select a cage first.": "Select a cage first.", "That cage is already on the ranch.": "That cage is already on the ranch.",
  "That hex already has a cage.": "That hex already has a cage.", "That hex is outside the ranch.": "That hex is outside the ranch.",
  "That hex is still locked.": "That hex is still locked.", "You do not own that cage.": "You do not own that cage yet.",
  "Every owned cage is on the ranch.": "Every cage you own is on the ranch.",
  "GATE SELECT": "Choose a gate", "Rotate the world and focus a biome node.": "Rotate the world and pick where to go.",
  "WORLD DESTINATION NETWORK": "Digital World gate network", "WORLD MODE": "World view", "16 BIOME LINKS": "16 regions",
  "LIST VIEW": "List view", "WORLD VIEW": "World view", "DRAG TO ROTATE · TAP A NODE TO FOCUS": "Drag to rotate · Tap a region",
  "SELECT A BIOME": "Choose a region", "DESTINATION NODE --": "Destination --", "STANDBY": "Waiting", "READY": "Ready",
  "DESTINATION INFORMATION": "Destination info", "DESTINATION": "Destination", "ACCESSIBLE DESTINATION LIST": "Destinations",
  "LOW GRAPHICS / DEVELOPER FALLBACK": "Low-graphics mode", "Biome destinations": "Regions you can visit",
  "HUNT LOADOUT": "Hunt loadout", "EXPEDITION CONFIGURATION": "Getting ready", "Equip your tools and fit your plugins.": "Choose your gear and fit your plug-ins.",
  "Equipment classes": "Gear types", "Plugin positions": "Plug-in slots", "None owned": "None owned", "BEGIN HUNT": "Start hunt",
  "ROPE": "Rope", "SHOT": "Shooter", "WIRE": "Wire", "ENTRAP": "Lure", "DAMAGE TRAP": "Damage trap",
  "DURABILITY": "Durability", "Durability": "Durability", "Length": "Length", "LENGTH": "Length", "AMMO": "Ammo", "QUANTITY": "Quantity",
  "Hunt field": "Hunt field", "Exploration field. Touch a creature to draw a circle. Empty ground moves you.": "Hunt field. Tap a creature, then draw a circle around it. Tap open ground to move.",
  "TOUCH A CREATURE AND DRAW A CIRCLE. EMPTY GROUND MOVES YOU.": "Tap a partner, then draw a circle. Tap open ground to move.",
  "Unavailable contextual controls": "Controls not available yet", "CONTEXT BAR": "Toolbar",
  "HUNT RESULT": "Hunt result", "BROUGHT HOME": "Brought home", "EXPEDITION": "Hunt",
  "Name them, then return home. They will be waiting in the habitat.": "Give it a name, then head home. It will be waiting at the ranch.",
  "Match clock": "Match time", "Match record": "Match record", "Health": "HP", "Action resource": "Action gauge",
  "Battle field. The match runs on its own.": "Battle field. The match plays out on its own.", "THE MATCH IS RUNNING.": "Match in progress.",
  "YOUR TEAM": "Your team wins", "OPPONENT": "Opponent wins", "LEVEL": "Draw", "UNDECIDED": "Undecided",
  "IN PROGRESS": "In progress", "TIME UP": "Time up", "TEAM DOWN": "A team is down", "NEITHER SIDE WAS AHEAD.": "Neither side was ahead.",
  "PRIZE": "Prize", "Payout from the title-event record.": "The prize set for this event.",
  "ROM VERIFIED": "Verified from the original", "PRODUCT AUTHORED": "Set by this game",
  "NORMAL": "Standard arena", "GRASS": "Grassland", "COLOSSEUM": "Colosseum", "CYBERSPACE": "Cyberspace", "DESERT": "Desert",
  "DOMESTADIUM": "Dome stadium", "HELL": "Inferno", "ISLAND": "Island", "SOUTHPOLE": "South Pole", "STADIUM": "Stadium", "VOLCANO": "Volcano",
  "A saved game was found but could not be read. You can start a new game.": "A saved game was found, but it could not be read. You can still start a new game.",
  "That saved game could not be opened. Start a new game.": "That saved game could not be opened. Please start a new game.",
  "The live field view is unavailable. Screen controls and save remain available.": "The field view is unavailable right now. Screen controls and saving still work."
});

const TOOL_TIERS_EN = Object.freeze({ Tether: "Rope", "Hold Shot": "Hold shooter", Line: "Wire", Snare: "Lure", Charge: "Damage trap" });
const ANALYZER_EN = Object.freeze({ Hp: "HP", Tp: "TP", Attack: "Attack", Defense: "Defense", Speed: "Speed", Wisdom: "Wisdom", Full: "Full" });
const CHECKER_EN = Object.freeze({ Full: "Full", Generation: "Generation", Alignment: "Attribute", Family: "Family", Size: "Size", Capacity: "Capacity", Resistance: "Resistance", Personality: "Personality" });

export const PATTERNS_EN = Object.freeze([
  [/^ID:([A-Z0-9]+)$/, (code) => `ID: ${code}`],
  [/^Release (.+)\?$/, (name) => `Release ${name}?`],
  [/^Release (.+)$/, (name) => `Release ${name}`],
  [/^Select (.+) biome destination$/, (name) => `Go to ${name}`],
  [/^Record (\d+)$/, (n) => `Event ${n}`],
  [/^(Spring|Summer|Autumn|Winter) — Day (\d+)$/, (season, day) => `${season} · Day ${day}`],
  [/^Required tamer rank: (\d+)\. Check the Battle menu for matches available today\.$/, (rank) => `Requires tamer rank ${rank}. Check the Battle menu for today's matches.`],
  [/^(\d+) scheduled fixtures across four seasons\.$/, (n) => `${n} events across the four seasons.`],
  [/^Entry (\d+) — title string (\d+), body string (\d+)\.$/, (entry, title, body) => `Entry ${entry}: title text ${title}, body text ${body}.`],
  [/^Saved game found: (.+)\.$/, (name) => `Saved game found: ${name}.`],
  [/^Could not start a new game: .+$/, () => "Could not start a new game. Reload the page and try again."],
  [/^Could not load your saved game: .+$/, () => "Could not load your saved game. Reload the page and try again."],
  [/^Championship 2026 could not start: .+$/, () => "The game could not start. Reload the page and try again."],
  [/^A saved game was found but this build cannot open it: .+ Start a new game\.$/, () => "A saved game was found, but this version cannot open it. Please start a new game."],
  [/^Living in (.+)$/, (name) => `Living in ${uiText(name)}`],
  [/^DESTINATION NODE (\d+)$/, (n) => `Destination ${n}`],
  [/^PLUGIN (\d+)$/, (n) => `Plug-in ${n}`],
  [/^MATCH (\d+)$/, (n) => `Match ${n}`],
  [/^SLOT (\d+)$/, (n) => `Slot ${n}`],
  [/^RAW_SLOT_(\d+)$/, (n) => `Unassigned slot ${n}`],
  [/^RAW (\d+)$/, (n) => `Field ${n}`],
  [/^Unavailable field control (\d+)$/, (n) => `Field control ${n} (not available yet)`],
  [/^RAW_SLOT_(\d+), unbound placeholder$/, (n) => `Slot ${n}, not assigned`],
  [/^([\d,]+) (?:BITS|Bits|bit)$/, (n) => `${n} Bits`],
  [/^Buy (.+)$/, (name) => `Buy ${uiText(name)}`],
  [/^Undiscovered slot (\d+)$/, (n) => `Undiscovered entry ${n}`],
  [/^(REGULAR|EGG) · (.+)$/, (kind, state) => `${uiText(kind)} · ${uiText(state)}`],
  [/^RANK (\d+) · (.+) HEX$/, (rank, n) => `Rank ${rank} · ${n} hexes`],
  [/^Empty hex (\d+)$/, (n) => `Empty hex ${n}`],
  [/^Locked hex (\d+)$/, (n) => `Locked hex ${n}`],
  [/^(.+) on hex (\d+)\. (.*)$/, (name, n, effect) => `Hex ${n}: ${uiText(name)}. ${uiText(effect)}`],
  [/^Select (.+)\. (.*)$/, (name, effect) => `Select ${uiText(name)}. ${uiText(effect)}`],
  [/^(\d+) further rows the original shows are not traced yet\.$/, (n) => `${n} more fields from the original are not yet confirmed.`],
  [/^(.+) payout, from the title-event record\.$/, (name) => `The prize set for ${uiText(name)}.`],
  [/^Training Goods (\d+)$/, (n) => `Raising goods ${n}`],
  [/^Hunt Item (\d+)$/, (n) => `Hunt item ${n}`],
  [/^Plugin (\d+)$/, (n) => `Plug-in ${n}`],
  [/^Cage (\d+)$/, (n) => `Cage ${n}`],
  [/^(Tether|Hold Shot|Line|Snare|Charge) (I{1,3})$/, (kind, tier) => `${TOOL_TIERS_EN[kind]} ${tier.length}`],
  [/^Card (\d+)G$/, (n) => `Memory card ${n}G`],
  [/^(Hp|Tp|Attack|Defense|Speed|Wisdom|Full) Analyzer$/, (key) => `${ANALYZER_EN[key]} analyzer`],
  [/^(.+) Checker$/, (key) => `${CHECKER_EN[key] ?? "Status"} checker`],
  [/^(Stage Radar|Attribute Radar|Capacity Readout)$/, (key) => ({ "Stage Radar": "Generation radar", "Attribute Radar": "Attribute radar", "Capacity Readout": "Capacity readout" })[key]],
  [/^(durability|Durability|DURABILITY|length|Length|LENGTH|AMMO|QUANTITY) (.+)$/, (key, n) => `${uiText(key)} ${n}`],
  [/^x(\d+)$/, (n) => `Qty ${n}`]
]);

// zh-Hant source string -> English. Grouped by where the string is shown.
// "context|source" entries tell apart a word with two meanings.
export const TEXT_EN = Object.freeze({
  "返回": "Back", "開始對戰": "Start battle",
  "{name} 回到了培育蛋。": "{name} returned to an egg.",
  "點選夥伴查看狀態・左右滑動查看牧場": "Tap a partner to see its status · Swipe to look around the ranch",
  "選取的夥伴": "Selected Partner",
  "上一隻夥伴": "Previous Partner",
  "下一隻夥伴": "Next Partner",
  "這隻夥伴的詳細資料暫時無法顯示。": "This partner's details can't be shown right now.",
  "夥伴消失了。": "A partner has disappeared.",
  "已取得 {count} / {total}": "Earned {count} / {total}",
  "徽章 {number}": "Medal {number}",
  "{season} 第 {day} 日": "{season} · Day {day}",
  "{number}. {name}，{status}": "{number}. {name}, {status}",

  "日本語": "日本語",
  "徽章收藏": "Medal collection",
  "61 場頭銜賽的勝利紀錄": "Victories in 61 title matches",
  "收藏": "Collection",
  "尚未取得徽章。贏得頭銜賽後，徽章會記錄在這裡。": "No medals yet. Win a title match to add its medal here.",
  "每一枚徽章，都是一場頭銜賽的勝利紀錄。": "Each medal records a title-match victory.",
  "61 枚頭銜賽徽章": "61 title-match medals",
  "徽章詳情": "Medal details",
  "已取得": "Earned",
  "未取得": "Not earned",
  "取得方式": "How to earn",
  "贏得這場頭銜賽。": "Win this title match.",
  "取得條件尚待查證。": "The earning condition still needs verification.",
  "賽事日期": "Match date",
  "尚待查證": "Not yet verified",
  "取得時間": "Date earned",
  "此存檔未記錄取得日期。": "This save does not record the date earned.",
  "關閉詳情": "Close details",

  "目前僅戰鬥文字支援日文；其餘介面使用繁體中文。": "Japanese currently applies to battle text only; other interface text stays in Traditional Chinese.",
  // ---- Shared words ---------------------------------------------------------
  "數碼獸冠軍賽 — 2026": "Cable Partners: Championship Beyond the Noise — 2026",
  "位元幣": "Bits",
  "{bits} 位元幣": "{bits} Bits",
  "持有 {bits} 位元幣": "You have {bits} Bits",
  "返回牧場": "Back to ranch",
  "關閉": "Close",
  "state|關閉": "Off",
  "開啟": "On",
  "state|開啟": "On",
  "取消": "Cancel",
  "確認": "OK",
  "決定": "Confirm",
  "是": "Yes",
  "否": "No",
  "完成": "Done",
  "設定": "Settings",
  "管理": "Manage",
  "對戰": "Battle",
  "獎金": "Prize",
  "資料": "Data",
  "menu|資料": "Reference",
  "無": "None",
  "？？？": "???",
  "繁體中文": "繁體中文",
  "頭銜賽": "Title matches",
  "chip|頭銜賽": "Titles",

  // ---- Title and opening ------------------------------------------------------
  "開始新遊戲": "New game",
  "繼續遊戲": "Continue",
  "要開始新遊戲嗎？": "Start a new game?",
  "目前存檔「{name}」會在完成開場命名後被新遊戲取代，而且無法復原。想接著玩請選「繼續遊戲」。": "Your current save \"{name}\" will be replaced by the new game once you finish naming in the opening, and this can't be undone. To keep playing it, choose Continue.",
  "目前的存檔會在完成開場命名後被新遊戲取代，而且無法復原。想接著玩請選「繼續遊戲」。": "Your current save will be replaced by the new game once you finish naming in the opening, and this can't be undone. To keep playing it, choose Continue.",
  "無法開始新遊戲：{reason}": "Could not start a new game: {reason}",
  "無法讀取存檔：{reason}": "Could not load your saved game: {reason}",
  "開啟信件": "Open the letter",
  "信件": "Letter",
  "數位競技場": "Digital Arena",
  "請輸入馴獸師姓名": "Enter your tamer name",
  "請替數碼蛋取名字": "Name your Creature Egg",
  "請輸入一至五個字。": "Enter 1 to 5 characters.",
  "馴獸師姓名使用「{name}」嗎？": "Use \"{name}\" as your tamer name?",
  "從現在起，你也是數碼獸馴獸師了。\n與夥伴一起，朝冠軍賽優勝邁進吧！\n贈禮應該就快送到了。": "From today, you are a tamer too.\nTogether with your partner, aim to win the Championship!\nYour gift should arrive very soon.",
  "這顆數碼蛋送給你。\n請替牠取個名字。": "This Creature Egg is for you.\nPlease give it a name.",
  "歡迎來到數位世界。\n首先，請輸入姓名，完成馴獸師登錄。": "Welcome to the Digital World.\nFirst, enter your name to register as a tamer.",
  "每四年舉辦一次的\n數碼獸冠軍賽。": "Once every four years comes\nthe Championship.",
  "取得參賽資格，\n正是身為真正數碼獸馴獸師的證明。": "Earning a place in it\nis the proof of a true tamer.",
  "而今天，你也迎來了\n參加數碼獸冠軍賽的機會。\n\n奪下勝利吧！\n數碼獸冠軍賽！": "And today, your own chance\nto enter the Championship has come.\n\nGo and win it!\nThe Championship!",
  "好像已經收到郵件了。": "Looks like some mail has arrived.",
  "開場故事，閱讀後點按繼續": "Opening story. Tap to continue after reading.",

  // ---- Save status (status bar, save details, settings) -------------------------
  "保存中": "Saving",
  "已存到本機": "Saved on this device",
  "保存失敗，點一下查看": "Save failed. Tap for details",
  "保存失敗": "Save failed",
  "遊戲狀態": "Game status",
  "第 {n} 日": "Day {n}",
  "今日有 {count} 場頭銜賽，開啟對戰選單": { one: "{count} title match today. Open the Battle menu", other: "{count} title matches today. Open the Battle menu" },
  "目前沒有進行中的遊戲。": "No game in progress.",
  "上次保存失敗；可在畫面上方的保存狀態重試。": "The last save failed. You can retry from the save status at the top of the screen.",
  "已存到本機（{time}）。": "Saved on this device ({time}).",
  "已存到本機。": "Saved on this device.",
  "上次寫入後遊戲又有進展，重要操作或離開頁面時會保存。": "The game has moved on since the last save. It saves after important actions and when you leave the page.",
  "存檔只保存在這台裝置的這個瀏覽器。目前沒有帳號或雲端同步，換裝置或清除網站資料後無法取回。": "Your save is kept only in this browser on this device. There is no account or cloud sync yet, so it can't be recovered on another device or after clearing site data.",
  "購買、改名、確認設施配置、報名與對戰結算後會自動保存；離開頁面、換日與「保存並結束」也會保存。": "The game saves automatically after purchases, renames, confirmed cage layouts, registrations and battle results, and also when you leave the page, end the day, or choose Save & quit.",
  "另一個分頁已寫入較新的存檔，這個分頁不會覆蓋它。請關閉其他分頁後重新開啟遊戲。": "Another tab wrote a newer save, and this tab won't overwrite it. Close the other tab, then reopen the game.",
  "這次沒有寫入本機存檔。可以再試一次；若仍失敗，請確認瀏覽器沒有封鎖網站資料或處於私密瀏覽。": "The save was not written to this device. You can try again; if it still fails, check that your browser isn't blocking site data or in private browsing.",
  "再試一次": "Try again",
  "有變更正在等待寫入。": "Changes are waiting to be saved.",
  "上次寫入後遊戲又有進展（上次：{time}）。": "The game has moved on since the last save (last saved {time}).",
  "上次寫入後遊戲又有進展。": "The game has moved on since the last save.",
  "存檔狀態": "Save status",
  "知道了": "Got it",

  // ---- Toolbar and menus -----------------------------------------------------------
  "階級、戰績與收納容量": "Rank, record and capacity",
  "全年頭銜賽與登錄": "The year's title matches and registration",
  "調整牧場設施位置": "Arrange the cages on your ranch",
  "夥伴名單與能力值": "Your partners and their stats",
  "結束今天，進入隔天": "End today and move to the next day",
  "操作與規則說明": "Controls and rules",
  "儲存進度並回到標題": "Save your progress and return to the title",
  "已登錄的數碼獸": "Registered Partners",
  "前往傳送門捕捉數碼獸": "Go through a gate to capture creatures",
  "參加比賽贏得獎金": "Enter matches to win prizes",
  "購買食物、道具與設施": "Buy food, items and cages",
  "主題、畫質、聲音與語言": "Theme, quality, sound and language",
  "夥伴與牧場": "Partners & ranch",
  "紀錄": "Records",
  "出發": "Go",

  // ---- Raising Home -------------------------------------------------------------------
  "另一個分頁已更新存檔。請先匯出這裡的進度，再重新載入並選擇繼續遊戲。": "Another tab updated the save. Export the progress here first, then reload and choose Continue.",
  "春季": "Spring",
  "夏季": "Summer",
  "秋季": "Autumn",
  "冬季": "Winter",
  "點選數碼獸查看狀態・左右滑動查看牧場": "Tap a partner to see its status · Swipe to look around the ranch",
  "選取的數碼獸": "Selected Partner",
  "詳細": "Details",
  "上一隻數碼獸": "Previous Partner",
  "下一隻數碼獸": "Next Partner",
  "取消選取": "Deselect",
  "匯出未存成功的進度": "Export unsaved progress",
  "收合詳細資料": "Close details",
  "收合": "Close",
  "夥伴名單": "Partners",
  "確認新日期，返回育成": "Confirm the new date and return to raising",
  "結束今天": "End today",
  "要結束今天嗎？": "End today?",
  "病毒": "Virus",
  "疫苗": "Vaccine",
  "龍": "Dragon",
  "獸": "Beast",
  "水": "Aquatic",
  "鳥": "Bird",
  "機械": "Machine",
  "聖": "Holy",
  "昆蟲植物": "Insect & Plant",
  "暗": "Dark",
  "耐熱": "Heat res.",
  "耐寒": "Cold res.",
  "耐雷": "Thunder res.",
  "耐暗": "Dark res.",
  "耐光": "Light res.",
  "飽足": "Fullness",
  "壓力": "Stress",
  "親密": "Affection",
  "友情": "Friendship",
  "疲勞": "Fatigue",
  "這隻數碼獸的詳細資料暫時無法顯示。": "This partner's details can't be shown right now.",
  "{name}，查看詳細資料": "{name}, see details",
  "新的通知已送達。": "A new notice has arrived.",
  "{season}　{day} 日": "{season} · Day {day}",
  "{name} 進化成了{species}。": "{name} evolved into {species}.",
  "{name} 回到了數碼蛋。": "{name} returned to a Creature Egg.",
  "數碼獸消失了。": "A partner has disappeared.",
  "進化!!": "Evolution!!",

  // ---- Partners (roster) ---------------------------------------------------------------
  "熱": "Heat",
  "寒": "Cold",
  "雷": "Thunder",
  "光": "Light",
  "闇": "Dark",
  "暱稱": "Nickname",
  "容量": "Capacity",
  "攻擊": "Attack",
  "防禦": "Defense",
  "智力": "Wisdom",
  "速度": "Speed",
  "特殊技能Ⅰ": "Special skill I",
  "特殊技能Ⅱ": "Special skill II",
  "戰鬥次數": "Battles",
  "勝率": "Win rate",
  "退化次數": "Returns to Creature Egg",
  "性格": "Personality",
  "抗性": "Resistance",
  "移除與報名尚未開放。": "Remove and Enter are not available yet.",
  "新的暱稱": "New nickname",
  "儲存名稱": "Save name",
  "初始夥伴的名字在開場時決定，無法更改。": "Your starter partner's name was set in the opening and can't be changed.",
  "名稱需為 1 至 {max} 個字。": "Names must be 1 to {max} characters.",
  "這隻數碼獸的名字無法更改。": "This partner's name can't be changed.",

  // ---- Help, tamer info, schedule ------------------------------------------------------------
  "系統": "System",
  "說明": "Help",
  "點選主題閱讀說明。分類與主題依原作順序排列。": "Tap a topic to read it. Sections and topics follow the original's order.",
  "說明內容": "Help text",
  "依原作順序列出 {topics} 個說明主題與 {headings} 個分類標題。分類與主題的從屬關係尚待確認。": "{topics} help topics and {headings} section headings, in the original's order. Which topic belongs to which section is not yet confirmed.",
  "未確認欄位": "Unconfirmed field",
  "共 {total} 個欄位，其中 {unsourced} 個欄位的資料來源尚待確認，以橫線表示，並非零。": "{total} fields; the source of {unsourced} of them is not yet confirmed. Those are shown as dashes, not as zeros.",
  "點選賽事查看報名費、獎金與參賽階級。今天可參加的賽事會標示出來。": "Tap an event to see its entry fee, prize and required rank. Events you can enter today are marked.",
  "賽事詳細": "Event details",
  "{rank} 以上": "{rank} or higher",
  "不限": "Any",
  "參賽階級": "Required rank",
  "持有金額": "Bits held",
  "持有金額不足以支付報名費。": "You don't have enough Bits for the entry fee.",
  "馴獸師階級達到 {rank} 後才能登錄這場比賽。": "You can register for this match at tamer rank {rank}.",
  "已獲勝": "Won",
  "取消登錄": "Cancel registration",
  "登錄比賽": "Register",
  "四季共 {count} 場預定賽事。": { one: "{count} scheduled event across the four seasons.", other: "{count} scheduled events across the four seasons." },
  "取消登錄世界冠軍賽": "Cancel World Championship registration",
  "取消登錄冠軍賽": "Cancel Championship registration",
  "登錄世界冠軍賽": "Register for the World Championship",
  "登錄冠軍賽": "Register for the Championship",

  // ---- Championship run -------------------------------------------------------------------------
  "{event} 預賽第 {round} 戰 / 共 {total} 戰": "{event} qualifier: round {round} of {total}",
  "世界大會": "World Championship",
  "冠軍大會": "Championship",
  "贏得冠軍大會後開放。": "Opens after you win the Championship.",
  "馴獸師階級到達後開放。": "Opens when you reach the required tamer rank.",
  "尚未報名。請在賽程登記後再來。": "Not registered. Register in the Schedule, then come back.",
  "多輪賽事": "Multi-round events",
  "返回對戰選單": "Back to the Battle menu",
  "{count} 輪": { one: "{count} round", other: "{count} rounds" },
  "無法開始這場賽事。": "This event can't be started.",
  "賽事結束": "Event over",
  "勝": "Won",
  "敗": "Lost",
  "選擇本輪參賽數碼獸；確認後抽出對手。": "Choose your partners for this round; the opponent is drawn once you confirm.",
  "開始第 {round} 戰": "Start round {round}",
  "選擇參賽數碼獸": "Choose your partner",
  "最多 {limit} 隻": "Up to {limit}",
  "目前沒有可以參賽的數碼獸。": "You have no partner that can enter right now.",
  "隊伍資料讀取失敗，請返回後再試。": "Couldn't load your team. Go back and try again.",
  "目前無法開始這一輪。": "This round can't be started right now.",
  "領取 {bits} 位元幣": "Collect {bits} Bits",
  "結束賽事": "End event",
  "獲得 {bits} 位元幣。": "You received {bits} Bits.",
  "本次沒有獎金。": "No prize this time.",
  "無法結算這場賽事。": "This event couldn't be settled.",

  // ---- Battle entry and preparation messages ---------------------------------------------------------
  "隊伍或遊戲進度已更新，請重新選擇。": "Your team or game progress has changed. Please choose again.",
  "另一個分頁正在遊玩。請先關閉該分頁，再開始遊戲。": "The game is open in another tab. Close that tab first, then start the game.",
  "另一個分頁正在遊玩。請先關閉該分頁，再繼續遊戲。": "The game is open in another tab. Close that tab first, then continue.",
  "這場對戰最多 {count} 隻。": "This battle allows up to {count} partners.",
  "同一隻數碼獸只能加入一隊。": "A partner can only join one team.",
  "無法建立通訊邀請碼，請重新選擇隊伍。": "Couldn't create a link invite code. Please choose your team again.",
  "通訊碼內含不能參戰的數碼獸。": "The link code contains a partner that can't battle.",
  "通訊碼無法辨識、已損壞，或不是同一場邀請。": "The link code can't be read, is damaged, or belongs to a different invite.",
  "通訊對戰準備失敗，請重新交換通訊碼。": "Link battle setup failed. Please exchange codes again.",
  "請選擇 1 至 3 隻數碼獸。": "Choose 1 to 3 partners.",
  "請輸入 A 隊與 B 隊的密碼。": "Enter the passwords for Team A and Team B.",
  "密碼無法辨識或校驗不正確，請確認後再輸入。": "The password can't be read or its check failed. Please check it and enter it again.",
  "密碼隊伍準備失敗，請重新輸入。": "The password team couldn't be prepared. Please enter it again.",
  "隊伍或遊戲進度已更新，請重新選擇參賽隊伍。": "Your team or game progress has changed. Please choose your team again.",
  "請選擇 1 至 {limit} 隻符合條件的數碼獸。": "Choose 1 to {limit} eligible partners.",
  "選擇的數碼獸已不在目前名冊。": "A partner you chose is no longer in your roster.",
  "這場比賽不符合目前日期或資格，請重新選擇。": "This match doesn't fit today's date or your eligibility. Please choose again.",
  "遊戲進度已更新，請重新選擇參賽隊伍。": "Your game progress has changed. Please choose your team again.",
  "遊戲場景尚未就緒，請返回牧場後重試。": "The game scene isn't ready yet. Return to the ranch and try again.",
  "目前日期或參賽資格已改變，請重新選擇賽事。": "Today's date or your eligibility has changed. Please choose a match again.",
  "這隻數碼獸的個體資料尚未完整。": "This partner's individual data is incomplete.",
  "這隻數碼獸還太幼小，暫時無法參賽。": "This partner is too young to battle yet.",
  "這隻數碼獸目前的身體狀況無法參賽。": "This partner isn't fit to battle right now.",
  "這隻數碼獸不符合本場比賽的參賽條件。": "This partner doesn't meet this match's entry conditions.",
  "密碼中沒有可參戰的數碼獸。": "The password has no partner that can battle.",
  "密碼中含有目前不能參戰的數碼獸。": "The password contains a partner that can't battle right now.",
  "這隻數碼獸還不能密碼化。": "This partner can't be saved as a password yet.",
  "單隻對戰": "Single battle",
  "三隻對戰": "Three-partner battle",
  "頭銜 {id}": "Title {id}",
  "通訊對戰": "Link Battle",
  "密碼對戰": "Password Battle",
  "練習對戰": "Practice Battle",
  "自由對戰": "Free Battle",
  "{event} 第 {round} 戰": "{event}, round {round}",
  "返回賽事": "Back to the event",

  // ---- Battle menu, party, password and link ------------------------------------------------------------
  "戰鬥選單立方體，拖曳或使用左右方向鍵旋轉": "Battle menu cube. Drag it or use the left and right arrow keys to turn it.",
  "對戰模式": "Battle modes",
  "此模式尚未開放": "This mode isn't available yet",
  "對戰清單載入失敗，請重新選擇模式。": "Couldn't load the match list. Please choose a mode again.",
  "對戰場地": "Arena",
  "隨機場地": "Random arena",
  "持有金額不足。報名費 {fee} 位元幣；持有 {wallet} 位元幣。": "Not enough Bits. Entry fee {fee} Bits; you have {wallet} Bits.",
  "持有金額不足。 報名費 {fee} 位元幣；持有 {wallet} 位元幣。": "Not enough Bits. Entry fee {fee} Bits; you have {wallet} Bits.",
  "目前無法參加這場對戰。": "You can't enter this battle right now.",
  "參賽隊伍載入失敗，請再試一次。": "Couldn't load the teams. Please try again.",
  "HP {hp}／{maxHp}　TP {tp}／{maxTp}": "HP {hp}/{maxHp} · TP {tp}/{maxTp}",
  "目前沒有符合這場比賽條件的數碼獸。": "None of your partners meet this match's conditions right now.",
  "對戰準備失敗，請再試一次。": "Battle setup failed. Please try again.",
  "返回賽事選擇": "Back to match selection",
  "將自己培育的數碼獸分成兩隊，每隊最多 3 隻。": "Split your own partners into two teams of up to 3 each.",
  "開始練習": "Start practice",
  "A 隊 {a}／3　B 隊 {b}／3": "Team A {a}/3 · Team B {b}/3",
  "{team} 隊": "Team {team}",
  "{name} {team} 隊": "{name}, Team {team}",
  "練習對戰需要至少兩隻可以參賽的數碼獸。": "Practice battles need at least two partners that can battle.",
  "密碼對戰載入失敗，請再試一次。": "Couldn't load Password Battle. Please try again.",
  "輸入兩組隊伍密碼。每組密碼可還原最多 3 隻數碼獸。": "Enter two team passwords. Each password restores up to 3 partners.",
  "{team} 隊密碼": "Team {team} password",
  "開始密碼對戰": "Start Password Battle",
  "密碼對戰準備失敗，請再試一次。": "Password Battle setup failed. Please try again.",
  "我的隊伍密碼": "My team password",
  "選擇最多 3 隻自己的數碼獸，產生可以分享給朋友的密碼。密碼保存的是現在的狀態。": "Choose up to 3 of your partners to make a password you can share with friends. The password keeps their state as it is now.",
  "產生密碼": "Make password",
  "複製密碼": "Copy password",
  "目前沒有可以密碼化的數碼獸。": "You have no partner that can be saved as a password right now.",
  "密碼產生失敗，請再試一次。": "Couldn't make the password. Please try again.",
  "已複製密碼。": "Password copied.",
  "請長按密碼欄位手動複製。": "Press and hold the password field to copy it yourself.",
  "通訊對戰載入失敗，請再試一次。": "Couldn't load Link Battle. Please try again.",
  "兩台裝置交換邀請碼與回覆碼，完成後雙方會看到同一場對戰。": "Two devices exchange an invite code and a reply code; then both see the same battle.",
  "建立邀請": "Create invite",
  "加入邀請": "Join invite",
  "選擇參賽數碼獸（1 至 3 隻）": "Choose your partners (1 to 3)",
  "通訊對戰準備失敗，請再交換一次通訊碼。": "Link battle setup failed. Please exchange codes again.",
  "邀請碼": "Invite code",
  "對方回覆碼": "Their reply code",
  "產生邀請碼": "Make invite code",
  "讀取回覆並開始": "Read reply and start",
  "對方邀請碼": "Their invite code",
  "回覆碼": "Reply code",
  "產生回覆碼": "Make reply code",
  "已分享回覆碼，開始對戰": "Reply code shared: start battle",
  "報名費 {bits} 位元幣": "Entry fee {bits} Bits",
  "獎金 {bits} 位元幣": "Prize {bits} Bits",
  "獎金 {none}": "Prize: {none}",

  // ---- Battle field and result ---------------------------------------------------------------------
  "進行中": "In progress",
  "時間到": "Time up",
  "一方全員倒下": "A team is down",
  "尚未分出勝負": "Undecided",
  "我方獲勝": "Your team wins",
  "對手獲勝": "Opponent wins",
  "雙方平手": "Draw",
  "生命值 {hp} / {max}": "HP {hp} / {max}",
  "正在準備對戰場地…": "Preparing the arena…",
  "對戰進行中": "Battle in progress",
  "離開對戰": "Leave battle",
  "要離開這場對戰嗎？": "Leave this battle?",
  "離開後對戰會中止並記為放棄，不會獲得獎金；已支付的報名費不會退回。": "Leaving stops the battle and counts as a forfeit. You won't get a prize, and the entry fee you paid won't be refunded.",
  "繼續觀戰": "Keep watching",
  "對戰場地載入失敗，請返回牧場後再試。": "The arena couldn't load. Return to the ranch and try again.",
  "雙方都未取得領先。": "Neither side was ahead.",
  "獎金 +": "Prize +",
  "持有金額已達上限": "Your Bits are at the limit",
  "獎金尚未入帳。": "The prize hasn't been credited.",
  "獎金 {bits} 位元幣；持有金額已達上限。": "Prize {bits} Bits; your Bits are at the limit.",
  "本場沒有獲得獎金。": "No prize from this battle.",
  "馴獸師升階": "Tamer rank up",
  "階級 {before} → {after}": "Rank {before} → {after}",
  "取得頭銜": "Title earned",
  "戰績": "Record",
  "對戰場次": "Battles",
  "頭銜數": "Titles",
  "新解鎖": "Newly unlocked",
  "下一頁": "Next",
  "參賽數碼獸": "Participating Partners",
  "輕觸畫面略過": "Tap to skip",

  // ---- Gate, loadout and hunt ------------------------------------------------------------------------
  "馴獸師階級達到 {rank} 後開放。": "Opens at tamer rank {rank}.",
  "取得對應比賽勝利後開放。": "Opens after you win the matching match.",
  "持有金額不足，入場需要 {bits} 位元幣。": "Not enough Bits. Entry costs {bits} Bits.",
  "選擇狩獵場": "Choose a hunting ground",
  "轉動地球，選擇要前往的場地。": "Turn the globe and choose where to go.",
  "場地列表": "List of grounds",
  "拖曳轉動 · 輕觸地點選擇": "Drag to turn · Tap a place to choose it",
  "狩獵場資訊": "Hunting ground info",
  "請選擇目的地": "Choose a destination",
  "入場費": "Entry fee",
  "選擇目的地": "Destination",
  "前往狩獵設定": "Go to hunt setup",
  "返回地球": "Back to the globe",
  "{gate}・日間場地預覽": "{gate}, daytime preview",
  "狩獵設定": "Hunt setup",
  "選擇攜帶的工具與外掛。": "Choose the gear and plug-ins to take.",
  "目的地": "Destination",
  "返回選場": "Back to grounds",
  "開始狩獵": "Start hunt",
  "繩索": "Rope",
  "射擊": "Shooter",
  "鋼索": "Wire",
  "誘引道具": "Lure",
  "傷害陷阱": "Damage trap",
  "尚未持有": "None owned",
  "外掛 {n}": "Plug-in {n}",
  "入場費 {fee} 位元幣 · 持有 {wallet} 位元幣": "Entry fee {fee} Bits · You have {wallet} Bits",
  "此存檔缺少狩獵歷史，暫時無法進入狩獵。": "This save has no hunt history, so hunting isn't available yet.",
  "狩獵進場未完成，遊戲狀態已保留。請重試。": "Entering the hunt didn't finish; your game state is unchanged. Please try again.",
  "正在準備狩獵場…": "Preparing the hunting ground…",
  "狩獵場下載進度": "Hunting ground download progress",
  "狩獵目標資訊": "Target info",
  "輕觸數碼獸查看": "Tap a partner to see it",
  "世代": "Generation",
  "種族": "Family",
  "屬性": "Attribute",
  "記憶卡容量": "Memory card capacity",
  "狩獵雷達": "Hunt radar",
  "狩獵工具": "Hunt gear",
  "拖曳地面移動視野 · 輕觸數碼獸選取": "Drag the ground to look around · Tap a creature to select it",
  "正在返回牧場…": "Returning to the ranch…",
  "正在下載狩獵場 {percent}%": "Downloading the hunting ground: {percent}%",
  "已下載 {size}": "{size} downloaded",
  "正在下載狩獵場…": "Downloading the hunting ground…",
  "網路較慢，仍在下載中；也可以先返回牧場。": "The connection is slow and the download is still running. You can also return to the ranch for now.",
  "狩獵場下載沒有回應，請返回牧場後再試一次。": "The hunting ground download stopped responding. Return to the ranch and try again.",
  "狩獵場載入時間過長，請返回牧場後再試一次。": "The hunting ground took too long to load. Return to the ranch and try again.",
  "剩餘 {time}": "{time} left",
  "野生數碼獸": "Wild Creatures",
  "記憶卡容量不足": "Not enough memory card capacity",
  "繩索斷了": "The rope broke",
  "已收入記憶卡": "Stored on the memory card",
  "道具已用完": "Out of this item",
  "無法放在這個位置": "Can't be placed here",
  "場上的肉餌已滿": "Too much meat bait on the field",
  "場上的道具已滿": "Too many items on the field",
  "快速畫圈綑綁 · 按住目標拉動繩索 · 放鬆可恢復耐久": "Circle quickly to bind · Hold on the target to pull the rope · Ease off to restore durability",
  "按住目標射擊": "Hold on the target to shoot",
  "拖曳拉出鋼索 · 放手完成": "Drag to lay a wire · Release to finish",
  "輕觸地面放置肉餌": "Tap the ground to place meat bait",
  "輕觸放置玩具 · 再輕觸指定移動方向": "Tap to place the toy · Tap again to set its direction",
  "輕觸放置誘引燈 · 夜間吸引目標": "Tap to place a lure light · Attracts targets at night",
  "輕觸放置陷阱 · 困住目標後切換手掌收取": "Tap to place a trap · Once a target is caught, switch to the hand to collect it",
  "輕觸放置炸彈": "Tap to place a bomb",
  "輕觸放置地雷 · 目標經過時引爆": "Tap to place a mine · It goes off when a target passes",
  "拖曳地面移動視野 · 目標倒地後輕觸抓取": "Drag the ground to look around · Tap a downed target to grab it",
  "手": "Hand",

  // Hunt gear names (loadout).
  "基礎捕捉繩 α": "Basic Capture Rope α", "基礎捕捉繩 β": "Basic Capture Rope β", "基礎捕捉繩 γ": "Basic Capture Rope γ",
  "強化捕捉繩 α": "Enhanced Capture Rope α", "強化捕捉繩 β": "Enhanced Capture Rope β", "強化捕捉繩 γ": "Enhanced Capture Rope γ",
  "高階捕捉繩 α": "Advanced Capture Rope α", "高階捕捉繩 β": "Advanced Capture Rope β", "高階捕捉繩 γ": "Advanced Capture Rope γ",
  "頂級捕捉繩 α": "Top-grade Capture Rope α", "頂級捕捉繩 β": "Top-grade Capture Rope β", "頂級捕捉繩 γ": "Top-grade Capture Rope γ",
  "普通射擊 α": "Standard Shot α", "普通射擊 β": "Standard Shot β",
  "連發射擊 α": "Rapid Shot α", "連發射擊 β": "Rapid Shot β",
  "睡眠射擊 α": "Sleep Shot α", "睡眠射擊 β": "Sleep Shot β",
  "麻痺射擊 α": "Stun Shot α", "麻痺射擊 β": "Stun Shot β",
  "散彈 α": "Scatter Shot α", "散彈 β": "Scatter Shot β",
  "麻痺散彈 α": "Stun Scatter Shot α", "麻痺散彈 β": "Stun Scatter Shot β",
  "阻擋鋼索 α": "Barrier Wire α", "阻擋鋼索 β": "Barrier Wire β",
  "磁力鋼索 α": "Magnet Wire α", "磁力鋼索 β": "Magnet Wire β",
  "電擊鋼索 α": "Shock Wire α", "電擊鋼索 β": "Shock Wire β",
  "肉餌": "Meat Bait", "大型肉餌": "Large Meat Bait", "毒肉餌": "Poison Meat Bait", "麻痺肉餌": "Stun Meat Bait",
  "誘導玩具": "Decoy Toy", "強化誘導玩具": "Enhanced Decoy Toy",
  "黃色誘引燈": "Yellow Lure Light", "藍色誘引燈": "Blue Lure Light",
  "爆破彈": "Blast Bomb", "睡眠彈": "Sleep Bomb", "麻痺彈": "Stun Bomb", "閃光彈": "Flash Bomb",
  "地雷": "Mine", "大型地雷": "Large Mine",
  "捕捉陷阱": "Capture Trap", "強化捕捉陷阱": "Enhanced Capture Trap",
  "世代分析": "Generation analysis", "種族分析": "Family analysis", "屬性分析": "Attribute analysis",
  "HP 分析": "HP analysis", "性格分析": "Personality analysis", "容量分析": "Capacity analysis",
  "世代／種族分析": "Generation/family analysis", "世代／種族／屬性分析": "Generation/family/attribute analysis", "完整分析": "Full analysis",
  "射擊數量": "Shot count", "鋼索數量": "Wire count", "誘引道具數量": "Lure count", "傷害陷阱數量": "Damage trap count", "全部道具數量": "All item counts",
  "幼年期雷達": "Baby radar", "成長期雷達": "Child radar", "成熟期雷達": "Adult radar", "完全體雷達": "Perfect radar",
  "資料／自由屬性雷達": "Data/Free attribute radar", "疫苗屬性雷達": "Vaccine attribute radar", "病毒屬性雷達": "Virus attribute radar",
  "龍族雷達": "Dragon radar", "獸族雷達": "Beast radar", "鳥族雷達": "Bird radar", "水族雷達": "Aquatic radar",
  "聖族雷達": "Holy radar", "暗黑族雷達": "Dark radar", "昆蟲植物雷達": "Insect & Plant radar", "機械族雷達": "Machine radar",
  "記憶卡容量顯示": "Memory card capacity readout",
  "記憶卡 32G": "Memory card 32G", "記憶卡 64G": "Memory card 64G", "記憶卡 96G": "Memory card 96G",

  // Hunt target readouts (analyzer plug-ins).
  "數碼蛋": "Creature Egg",
  "幼年期 I": "Baby I", "幼年期 II": "Baby II", "幼年期Ⅰ": "Baby I", "幼年期Ⅱ": "Baby II",
  "成長期": "Child", "成熟期": "Adult", "完全體": "Perfect", "究極體": "Ultimate",
  "昆蟲／植物": "Insect & Plant", "暗黑": "Dark", "自由": "Free",
  "坦率": "Honest", "任性": "Selfish", "急躁": "Impatient", "悠閒": "Easygoing",
  "熱血": "Passionate", "冷靜": "Calm", "大膽": "Bold", "膽小": "Timid",

  // ---- Shop, Database, Cage layout ------------------------------------------------------------------------
  "養成用品": "Raising goods",
  "外掛": "Plug-ins",
  "籠子設施": "Cages",
  "購買完成。": "Purchased.",
  "持有金額不足。": "Not enough Bits.",
  "已達持有上限。": "You already hold the maximum.",
  "此商品目前不販售。": "This item isn't on sale right now.",
  "無法購買這個數量。": "That quantity can't be bought.",
  "用品": "Goods",
  "工具": "Gear",
  "設施": "Cage",
  "商品說明無法顯示。": "This item's description can't be shown.",
  "商店": "Shop",
  "養成用品・狩獵裝備・牧場設施": "Raising goods · Hunt gear · Ranch cages",
  "商品分類": "Item categories",
  "上一項商品": "Previous item",
  "商品選擇": "Items",
  "下一項商品": "Next item",
  "購買": "Buy",
  "商品": "Item",
  "已購買「{item}」，持有 {owned}/{max}。": "Bought {item}. You now have {owned}/{max}.",
  "這個分類目前沒有販售商品。": "Nothing is on sale in this category right now.",
  "{bits} 位元幣 · 持有 {owned}/{max}": "{bits} Bits · Owned {owned}/{max}",
  "已持有": "Owned",
  "已達上限": "Max held",
  "{item}已達持有上限": "{item}: you already hold the maximum",
  "購買{item}": "Buy {item}",
  "已經持有，無法再購買。": "You already own this and can't buy another.",
  "已達持有上限 {max}。": "You already hold the maximum of {max}.",
  "持有金額不足，還差 {bits} 位元幣。": "Not enough Bits. You need {bits} more.",
  "數碼獸圖鑑": "Database",
  "已登錄 {count} / {total}": "Registered {count} / {total}",
  "未登錄 {n}": "Not registered: No. {n}",
  "已登錄": "Registered",
  "尚未登錄這隻數碼獸。": "This partner isn't registered yet.",
  "配置已套用。": "Layout applied.",
  "設施配置": "Cage layout",
  "待機區固定。點選設施取回，再選擇空格放置。": "The Waiting Room is fixed. Tap a cage to take it back, then choose an empty hex to place it.",
  "已放置設施": "Placed cages",
  "牧場平面配置 · 左右滑動查看所有格位": "Ranch layout · Swipe to see every hex",
  // Ranch expansion prototype (2026-10-05): no price, no purchase.
  "牧場平面配置 · 左右滑動查看格位，往下是擴充區": "Ranch layout · Swipe sideways for hexes; the annex is below",
  "擴充區 · 原型（未定價、不收費）": "Annex · prototype (unpriced, free)",
  "擴充區格位": "Annex hexes",
  "加入擴充區（原型，不收費）": "Add annex (prototype, free)",
  "移除擴充區（原型）": "Remove annex (prototype)",
  "先取回擴充區的設施": "Take the annex cages back first",
  "先套用或放棄目前的配置": "Apply or discard the current layout first",
  "已加入擴充區（原型，不收費）。": "Annex added (prototype, free).",
  "擴充區已經開放。": "The annex is already open.",
  "已移除擴充區，牧場回到原本的格數。": "Annex removed; the ranch is back to its own hexes.",
  "請先把擴充區的設施取回，再移除擴充區。": "Take the annex cages back before removing the annex.",
  "這個存檔的牧場仍是舊版配置，暫時不能加入擴充區。": "This save still uses the old ranch layout, so the annex cannot be added yet.",
  "擴充區尚未開放。": "The annex is not open.",
  "確認配置": "Confirm layout",
  "配置還沒有套用": "The layout isn't applied yet",
  "這次調整的設施位置尚未確認。要套用後返回牧場，還是放棄這些變更？": "You haven't confirmed the cage positions you changed. Apply them and return to the ranch, or discard the changes?",
  "繼續編輯": "Keep editing",
  "放棄變更": "Discard changes",
  "套用並返回": "Apply and return",
  "階級 {rank} · {used} / {total} 格": "Rank {rank} · {used} / {total} hexes",
  "第 {n} 格：{cage}。{effect}": "Hex {n}: {cage}. {effect}",
  "可放置": "Available",
  "尚未開放": "Locked",
  "取回 {cage}": "Take back {cage}",
  "已持有的設施皆已放置。": "Every cage you own is placed.",
  "選擇{cage}。{effect}": "Select {cage}. {effect}",
  "飼料": "Feed", "蛋白質": "Protein", "傷藥": "Salve", "藥品": "Medicine",

  // Cage effects (cage summaries).
  "防禦上升": "Defense up", "生命值上升": "HP up", "技力上升": "TP up", "攻擊上升": "Attack up",
  "速度上升": "Speed up", "智力上升": "Wisdom up", "回復生命值與壓力": "Recovers HP and stress",
  "自動餵食與清潔": "Feeds and cleans automatically", "對戰次數上升": "Battle count up",
  "資料屬性上升": "Data up", "龍屬性上升": "Dragon up", "獸屬性上升": "Beast up", "水棲屬性上升": "Aquatic up",
  "鳥屬性上升": "Bird up", "蟲草屬性上升": "Insect & Plant up", "暗黑屬性上升": "Dark up", "機械屬性上升": "Machine up",
  "疫苗屬性上升": "Vaccine up", "聖屬性上升": "Holy up", "病毒屬性上升": "Virus up",
  "光耐性上升": "Light resistance up", "熱耐性上升": "Heat resistance up", "冷耐性上升": "Cold resistance up",
  "雷耐性上升": "Thunder resistance up", "闇耐性上升": "Dark resistance up",
  "建議 {count} 隻": "Suggested: {count}",
  "固定待機區": "Fixed Waiting Room",

  // Gate names as the gate catalog carries them (built once, in zh-Hant).
  "戴納草原": "Dyna Grassland", "驅動莽原": "Drive Savanna", "模組之森": "Module Forest", "啟動叢林": "Boot Jungle",
  "黏滑沼澤": "Slimy Swamp", "波浪海岸": "Wave Coast", "南橋峽谷": "Southbridge Valley", "克隆礦坑": "Clone Mines",
  "杜比工廠": "Dolbi Plant", "下水道路": "Sewer Road", "雪之國度": "Snowland", "裂岩地帶": "Crack Rocks",
  "岩漿山脈": "Magma Mountain", "灼熱沙漠": "Scorching Desert", "澄澈綠洲": "Clear Oasis", "臨界遺跡": "Critical Ruins", "教學關卡": "Tutorial",
  // Tamer Info field labels (TAMER_FIELD_LABELS in uiText.js).
  "頭銜完成度": "Titles completed", "圖鑑完成度": "Database completed", "地圖完成度": "Maps completed", "對戰次數": "Battles",
  "名稱": "Name", "階級": "Rank", "遊玩時間": "Play time", "育成執照": "Raising license", "收納容量": "Capacity", "設施格數": "Cage hexes",

  // ---- Settings ---------------------------------------------------------------------------------------------
  "外觀與顯示": "Appearance & display",
  "畫面品質": "Graphics quality",
  "聲音": "Sound",
  "語言": "Language",
  "操作與輔助": "Controls & accessibility",
  "資料與帳號": "Data & account",
  "深色夜景": "Night",
  "深色背景，適合夜間與長時間遊玩。": "A dark background, good for night and long sessions.",
  "藍白清爽": "Clear Blue",
  "明亮的藍白配色，適合白天與戶外。": "Bright blue and white, good for daytime and outdoors.",
  "經典暖黃": "Classic Warm",
  "米黃紙色與琥珀色，柔和的暖色調。": "Cream paper and amber, a soft warm palette.",
  "復古藍金": "Retro Blue & Gold",
  "深藍底、金色緞帶與框線，搭配六角網格的復古風格。": "Deep blue with gold ribbons and frames over a hexagon mesh, a retro look.",
  "跟隨系統": "Match system",
  "系統深色時用深色夜景，淺色時用藍白清爽。": "Night when your system is dark, Clear Blue when it is light.",
  "標準": "Standard",
  "較大": "Larger",
  "大": "Large",
  "顯示全部說明與提示。": "Shows every hint and explanation.",
  "精簡": "Compact",
  "隱藏操作提示與次要說明，數值與按鈕不變。": "Hides control hints and secondary text; numbers and buttons stay.",
  "自動": "Auto",
  "依裝置條件選擇；持續卡頓時只會往下調一次，不會來回切換。": "Chosen from your device. If frames stay slow it steps down once and never switches back and forth.",
  "省電": "Power saving",
  "降低解析度與特效，保留所有必要回饋。": "Lower resolution and effects; every essential cue stays.",
  "平衡": "Balanced",
  "目前的標準畫質。": "The standard quality.",
  "高品質": "High",
  "較高解析度與較多高光碎片，耗電較多。": "Higher resolution and more highlight shards; uses more power.",
  "依裝置的「減少動態效果」設定。": "Follows your device's reduce-motion setting.",
  "減少移動、縮放與閃光，只保留短暫淡入淡出。": "Less movement, zooming and flashing; only short fades remain.",
  "播放完整動畫。": "Plays full animations.",
  "柔和": "Soft",
  "閃光亮度降到約三分之一。": "Flashes are about a third as bright.",
  "完整": "Full",
  "約 3.7 秒的完整演出。": "The full sequence, about 3.7 seconds.",
  "約 2.4 秒；結果與獎勵完全相同。": "About 2.4 seconds; the result and rewards are exactly the same.",
  "此裝置": "This device",
  "帳號偏好": "Account",
  "自動（目前：{tier}）": "Auto (now: {tier})",
  "靜音": "Muted",
  "總音量 {volume}%": "Master volume {volume}%",
  "減少動態：{state}": "Reduce motion: {state}",
  "存檔只在本機": "Save kept on this device only",
  "恢復本分類預設": "Restore defaults for this section",
  "已恢復「{name}」的預設值。遊戲進度不受影響。": "Restored the defaults for {name}. Your game progress is not affected.",
  "主題": "Theme",
  "只改變介面顏色，不會改變角色與場景的原圖。": "Changes interface colors only; character and scene art is never recolored.",
  "目前系統為{mode}，使用「{theme}」。": "Your system is {mode}, so {theme} is used.",
  "深色": "dark",
  "淺色": "light",
  "文字大小": "Text size",
  "這是文字大小的預覽：生命值 128／技力 64。": "Text size preview: HP 128 / TP 64.",
  "資訊密度": "Information density",
  "畫質": "Quality",
  "畫面解析度上限": "Screen resolution cap",
  "立即生效": "Applies now",
  "立體場景解析度上限": "3D view resolution cap",
  "下次進入該畫面時生效": "Applies the next time that screen opens",
  "抗鋸齒": "Anti-aliasing",
  "下次開啟遊戲時生效": "Applies the next time the game starts",
  "高光碎片數": "Highlight shards",
  "下一次演出生效": "Applies to the next highlight",
  "模糊與光暈": "Blur and glow",
  "目前實際使用的參數（{tier}）：": "Parameters in use ({tier}):",
  "像素美術在任何畫質下都以最近點取樣放大，不會變糊。": "Pixel art is always scaled with nearest-neighbor sampling, so it never turns blurry.",
  "不提供 30／60 FPS 選項：對戰與育成時間跟著畫面更新前進，限制幀率會改變遊戲速度。": "There is no 30/60 FPS option: battle and raising time advance with each frame, so capping the frame rate would change the game's speed.",
  "全部靜音": "Mute all",
  "總音量": "Master volume",
  "遊戲音效": "Game sounds",
  "對戰音效與高光演出音效。": "Battle sounds and highlight sounds.",
  "實際音量 = 總音量 × 遊戲音效（目前 {level}%）；靜音時為 0。": "Actual volume = master × game sounds (now {level}%); 0 while muted.",
  "試聽": "Test sound",
  "正在播放試聽音效。": "Playing the test sound.",
  "目前為靜音。": "Sound is muted.",
  "瀏覽器尚未允許播放聲音，請再點一次。": "The browser hasn't allowed sound yet. Tap once more.",
  "本版本沒有背景音樂、介面音效與角色語音，所以不提供這些音量。": "This version has no background music, interface sounds or voices, so there are no volumes for them.",
  "顯示語言": "Display language",
  "切換後立即生效，不會重新開始或改變目前進度。": "Takes effect at once, without restarting or changing your progress.",
  "英文翻譯尚未經母語編輯審校。": "The English text has not been reviewed by a native editor yet.",
  "數碼獸物種名稱與初始夥伴的自動名稱在英文正式名稱核定前，沿用已核定的繁體中文名稱；你取的名字不會被翻譯。": "Until official English names are approved, partner species names and your starter's automatic name keep their approved Traditional Chinese names. Names you give are never translated.",
  "減少動態": "Reduce motion",
  "目前：{state}": "Now: {state}",
  "完整動態": "Full motion",
  "閃光強度": "Flash intensity",
  "高光演出": "Highlight presentation",
  "重要勝利的演出長度。": "How long the presentation for important wins plays.",
  "鍵盤：Tab 移動、方向鍵切換選項、Esc 返回或關閉。": "Keyboard: Tab to move, arrow keys to change a choice, Esc to go back or close.",
  "存檔": "Save",
  "存檔保存在這台裝置的這個瀏覽器（本機）。重要操作後會自動保存；清除網站資料後無法取回。": "Your save is kept in this browser on this device. It saves automatically after important actions; it can't be recovered after clearing site data.",
  "帳號": "Account",
  "尚未提供帳號登入與雲端同步，這台裝置的資料不會上傳。": "Account sign-in and cloud sync aren't available yet. Nothing on this device is uploaded.",
  "標示為「帳號偏好」的設定將來可隨帳號同步；目前與「此裝置」設定一樣只保存在本機。": "Settings marked Account could sync with an account in the future; for now they are stored on this device like the This device settings.",
  "偏好設定": "Preferences",
  "恢復全部設定": "Restore all settings",
  "要恢復全部設定嗎？": "Restore all settings?",
  "主題、畫質、聲音、語言與輔助設定會回到預設值。只會重設設定，不會影響遊戲進度與存檔。": "Theme, quality, sound, language and accessibility settings return to their defaults. Only settings are reset; your progress and save are not affected.",
  "恢復預設": "Restore defaults",
  "全部設定已恢復預設。遊戲進度不受影響。": "All settings are back to their defaults. Your game progress is not affected.",
  "設定未能保存到本機（本次遊玩仍然有效）。": "Settings couldn't be saved on this device (they still apply for this session).",
  "設定由較新的版本建立；這個版本不會覆寫它，變更只在本次遊玩有效。": "These settings were made by a newer version. This version won't overwrite them; changes apply to this session only.",
  "瀏覽器不允許保存網站資料，設定只在本次遊玩有效。": "The browser doesn't allow saving site data, so settings apply to this session only.",
  "正在保存設定…": "Saving settings…",
  "設定已保存到本機（{time}）。": "Settings saved on this device ({time}).",
  "目前使用預設設定。": "Using the default settings.",
  "設定已從本機讀取。": "Settings loaded from this device.",
  "返回設定分類": "Back to settings sections",
  "關閉設定": "Close settings",
  "設定分類": "Settings sections",
  "裝置開啟了省流量模式，自動使用省電。": "Your device has data saver on, so Auto uses Power saving.",
  "裝置記憶體較少，自動使用省電。": "Your device has little memory, so Auto uses Power saving.",
  "裝置處理器核心較少，自動使用省電。": "Your device has few processor cores, so Auto uses Power saving.",
  "自動使用平衡。": "Auto uses Balanced.",
  "畫面持續低於約 35 FPS，已自動改用省電（本次遊玩不會再改回）。": "Frames stayed below about 35 FPS, so Auto switched to Power saving (it won't switch back this session)."
});

// Proper nouns with no approved English form. English shows their approved
// zh-Hant form on purpose, so they are not reported as missing translations.
export const UNTRANSLATED_PROPER_NOUNS = Object.freeze(new Set([
  // Owner-confirmed original egg names; localized note states they retain zh-Hant.
  "星絮蛋", "焰脈蛋", "潮環蛋", "森芽蛋", "雷紋蛋", "月霧蛋", "晶棘蛋", "聖耀蛋",
  ...Object.values(SPECIES_NAMES_ZH),
  ...Object.values(STARTER_NAMES_ZH),
  "浩司", "惠子"
]));
