// Display-only PRODUCT_AUTHORED copy. Never translate identifiers or saved input.
export const UI_COPY = Object.freeze({
  "SWIPE TO VIEW": "滑動查看場地", "Waiting Room": "待機區",
  "Moonwell Pool": "月井池", "Quiet Hollow": "靜謐谷地",
  "TAMER RANK": "馴獸師階級", "ENTRY FEE": "報名費",
  "durability": "耐久度", "length": "長度",
  "HP 分析": "生命值分析",
  "ON MEMORY CARD": "已收入記憶卡", "MEMORY CARD": "記憶卡",
  "RELEASE": "放生", "CANCEL": "取消", "CONFIRM RELEASE": "確認放生",
  "Memory card and Home roster": "記憶卡與育成夥伴名單", "Confirm release": "確認放生",
  "Release is not yet available for this resident.": "目前尚無法放生這隻數碼獸。",
  "Save failed. Your Digimon is still on the memory card. Return Home again to retry.": "儲存失敗，數碼獸仍在記憶卡中。請再次返回育成基地以重試。",
  "Your home roster is full. Your Digimon remains on the memory card.": "育成夥伴名單已滿，數碼獸仍在記憶卡中。",
  "The full cage footprint must fit in free, unlocked cells.": "設施占用的所有格位都必須為已開放的空格。",
  "Waiting Room stays at the ranch entrance.": "待機區固定在育成區入口。",
  "Exploration field. Drag empty ground to look around. Touch a creature to select it.": "狩獵場地。拖曳空地移動視野，點選數碼獸進行選取。",
  "Rotatable world destination view": "可旋轉的世界目的地視圖", "World destination nodes": "世界目的地節點",
  "DIGIMON CHAMPIONSHIP · 2026": "數碼獸冠軍賽 · 2026",
  "RAISING HOME": "育成基地", "Raising Home": "育成基地", "Training": "育成",
  "Spring": "春季", "Summer": "夏季", "Autumn": "秋季", "Winter": "冬季",
  "SPRING": "春季", "SUMMER": "夏季", "AUTUMN": "秋季", "WINTER": "冬季",
  "Day": "日", "END DAY": "結束今天", "End the day": "結束今天",
  "SAVE": "儲存", "BACK": "返回", "RETURN HOME": "返回育成", "CONTINUE": "繼續",
  "NEXT": "下一頁", "LEAVE": "離開", "CONFIRM": "確認", "LIST": "列表",
  "SHOP": "商店", "Shop": "商店", "HUNT": "狩獵", "Hunt": "狩獵",
  "Battle": "對戰", "Battle result": "對戰結果", "DATABASE": "圖鑑", "Database": "圖鑑",
  "HOME": "育成", "CAGE": "設施配置", "CAGES": "育成設施", "GOODS": "育成用品",
  "PLUGINS": "外掛程式", "EGG": "數碼蛋", "EGGS": "數碼蛋", "REGULAR": "一般物種",
  "SPECIES": "物種", "REGISTERED": "已登錄", "STARTER": "初始夥伴", "NEW": "新品",
  "HELD": "已達上限", "BUY": "購買", "Undiscovered": "尚未發現", "Unknown gate": "未知傳送門",
  "GIVEN NAME": "暱稱", "Given name": "暱稱", "NAME": "名稱", "FAMILY": "種族",
  "GEN.": "世代", "ATTR. INDEX": "屬性編號", "none set": "未設定",
  "HP": "生命值", "TP": "技力", "DIGIMON": "數碼獸", "Digimon": "數碼獸",
  "ROSTER": "夥伴名單", "NAME EDIT": "更改名稱", "DELETE": "移除", "ENTRY": "報名",
  "TAMER": "馴獸師", "Tamer": "馴獸師", "TAMER INFO": "馴獸師資料",
  "SCHEDULE": "賽程", "Schedule": "賽程", "TITLE MATCHES": "頭銜賽", "RECORD": "編號",
  "HELP": "說明", "Help": "說明", "Cage Edit": "設施配置", "End Day": "結束今天",
  "Save & Quit": "儲存並離開", "MANAGE": "管理", "SYSTEM": "系統",
  "HAND": "手掌", "FEED": "餵食", "CLEAN": "清潔", "MED": "藥品", "WOUND": "傷藥", "PROTEIN": "蛋白質",
  "Move a resident, or stroke it": "移動或撫摸數碼獸", "Place food beside a resident": "在數碼獸身旁放置食物",
  "Clear droppings and leftovers": "清除排泄物與剩餘食物", "Cure sickness": "治療疾病",
  "Heal injury": "治療傷勢", "Raise attack for a time": "暫時提升攻擊力",
  "Contextual toolbar": "目前場景工具列", "In the original, not yet in this build": "此功能尚未開放",
  "Changes are waiting to be saved.": "有尚未儲存的變更。", "Raising Home is up to date.": "育成狀態已更新。",
  "Raising Home saved.": "育成狀態已儲存。", "Raising Home restored from save.": "已讀取育成存檔。",
  "The last safe Raising Home state was recovered.": "已復原最近一次有效的育成狀態。",
  "Save did not complete. You can try again.": "儲存未完成，請再試一次。",
  "Raising Home status updated.": "育成狀態已更新。", "Raising Home is ready.": "育成基地準備完成。",
  "Saved game restored.": "已讀取存檔。", "Raising Home is ready. Tap a creature to look after them.": "育成基地準備完成，點選數碼獸查看狀態。",
  "Raising Home time": "育成時間", "Playable Raising field": "育成活動場地",
  "LIVE HABITAT": "育成場地", "FIELD ONLINE": "場地已就緒", "COMPANION LINK": "夥伴狀態",
  "SELECT A RESIDENT": "選擇數碼獸", "Touch a resident in the habitat.": "點選場地中的數碼獸。",
  "Original toolbar structure, commands unverified": "工具列結構，指令尚待確認",
  "TRAINING TOOLBAR · MODE 1": "育成工具列 · 模式一", "8-SLOT SHELL · ROM VERIFIED": "八格工具列 · 結構已驗證",
  "Commands, icons, submenu membership, enable mask and slot 7 identity remain unverified.": "指令、圖示、子選單歸屬、啟用條件與第八格用途仍待確認。",
  "No Digimon in the roster.": "目前沒有數碼獸。", "Empty roster.": "夥伴名單是空的。",
  "No topic selected.": "尚未選擇說明主題。", "No fixture selected.": "尚未選擇賽事。",
  "The original draws this field; this build has no traced source for it": "此欄位的資料來源尚待確認",
  "Buy goods, hunt gear, plugins and cages.": "購買育成用品、狩獵裝備、外掛程式與設施。",
  "Shop categories": "商品分類", "Purchased.": "購買成功。", "Not enough Bits.": "持有金額不足。",
  "You already hold the maximum.": "持有數量已達上限。", "That item is not for sale.": "此商品尚未開放購買。",
  "That quantity cannot be bought.": "無法購買此數量。", "Nothing listed in this category yet.": "此分類目前沒有商品。",
  "224 encyclopedia slots. Unlock filters remain untraced.": "圖鑑共有 224 格；解鎖篩選條件尚待確認。",
  "Database families": "圖鑑分類", "Return to Raising Home": "返回育成基地", "Return to database list": "返回圖鑑列表",
  "This slot is in the 224-entry book. Unlock/filter logic is untraced.": "此格屬於 224 格圖鑑，解鎖與篩選條件尚待確認。",
  "Registered by the opening partner. No Hunt instance yet.": "由初始夥伴登錄，尚無狩獵帶回的個體。",
  "Cage editor": "設施配置", "One cage per hex. Rank opens 14–20. Overfill is allowed; extra Digimon stress more easily.": "每個六角格可放一座設施，隨階級開放 14 至 20 格。可以超過建議容納數，但數碼獸較容易累積壓力。",
  "Ranch hex slots": "育成區六角格", "Owned cages": "持有的設施", "Keep this ranch layout": "保留目前設施配置",
  "Lower stand-in rank until title matches write it": "降低目前測試階級", "Raise stand-in rank until title matches write it": "提高目前測試階級",
  "Placed.": "已放置。", "Removed from the ranch.": "已從育成區移除。",
  "Layout kept. Save on Home to write it to disk.": "已保留配置，請返回育成基地儲存。",
  "Select a cage first.": "請先選擇設施。", "That cage is already on the ranch.": "此設施已在育成區中。",
  "That hex already has a cage.": "此格已有設施。", "That hex is outside the ranch.": "此格不在育成區內。",
  "That hex is still locked.": "此格尚未開放。", "You do not own that cage.": "尚未持有此設施。",
  "Every owned cage is on the ranch.": "所有持有的設施都已放入育成區。",
  "GATE SELECT": "選擇傳送門", "Rotate the world and focus a biome node.": "旋轉世界，選擇想前往的地區。",
  "WORLD DESTINATION NETWORK": "數碼世界傳送網路", "WORLD MODE": "世界視圖", "16 BIOME LINKS": "16 個地區連結",
  "LIST VIEW": "列表視圖", "WORLD VIEW": "世界視圖", "DRAG TO ROTATE · TAP A NODE TO FOCUS": "拖曳旋轉 · 點選地區",
  "SELECT A BIOME": "選擇地區", "DESTINATION NODE --": "目的地 --", "STANDBY": "等待選擇", "READY": "已就緒",
  "DESTINATION INFORMATION": "目的地資訊", "DESTINATION": "目的地", "ACCESSIBLE DESTINATION LIST": "目的地列表",
  "LOW GRAPHICS / DEVELOPER FALLBACK": "低圖形需求模式", "Biome destinations": "可前往的地區",
  "HUNT LOADOUT": "狩獵整備", "EXPEDITION CONFIGURATION": "出發準備", "Equip your tools and fit your plugins.": "選擇裝備並安裝外掛程式。",
  "Equipment classes": "裝備種類", "Plugin positions": "外掛程式欄位", "None owned": "尚未持有", "BEGIN HUNT": "開始狩獵",
  "ROPE": "繩索", "SHOT": "射擊器", "WIRE": "攔阻線", "ENTRAP": "誘捕裝置", "DAMAGE TRAP": "傷害陷阱",
  "DURABILITY": "耐久度", "Durability": "耐久度", "Length": "長度", "LENGTH": "長度", "AMMO": "彈藥", "QUANTITY": "數量",
  "Hunt field": "狩獵場地", "Exploration field. Touch a creature to draw a circle. Empty ground moves you.": "狩獵場地。點選數碼獸後畫圈，點選空地則會移動。",
  "TOUCH A CREATURE AND DRAW A CIRCLE. EMPTY GROUND MOVES YOU.": "點選數碼獸後畫圈，點選空地則會移動。",
  "Unavailable contextual controls": "尚未開放的場景控制", "CONTEXT BAR": "場景工具列",
  "HUNT RESULT": "狩獵結果", "BROUGHT HOME": "已帶回育成基地", "EXPEDITION": "狩獵",
  "Name them, then return home. They will be waiting in the habitat.": "取好名字後返回育成基地，牠會在育成場地等你。",
  "Match clock": "對戰時間", "Match record": "對戰紀錄", "Health": "生命值", "Action resource": "行動資源",
  "Battle field. The match runs on its own.": "對戰場地，比賽會自動進行。", "THE MATCH IS RUNNING.": "對戰進行中。",
  "YOUR TEAM": "我方獲勝", "OPPONENT": "對手獲勝", "LEVEL": "雙方平手", "UNDECIDED": "尚未分出勝負",
  "IN PROGRESS": "進行中", "TIME UP": "時間到", "TEAM DOWN": "一方全員倒下", "NEITHER SIDE WAS AHEAD.": "雙方都未取得領先。",
  "PRIZE": "獎金", "Payout from the title-event record.": "此賽事設定的獎金。",
  "ROM VERIFIED": "原作資料已驗證", "PRODUCT AUTHORED": "本作設定",
  "NORMAL": "一般場地", "GRASS": "草原", "COLOSSEUM": "競技場", "CYBERSPACE": "電腦空間", "DESERT": "沙漠",
  "DOMESTADIUM": "室內競技場", "HELL": "地獄", "ISLAND": "島嶼", "SOUTHPOLE": "南極", "STADIUM": "體育場", "VOLCANO": "火山",
  "A saved game was found but could not be read. You can start a new game.": "找到存檔，但無法讀取。你仍可開始新遊戲。",
  "That saved game could not be opened. Start a new game.": "無法開啟此存檔，請開始新遊戲。",
  "The live field view is unavailable. Screen controls and save remain available.": "目前無法顯示場地，仍可使用畫面控制與儲存功能。"
});

export function uiText(value) {
  if (typeof value !== "string") return value;
  if (Object.hasOwn(UI_COPY, value)) return UI_COPY[value];
  for (const [pattern, format] of PATTERNS) {
    const match = value.match(pattern);
    if (match) return format(...match.slice(1));
  }
  return value;
}

const PATTERNS = [
  [/^ID:([A-Z0-9]+)$/, code => `代碼：${code}`],
  [/^Release (.+)\?$/, name => `要放生「${name}」嗎？`],
  [/^Release (.+)$/, name => `放生${name}`],
  [/^Select (.+) biome destination$/, name => `選擇目的地：${name}`],
  [/^Record (\d+)$/, n => `賽事 ${n}`],
  [/^(Spring|Summer|Autumn|Winter) — Day (\d+)$/, (season, day) => `${uiText(season)} · 第 ${day} 日`],
  [/^Required tamer rank: (\d+)\. Check the Battle menu for matches available today\.$/, rank => `需要馴獸師階級 ${rank}。請在對戰選單查看今日開放的賽事。`],
  [/^(\d+) scheduled fixtures across four seasons\.$/, n => `四季合計安排 ${n} 場賽事。`],
  [/^Entry (\d+) — title string (\d+), body string (\d+)\.$/, (entry, title, body) => `條目 ${entry}：標題編號 ${title}，內文編號 ${body}。`],
  [/^Saved game found: (.+)\.$/, name => `找到存檔：${name}。`],
  [/^Could not start a new game: .+$/, () => "無法開始新遊戲，請重新載入後再試一次。"],
  [/^Could not load your saved game: .+$/, () => "無法讀取存檔，請重新載入後再試一次。"],
  [/^Championship 2026 could not start: .+$/, () => "遊戲無法啟動，請重新載入後再試一次。"],
  [/^A saved game was found but this build cannot open it: .+ Start a new game\.$/, () => "找到存檔，但目前版本無法開啟。請開始新遊戲。"],
  [/^Living in (.+)$/, name => `目前位於${uiText(name)}`],
  [/^DESTINATION NODE (\d+)$/, n => `目的地 ${n}`],
  [/^PLUGIN (\d+)$/, n => `外掛程式 ${n}`],
  [/^MATCH (\d+)$/, n => `對戰 ${n}`],
  [/^SLOT (\d+)$/, n => `位置 ${n}`],
  [/^RAW_SLOT_(\d+)$/, n => `未設定欄位 ${n}`],
  [/^RAW (\d+)$/, n => `欄位 ${n}`],
  [/^Unavailable field control (\d+)$/, n => `尚未開放的場地控制 ${n}`],
  [/^RAW_SLOT_(\d+), unbound placeholder$/, n => `欄位 ${n}，尚未設定`],
  [/^([\d,]+) (?:BITS|Bits|bit)$/, n => `${n} 位元幣`],
  [/^Buy (.+)$/, name => `購買${uiText(name)}`],
  [/^Undiscovered slot (\d+)$/, n => `尚未發現的圖鑑位置 ${n}`],
  [/^(REGULAR|EGG) · (.+)$/, (kind, state) => `${uiText(kind)} · ${uiText(state)}`],
  [/^RANK (\d+) · (.+) HEX$/, (rank, n) => `階級 ${rank} · ${n} 格`],
  [/^Empty hex (\d+)$/, n => `空格 ${n}`],
  [/^Locked hex (\d+)$/, n => `尚未開放的格位 ${n}`],
  [/^(.+) on hex (\d+)\. (.*)$/, (name,n,effect) => `第 ${n} 格：${name}。${effect}`],
  [/^Select (.+)\. (.*)$/, (name,effect) => `選擇${name}。${effect}`],
  [/^(\d+) further rows the original shows are not traced yet\.$/, n => `另有 ${n} 個原作欄位的資料來源尚待確認。`],
  [/^(.+) payout, from the title-event record\.$/, name => `${uiText(name)}的設定獎金。`],
  [/^Training Goods (\d+)$/, n => `育成用品 ${n}`],
  [/^Hunt Item (\d+)$/, n => `狩獵道具 ${n}`],
  [/^Plugin (\d+)$/, n => `外掛程式 ${n}`],
  [/^Cage (\d+)$/, n => `育成設施 ${n}`],
  [/^(Tether|Hold Shot|Line|Snare|Charge) (I{1,3})$/, (kind,tier) => `${({Tether:'繩索','Hold Shot':'定身射擊器',Line:'攔阻線',Snare:'誘捕裝置',Charge:'傷害陷阱'})[kind]} ${tier.length}`],
  [/^Card (\d+)G$/, n => `記憶卡 ${n} 容量`],
  [/^(Hp|Tp|Attack|Defense|Speed|Wisdom|Full) Analyzer$/, key => `${({Hp:'生命值',Tp:'技力',Attack:'攻擊',Defense:'防禦',Speed:'速度',Wisdom:'智力',Full:'完整'})[key]}分析器`],
  [/^(.+) Checker$/, key => `${({Full:'完整',Generation:'世代',Alignment:'屬性',Family:'種族',Size:'體型',Capacity:'容量',Resistance:'抗性',Personality:'個性'})[key] ?? '狀態'}檢查器`],
  [/^(Stage Radar|Attribute Radar|Capacity Readout)$/, key => ({'Stage Radar':'世代雷達','Attribute Radar':'屬性雷達','Capacity Readout':'容量顯示器'})[key]],
  [/^(durability|Durability|DURABILITY|length|Length|LENGTH|AMMO|QUANTITY) (.+)$/, (key,n) => `${uiText(key)} ${n}`],
  [/^x(\d+)$/, n => `數量 ${n}`]
];

export const TAMER_FIELD_LABELS = Object.freeze({
  title: '頭銜', guid: '未確認欄位一', map: '未確認欄位二', battle: '對戰', win: '勝利',
  name: '名稱', rank: '階級', money: '持有金額', time: '遊玩時間', license: '執照', have: '持有數量', cage: '設施'
});
