// Vietnamese display copy. PRODUCT_AUTHORED, 2026-10-09.

import { uiText } from "./uiText.js";
import { SPECIES_NAMES_ZH } from "./catalogs.zhHant.js";
import { STARTER_NAMES_ZH } from "./zhHant.js";

export const UI_COPY_VI = Object.freeze({
  "CODE_COPY": "Sao chép mã trao đổi",
  "CODE_COPIED": "Đã sao chép mã trao đổi.",
  "CODE_COPY_MANUAL": "Không thể sao chép tự động. Mã đã được chọn; hãy nhấn giữ hoặc dùng lệnh Sao chép.",
  "TEAM_PICK_HINT": "Chọn 1–3 bạn đồng hành.",
  "TEAM_SELECTED": "Đội đã chọn",
  "TEAM_LOCKED": "Đội của bạn được chốt trong mã này",
  "TEAM_OPPONENT_LOCKED": "Đội đối thủ được chốt trong mã này",
  "TEAM_EXCHANGE_RESET": "Đội hoặc lời mời đã đổi. Mã cũ đã được xóa khỏi màn hình này. Hãy trao đổi lại cả hai mã.",
  "LINK_LOCAL_ONLY": "Trao đổi mã rồi phát lại trận đấu trên từng thiết bị. Không có phòng trực tuyến thời gian thực.",
  "LINK_STEP_1": "Bên mời: chọn đội, tạo và chia sẻ mã mời.",
  "LINK_STEP_2": "Bên tham gia: dán mã mời, chọn đội, tạo và chia sẻ mã trả lời.",
  "LINK_STEP_3": "Bên mời: đọc mã trả lời. Cả hai kiểm tra đội đã chốt rồi bắt đầu phát lại trên thiết bị của mình.",
  "LINK_READ_REPLY": "Đọc mã trả lời và kiểm tra đội",
  "LINK_START_LOCAL": "Đã trao đổi mã — phát lại trên thiết bị này",
  "PASSWORD_LOCAL_STEPS": "Chọn bạn đồng hành và tạo mã để tự động điền đội A. Dán mã của bạn bè vào đội B để phát lại trên thiết bị này. Mã ghi lại trạng thái đội lúc tạo.",
  "PASSWORD_TEAM_LOCKED": "Đội của bạn trong mã đội A",
  "BACKUP_DOWNLOAD": "Tải bản sao lưu trò chơi",
  "BACKUP_HINT": "Tải dữ liệu đầy đủ đã lưu gần nhất, hoặc dữ liệu chưa ghi được gần nhất nếu lưu thất bại. Thao tác này không lưu các thay đổi đang chờ. Hãy giữ gìn tệp đã tải.",
  "BACKUP_PENDING_READY": "Dữ liệu chưa ghi đã được xác thực và gửi cho trình duyệt tải xuống. Dữ liệu lưu hiện có không thay đổi.",
  "BACKUP_STORED_READY": "Dữ liệu đầy đủ đã lưu gần nhất được xác thực và gửi cho trình duyệt tải xuống.",
  "BACKUP_FAILED": "Không tải được bản sao lưu hoặc chưa có dữ liệu đầy đủ hợp lệ. Dữ liệu lưu hiện có không thay đổi.",
  "SAVE_LAST_SUCCESS": "Lần lưu thành công gần nhất: {time}.",
  "SAVE_NO_SUCCESS": "Chưa có thời điểm lưu thành công.",
  "SAVE_PENDING": "Đang chờ lưu trên thiết bị…",

  "MUSIC_VOLUME": "Nhạc",
  "MUSIC_VOLUME_HINT": "Nhạc cho màn hình chính, trang trại, khám phá và chiến đấu.",
  "MUSIC_GESTURE_NOTE": "Nhạc phát sau khi chạm hoặc nhấn phím và tạm dừng khi chuyển sang nền.",
  "RESIDENT_ART_LOADING": "Đang tải hình ảnh bạn đồng hành…",
  "RESIDENT_ART_ERROR": "Không tải được hình ảnh bạn đồng hành. Dữ liệu trò chơi vẫn được giữ.",
  "RESIDENT_ART_RETRY": "Thử tải lại hình ảnh",
  "OPENING_COMIC_LOADING": "Đang tải câu chuyện…",
  "輕觸數碼獸查看": "Nhấn vào đối tác để xem",
  "野生數碼獸": "bạn đồng hành hoang dã",

  "NAME THIS ONE": "Đặt tên",
  "NAMING": "Đang đặt tên",
  "SWIPE TO VIEW": "Vuốt để xem xung quanh",
  "Waiting Room": "Phòng chờ",
  "Moonwell Pool": "Hồ Nguyệt Tỉnh",
  "Quiet Hollow": "Thung lũng tĩnh lặng",
  "TAMER RANK": "Cấp bậc HLV",
  "ENTRY FEE": "Phí tham gia",
  "durability": "độ bền",
  "length": "chiều dài",
  "HP 分析": "Phân tích HP",
  "ON MEMORY CARD": "Trong thẻ nhớ",
  "MEMORY CARD": "Thẻ nhớ",
  "RELEASE": "Thả tự do",
  "CANCEL": "Hủy bỏ",
  "CONFIRM RELEASE": "Xác nhận thả tự do",
  "Memory card and Home roster": "Thẻ nhớ và danh sách trang trại",
  "Confirm release": "Xác nhận thả tự do",
  "Release is not yet available for this resident.": "Hiện chưa thể thả tự do cho bạn đồng hành này.",
  "Save failed. Your Digimon is still on the memory card. Return Home again to retry.": "Lưu thất bại. Bạn đồng hành vẫn còn trong thẻ nhớ. Vui lòng quay về trang trại để thử lại.",
  "Your home roster is full. Your Digimon remains on the memory card.": "Danh sách trang trại đã đầy. Bạn đồng hành vẫn ở lại trong thẻ nhớ.",
  "The full cage footprint must fit in free, unlocked cells.": "Mọi ô của chuồng phải vừa vặn trong các ô trống đã mở khóa.",
  "Waiting Room stays at the ranch entrance.": "Phòng chờ luôn cố định ở lối vào trang trại.",
  "Exploration field. Drag empty ground to look around. Touch a creature to select it.": "Khu vực săn bắt. Kéo khoảng trống để quan sát xung quanh, chạm vào sinh vật để chọn.",
  "Rotatable world destination view": "Bản đồ thế giới xoay được",
  "World destination nodes": "Các khu vực thế giới",
  "DIGIMON CHAMPIONSHIP · 2026": "Cyber Partner: Giải Đấu Phía Sau Tạp Âm · 2026",
  "RAISING HOME": "Trang trại nuôi dưỡng",
  "Raising Home": "Trang trại nuôi dưỡng",
  "Training": "Nuôi dưỡng",
  "Spring": "Mùa xuân",
  "Summer": "Mùa hè",
  "Autumn": "Mùa thu",
  "Winter": "Mùa đông",
  "SPRING": "Mùa xuân",
  "SUMMER": "Mùa hè",
  "AUTUMN": "Mùa thu",
  "WINTER": "Mùa đông",
  "Day": "Ngày",
  "END DAY": "Kết thúc ngày",
  "End the day": "Kết thúc ngày",
  "SAVE": "Lưu",
  "BACK": "Quay lại",
  "RETURN HOME": "Về trang trại",
  "RETURN TO RANCH": "Về trang trại",
  "CONTINUE": "Tiếp tục",
  "NEXT": "Tiếp theo",
  "LEAVE": "Rời đi",
  "CONFIRM": "Xác nhận",
  "LIST": "Danh sách",
  "SHOP": "Cửa hàng",
  "Shop": "Cửa hàng",
  "HUNT": "Săn bắt",
  "Hunt": "Săn bắt",
  "Battle": "Chiến đấu",
  "Battle result": "Kết quả chiến đấu",
  "DATABASE": "Thư viện",
  "Database": "Thư viện",
  "HOME": "Trang trại",
  "CAGE": "Bố trí chuồng",
  "CAGES": "Chuồng trại",
  "GOODS": "Đồ nuôi dưỡng",
  "PLUGINS": "Plug-in",
  "EGG": "Trứng",
  "EGGS": "Trứng",
  "REGULAR": "Loài thông thường",
  "SPECIES": "Loài",
  "REGISTERED": "Đã đăng ký",
  "STARTER": "Bạn đồng hành ban đầu",
  "NEW": "Mới",
  "HELD": "Tối đa có thể giữ",
  "BUY": "Mua",
  "Undiscovered": "Chưa phát hiện",
  "Unknown gate": "Cánh cổng chưa biết",
  "GIVEN NAME": "Biệt danh",
  "Given name": "Biệt danh",
  "NAME": "Tên",
  "FAMILY": "Chủng tộc",
  "GEN.": "Thế hệ",
  "ATTR. INDEX": "Mã thuộc tính",
  "none set": "Chưa thiết lập",
  "HP": "HP",
  "TP": "TP",
  "DIGIMON": "Bạn đồng hành",
  "Digimon": "Bạn đồng hành",
  "ROSTER": "Danh sách đồng đội",
  "NAME EDIT": "Đổi tên",
  "DELETE": "Xóa",
  "ENTRY": "Đăng ký",
  "TAMER": "Huấn luyện viên",
  "Tamer": "Huấn luyện viên",
  "TAMER INFO": "Thông tin HLV",
  "SCHEDULE": "Lịch trình",
  "Schedule": "Lịch trình",
  "TITLE MATCHES": "Trận đấu danh hiệu",
  "RECORD": "Kỷ lục",
  "HELP": "Trợ giúp",
  "Help": "Trợ giúp",
  "Cage Edit": "Bố trí chuồng",
  "End Day": "Kết thúc ngày",
  "Save & Quit": "Lưu & Thoát",
  "MANAGE": "Quản lý",
  "SYSTEM": "Hệ thống",
  "Settings": "Cài đặt",
  "Retry": "Thử lại",
  "Saving...": "Đang lưu…",
  "HAND": "Bàn tay",
  "FEED": "Cho ăn",
  "CLEAN": "Dọn dẹp",
  "MED": "Thuốc",
  "WOUND": "Thuốc mỡ",
  "PROTEIN": "Protein",
  "Move a resident, or stroke it": "Di chuyển hoặc vuốt ve bạn đồng hành",
  "Place food beside a resident": "Đặt thức ăn cạnh bạn đồng hành",
  "Clear droppings and leftovers": "Dọn dẹp chất thải và thức ăn thừa",
  "Cure sickness": "Chữa bệnh",
  "Heal injury": "Trị thương",
  "Raise attack for a time": "Tăng tấn công tạm thời",
  "Contextual toolbar": "Thanh công cụ ngữ cảnh",
  "In the original, not yet in this build": "Tính năng này chưa mở trong phiên bản hiện tại",
  "Changes are waiting to be saved.": "Có thay đổi chưa lưu.",
  "Raising Home is up to date.": "Trạng thái trang trại đã cập nhật.",
  "Raising Home saved.": "Đã lưu trang trại.",
  "Raising Home restored from save.": "Đã khôi phục trang trại từ bản lưu.",
  "The last safe Raising Home state was recovered.": "Đã khôi phục trạng thái an toàn gần nhất của trang trại.",
  "Save did not complete. You can try again.": "Lưu chưa hoàn tất. Bạn có thể thử lại.",
  "Raising Home status updated.": "Đã cập nhật trạng thái trang trại.",
  "Raising Home is ready.": "Trang trại đã sẵn sàng.",
  "Saved game restored.": "Đã khôi phục bản lưu trò chơi.",
  "Raising Home is ready. Tap a creature to look after them.": "Trang trại đã sẵn sàng. Chạm vào bạn đồng hành để chăm sóc.",
  "Raising Home time": "Thời gian nuôi dưỡng",
  "Playable Raising field": "Khu vực nuôi dưỡng hoạt động",
  "LIVE HABITAT": "Khu vực sinh sống",
  "FIELD ONLINE": "Khu vực trực tuyến",
  "COMPANION LINK": "Liên kết đồng đội",
  "SELECT A RESIDENT": "Chọn bạn đồng hành",
  "Touch a resident in the habitat.": "Chạm vào bạn đồng hành trong khu vực.",
  "TAP A RESIDENT": "Chạm vào bạn đồng hành xem trạng thái",
  "Original toolbar structure, commands unverified": "Cấu trúc thanh công cụ gốc, lệnh chưa xác minh",
  "TRAINING TOOLBAR · MODE 1": "Thanh công cụ nuôi dưỡng · Chế độ 1",
  "8-SLOT SHELL · ROM VERIFIED": "Khung 8 ô · Đã xác minh",
  "Commands, icons, submenu membership, enable mask and slot 7 identity remain unverified.": "Lệnh, biểu tượng, menu phụ và ô thứ 7 vẫn đang chờ xác minh.",
  "No Digimon in the roster.": "Hiện không có bạn đồng hành nào trong danh sách.",
  "Empty roster.": "Danh sách trống.",
  "No topic selected.": "Chưa chọn chủ đề.",
  "No fixture selected.": "Chưa chọn trận đấu.",
  "The original draws this field; this build has no traced source for it": "Nguồn dữ liệu của trường này chưa được xác minh",
  "Buy goods, hunt gear, plugins and cages.": "Mua đồ nuôi dưỡng, trang bị săn bắt, plug-in và chuồng trại.",
  "Shop categories": "Danh mục hàng hóa",
  "Purchased.": "Đã mua thành công.",
  "Not enough Bits.": "Không đủ Bits.",
  "You already hold the maximum.": "Số lượng đã đạt giới hạn.",
  "That item is not for sale.": "Vật phẩm này hiện chưa mở bán.",
  "That quantity cannot be bought.": "Không thể mua số lượng này.",
  "Nothing listed in this category yet.": "Chưa có mặt hàng nào trong danh mục này.",
  "224 encyclopedia slots. Unlock filters remain untraced.": "Thư viện 224 ô. Điều kiện mở khóa chưa xác minh.",
  "Database families": "Phân loại thư viện",
  "Return to Raising Home": "Về trang trại",
  "Return to database list": "Quay lại danh sách thư viện",
  "This slot is in the 224-entry book. Unlock/filter logic is untraced.": "Ô này thuộc thư viện 224 mục. Điều kiện mở khóa chưa xác minh.",
  "Registered by the opening partner. No Hunt instance yet.": "Được đăng ký bởi bạn đồng hành ban đầu. Chưa có cá thể săn bắt.",
  "Cage editor": "Bố trí chuồng",
  "One cage per hex. Rank opens 14–20. Overfill is allowed; extra Digimon stress more easily.": "Mỗi ô lục giác đặt được 1 chuồng. Mở 14–20 ô theo cấp. Được phép vượt khuyến nghị nhưng bạn đồng hành sẽ dễ căng thẳng hơn.",
  "Ranch hex slots": "Ô lục giác trang trại",
  "Owned cages": "Chuồng đang sở hữu",
  "Keep this ranch layout": "Giữ bố cục này",
  "Lower stand-in rank until title matches write it": "Hạ cấp bậc thử nghiệm",
  "Raise stand-in rank until title matches write it": "Tăng cấp bậc thử nghiệm",
  "Placed.": "Đã bố trí.",
  "Removed from the ranch.": "Đã dỡ khỏi trang trại.",
  "Layout kept. Save on Home to write it to disk.": "Đã lưu bố cục. Về trang trại lưu để ghi dữ liệu.",
  "Select a cage first.": "Vui lòng chọn chuồng trước.",
  "That cage is already on the ranch.": "Chuồng này đã có trong trang trại.",
  "That hex already has a cage.": "Ô này đã có chuồng.",
  "That hex is outside the ranch.": "Ô này nằm ngoài trang trại.",
  "That hex is still locked.": "Ô này vẫn chưa mở khóa.",
  "You do not own that cage.": "Bạn chưa sở hữu chuồng này.",
  "Every owned cage is on the ranch.": "Mọi chuồng sở hữu đều đã đặt trong trang trại.",
  "GATE SELECT": "Chọn cánh cổng",
  "Rotate the world and focus a biome node.": "Xoay thế giới và chọn khu vực muốn đến.",
  "WORLD DESTINATION NETWORK": "Mạng Lưới Dịch Chuyển Thế Giới",
  "WORLD MODE": "Giao diện thế giới",
  "16 BIOME LINKS": "16 liên kết khu vực",
  "LIST VIEW": "Xem dạng danh sách",
  "WORLD VIEW": "Xem dạng thế giới",
  "DRAG TO ROTATE · TAP A NODE TO FOCUS": "Kéo để xoay · Chạm để chọn khu vực",
  "SELECT A BIOME": "Chọn khu vực",
  "DESTINATION NODE --": "Điểm đến --",
  "STANDBY": "Chờ chọn",
  "READY": "Sẵn sàng",
  "DESTINATION INFORMATION": "Thông tin điểm đến",
  "DESTINATION": "Điểm đến",
  "ACCESSIBLE DESTINATION LIST": "Danh sách điểm đến có thể đến",
  "LOW GRAPHICS / DEVELOPER FALLBACK": "Chế độ đồ họa nhẹ",
  "Biome destinations": "Các khu vực có thể đến",
  "HUNT LOADOUT": "Trang bị săn bắt",
  "EXPEDITION CONFIGURATION": "Chuẩn bị xuất phát",
  "Equip your tools and fit your plugins.": "Trang bị dụng cụ và cài đặt plug-in.",
  "Equipment classes": "Phân loại trang bị",
  "Plugin positions": "Vị trí plug-in",
  "None owned": "Chưa sở hữu",
  "BEGIN HUNT": "Bắt đầu săn bắt",
  "ROPE": "Dây thừng",
  "SHOT": "Súng bắn",
  "WIRE": "Dây cáp",
  "ENTRAP": "Bẫy bắt",
  "DAMAGE TRAP": "Bẫy sát thương",
  "DURABILITY": "Độ bền",
  "Durability": "Độ bền",
  "Length": "Chiều dài",
  "LENGTH": "Chiều dài",
  "AMMO": "Số đạn",
  "QUANTITY": "Số lượng",
  "Hunt field": "Khu vực săn bắt",
  "Exploration field. Touch a creature to draw a circle. Empty ground moves you.": "Khu vực săn bắt. Chạm vào sinh vật rồi vẽ vòng tròn, chạm vào đất trống để di chuyển.",
  "TOUCH A CREATURE AND DRAW A CIRCLE. EMPTY GROUND MOVES YOU.": "Chạm vào sinh vật rồi vẽ vòng tròn. Chạm đất trống để di chuyển.",
  "Unavailable contextual controls": "Điều khiển chưa mở",
  "CONTEXT BAR": "Thanh ngữ cảnh",
  "HUNT RESULT": "Kết quả săn bắt",
  "BROUGHT HOME": "Đã đưa về trang trại",
  "EXPEDITION": "Thám hiểm",
  "Name them, then return home. They will be waiting in the habitat.": "Đặt tên rồi quay về trang trại, bạn đồng hành sẽ chờ bạn ở đó.",
  "Match clock": "Thời gian trận đấu",
  "Match record": "Biên bản trận đấu",
  "Health": "HP",
  "Action resource": "Thanh hành động",
  "Battle field. The match runs on its own.": "Đấu trường. Trận đấu diễn ra tự động.",
  "THE MATCH IS RUNNING.": "Trận đấu đang diễn ra.",
  "YOUR TEAM": "Đội bạn thắng",
  "OPPONENT": "Đối thủ thắng",
  "LEVEL": "Hòa",
  "UNDECIDED": "Chưa ngã ngũ",
  "IN PROGRESS": "Đang diễn ra",
  "TIME UP": "Hết giờ",
  "TEAM DOWN": "Cả đội gục ngã",
  "NEITHER SIDE WAS AHEAD.": "Hai bên ngang tài ngang sức.",
  "PRIZE": "Tiền thưởng",
  "Payout from the title-event record.": "Tiền thưởng thiết lập cho giải đấu này.",
  "ROM VERIFIED": "Dữ liệu gốc đã xác minh",
  "PRODUCT AUTHORED": "Thiết lập của trò chơi",
  "NORMAL": "Đấu trường chuẩn",
  "GRASS": "Đồng cỏ",
  "COLOSSEUM": "Đấu trường La Mã",
  "CYBERSPACE": "Không gian mạng",
  "DESERT": "Sa mạc",
  "DOMESTADIUM": "Sân vận động mái vòm",
  "HELL": "Địa ngục",
  "ISLAND": "Đảo cô độc",
  "SOUTHPOLE": "Nam Cực",
  "STADIUM": "Sân vận động",
  "VOLCANO": "Núi lửa",
  "A saved game was found but could not be read. You can start a new game.": "Tìm thấy bản lưu nhưng không thể đọc. Bạn vẫn có thể bắt đầu trò chơi mới.",
  "That saved game could not be opened. Start a new game.": "Không thể mở bản lưu này. Vui lòng bắt đầu trò chơi mới.",
  "The live field view is unavailable. Screen controls and save remain available.": "Hiện không thể hiển thị khu vực. Các phím điều khiển và lưu vẫn hoạt động bình thường."
});

const TOOL_TIERS_VI = Object.freeze({
  "Tether": "Dây thừng",
  "Hold Shot": "Súng bắn",
  "Line": "Dây cáp",
  "Snare": "Mồi nhử",
  "Charge": "Bẫy"
});
const ANALYZER_VI = Object.freeze({
  "Hp": "HP",
  "Tp": "TP",
  "Attack": "Tấn công",
  "Defense": "Phòng thủ",
  "Speed": "Tốc độ",
  "Wisdom": "Trí tuệ",
  "Full": "Tổng hợp"
});
const CHECKER_VI = Object.freeze({
  "Full": "Tổng hợp",
  "Generation": "Thế hệ",
  "Alignment": "Thuộc tính",
  "Family": "Chủng tộc",
  "Size": "Kích thước",
  "Capacity": "Dung lượng",
  "Resistance": "Kháng tính",
  "Personality": "Tính cách"
});

export const PATTERNS_VI = Object.freeze([
  [/^ID:([A-Z0-9]+)$/, (code) => `ID: ${code}`],
  [/^Release (.+)\?$/, (name) => `Thả tự do cho ${name}?`],
  [/^Release (.+)$/, (name) => `Thả tự do ${name}`],
  [/^Select (.+) biome destination$/, (name) => `Đến ${name}`],
  [/^Record (\d+)$/, (n) => `Giải đấu ${n}`],
  [/^(Spring|Summer|Autumn|Winter) — Day (\d+)$/, (season, day) => `${uiText(season)} · Ngày ${day}`],
  [/^Required tamer rank: (\d+)\. Check the Battle menu for matches available today\.$/, (rank) => `Yêu cầu cấp bậc HLV ${rank}. Kiểm tra Menu chiến đấu để xem các trận hôm nay.`],
  [/^(\d+) scheduled fixtures across four seasons\.$/, (n) => `Tổng cộng ${n} sự kiện qua bốn mùa.`],
  [/^Entry (\d+) — title string (\d+), body string (\d+)\.$/, (entry, title, body) => `Mục ${entry}: tiêu đề ${title}, nội dung ${body}.`],
  [/^Saved game found: (.+)\.$/, (name) => `Tìm thấy bản lưu: ${name}.`],
  [/^Could not start a new game: .+$/, () => "Không thể bắt đầu trò chơi mới. Tải lại trang và thử lại."],
  [/^Could not load your saved game: .+$/, () => "Không thể đọc bản lưu. Tải lại trang và thử lại."],
  [/^Championship 2026 could not start: .+$/, () => "Trò chơi không thể khởi động. Tải lại trang và thử lại."],
  [/^A saved game was found but this build cannot open it: .+ Start a new game\.$/, () => "Tìm thấy bản lưu nhưng phiên bản này không thể mở. Vui lòng bắt đầu trò chơi mới."],
  [/^Living in (.+)$/, (name) => `Đang ở tại ${uiText(name)}`],
  [/^DESTINATION NODE (\d+)$/, (n) => `Khu vực ${n}`],
  [/^PLUGIN (\d+)$/, (n) => `Plug-in ${n}`],
  [/^MATCH (\d+)$/, (n) => `Trận đấu ${n}`],
  [/^SLOT (\d+)$/, (n) => `Vị trí ${n}`],
  [/^RAW_SLOT_(\d+)$/, (n) => `Vị trí chưa gán ${n}`],
  [/^RAW (\d+)$/, (n) => `Trường ${n}`],
  [/^Unavailable field control (\d+)$/, (n) => `Điều khiển ${n} chưa khả dụng`],
  [/^RAW_SLOT_(\d+), unbound placeholder$/, (n) => `Vị trí ${n}, chưa gán`],
  [/^([\d,]+) (?:BITS|Bits|bit)$/, (n) => `${n} Bits`],
  [/^Buy (.+)$/, (name) => `Mua ${uiText(name)}`],
  [/^Undiscovered slot (\d+)$/, (n) => `Mục thư viện chưa phát hiện ${n}`],
  [/^(REGULAR|EGG) · (.+)$/, (kind, state) => `${uiText(kind)} · ${uiText(state)}`],
  [/^RANK (\d+) · (.+) HEX$/, (rank, n) => `Cấp ${rank} · ${n} ô`],
  [/^Empty hex (\d+)$/, (n) => `Ô trống ${n}`],
  [/^Locked hex (\d+)$/, (n) => `Ô bị khóa ${n}`],
  [/^(.+) on hex (\d+)\. (.*)$/, (name, n, effect) => `Ô ${n}: ${uiText(name)}. ${uiText(effect)}`],
  [/^Select (.+)\. (.*)$/, (name, effect) => `Chọn ${uiText(name)}. ${uiText(effect)}`],
  [/^(\d+) further rows the original shows are not traced yet\.$/, (n) => `Còn ${n} trường gốc chưa được xác minh.`],
  [/^(.+) payout, from the title-event record\.$/, (name) => `Phần thưởng thiết lập cho ${uiText(name)}.`],
  [/^Training Goods (\d+)$/, (n) => `Đồ nuôi dưỡng ${n}`],
  [/^Hunt Item (\d+)$/, (n) => `Vật phẩm săn bắt ${n}`],
  [/^Plugin (\d+)$/, (n) => `Plug-in ${n}`],
  [/^Cage (\d+)$/, (n) => `Chuồng ${n}`],
  [/^(Tether|Hold Shot|Line|Snare|Charge) (I{1,3})$/, (kind, tier) => `${TOOL_TIERS_VI[kind]} ${tier.length}`],
  [/^Card (\d+)G$/, (n) => `Thẻ nhớ ${n}G`],
  [/^(Hp|Tp|Attack|Defense|Speed|Wisdom|Full) Analyzer$/, (key) => `Máy phân tích ${ANALYZER_VI[key]}`],
  [/^(.+) Checker$/, (key) => `Máy kiểm tra ${CHECKER_VI[key] ?? "trạng thái"}`],
  [/^(Stage Radar|Attribute Radar|Capacity Readout)$/, (key) => ({ "Stage Radar": "Radar thế hệ", "Attribute Radar": "Radar thuộc tính", "Capacity Readout": "Màn hình dung lượng" })[key]],
  [/^(durability|Durability|DURABILITY|length|Length|LENGTH|AMMO|QUANTITY) (.+)$/, (key, n) => `${uiText(key)} ${n}`],
  [/^x(\d+)$/, (n) => `SL ${n}`]
]);

export const TEXT_VI = Object.freeze({
  // Upstream naming, Retro theme and ranch expansion integration.
  "返回": "Quay lại",
  "開始對戰": "Bắt đầu trận đấu",
  "復古藍金": "Xanh vàng cổ điển",
  "深藍底、金色緞帶與框線，搭配六角網格的復古風格。": "Nền xanh đậm, dải ruy băng và viền vàng cùng lưới lục giác mang phong cách cổ điển.",
  "已加入擴充區（原型，不收費）。": "Đã thêm khu mở rộng (bản thử nghiệm, miễn phí).",
  "擴充區已經開放。": "Khu mở rộng đã được mở.",
  "已移除擴充區，牧場回到原本的格數。": "Đã bỏ khu mở rộng, trang trại trở lại số ô ban đầu.",
  "請先把擴充區的設施取回，再移除擴充區。": "Hãy thu hồi các công trình trong khu mở rộng trước khi bỏ khu này.",
  "這個存檔的牧場仍是舊版配置，暫時不能加入擴充區。": "Bản lưu này vẫn dùng bố cục trang trại cũ nên chưa thể thêm khu mở rộng.",
  "擴充區尚未開放。": "Khu mở rộng chưa được mở.",
  "擴充區 · 原型（未定價、不收費）": "Khu mở rộng · Bản thử nghiệm (chưa định giá, miễn phí)",
  "擴充區格位": "Ô trong khu mở rộng",
  "牧場平面配置 · 左右滑動查看格位，往下是擴充區": "Sơ đồ trang trại · Vuốt trái phải để xem các ô; khu mở rộng nằm bên dưới",
  "移除擴充區（原型）": "Bỏ khu mở rộng (bản thử nghiệm)",
  "加入擴充區（原型，不收費）": "Thêm khu mở rộng (bản thử nghiệm, miễn phí)",
  "先取回擴充區的設施": "Thu hồi công trình trong khu mở rộng trước",
  "先套用或放棄目前的配置": "Áp dụng hoặc hủy bố cục hiện tại trước",

  "{name} 回到了培育蛋。": "{name} đã trở về dạng trứng.",
  "點選夥伴查看狀態・左右滑動查看牧場": "Nhấp vào đối tác để xem trạng thái · Vuốt sang trái hoặc phải để xem trang trại",
  "選取的夥伴": "Đối tác đã chọn",
  "上一隻夥伴": "Đối tác trước",
  "下一隻夥伴": "Đối tác tiếp theo",
  "這隻夥伴的詳細資料暫時無法顯示。": "Chi tiết về đối tác này hiện không thể hiển thị.",
  "夥伴消失了。": "Đối tác đã biến mất.",
  "徽章 {number}": "Huy hiệu {number}",
  "{number}. {name}，{status}": "{number}. {name}, {status}",
  "已取得 {count} / {total}": "Đã nhận được {count} / {total}",
  "{season} 第 {day} 日": "{season} Ngày {day}",
  "日本語": "tiếng Nhật",
  "徽章收藏": "Bộ sưu tập huy hiệu",
  "61 場頭銜賽的勝利紀錄": "61 chiến thắng trong cuộc đua danh hiệu",
  "收藏": "Bộ sưu tập",
  "尚未取得徽章。贏得頭銜賽後，徽章會記錄在這裡。": "Vẫn chưa giành được huy hiệu. Sau khi thắng một trận tranh đai, huy hiệu sẽ được ghi vào đây.",
  "每一枚徽章，都是一場頭銜賽的勝利紀錄。": "Mỗi huy hiệu là một kỷ lục chiến thắng trong một trận tranh đai.",
  "61 枚頭銜賽徽章": "61 Huy Hiệu Vô Địch",
  "徽章詳情": "Chi tiết huy hiệu",
  "已取得": "thu được",
  "未取得": "Không thu được",
  "取得方式": "Làm thế nào để có được",
  "目前僅戰鬥文字支援日文；其餘介面使用繁體中文。": "Giao diện tiếng Việt đã được hỗ trợ đầy đủ.",
  "位元幣": "Bits",
  "關閉": "Đóng",
  "state|關閉": "Tắt",
  "贏得這場頭銜賽。": "Giành chiến thắng trong trận tranh đai này.",
  "取得條件尚待查證。": "Các điều kiện mua lại vẫn chưa được xác minh.",
  "賽事日期": "Ngày sự kiện",
  "尚待查證": "vẫn chưa được xác minh",
  "取得時間": "Nhận thời gian",
  "此存檔未記錄取得日期。": "Không có ngày mua lại được ghi lại trong kho lưu trữ này.",
  "關閉詳情": "Đóng chi tiết",
  "數碼獸冠軍賽 — 2026": "Giải vô địch đối tác - 2026",
  "{bits} 位元幣": "Tiền tệ bit {bits}",
  "持有 {bits} 位元幣": "Giữ tiền tệ bit {bits}",
  "返回牧場": "Trở lại trang trại",
  "開啟": "Mở",
  "state|開啟": "Bật",
  "取消": "Hủy bỏ",
  "確認": "Xác nhận",
  "是": "Có",
  "否": "Không",
  "完成": "Hoàn tất",
  "設定": "Cài đặt",
  "管理": "Quản lý",
  "對戰": "Chiến đấu",
  "獎金": "Tiền thưởng",
  "資料": "Dữ liệu",
  "menu|資料": "Tài liệu",
  "無": "Không có",
  "決定": "Quyết định",
  "？？？": "???",
  "繁體中文": "繁體中文",
  "頭銜賽": "Trận đấu danh hiệu",
  "chip|頭銜賽": "Danh hiệu",
  "開始新遊戲": "Bắt đầu mới",
  "繼續遊戲": "Tiếp tục",
  "要開始新遊戲嗎？": "Bắt đầu trò chơi mới?",
  "開啟信件": "Mở thư",
  "信件": "Thư",
  "目前存檔「{name}」會在完成開場命名後被新遊戲取代，而且無法復原。想接著玩請選「繼續遊戲」。": "Kho lưu trữ hiện tại \"{name}\" sẽ được thay thế bằng trò chơi mới sau khi quá trình đặt tên mở hoàn tất và không thể khôi phục. Nếu bạn muốn tiếp tục chơi, vui lòng chọn \"Tiếp tục trò chơi\".",
  "目前的存檔會在完成開場命名後被新遊戲取代，而且無法復原。想接著玩請選「繼續遊戲」。": "Bản lưu hiện tại sẽ được thay thế bằng trò chơi mới sau khi phần mở đầu được đặt tên và không thể khôi phục. Nếu bạn muốn tiếp tục chơi, vui lòng chọn \"Tiếp tục trò chơi\".",
  "無法開始新遊戲：{reason}": "Không thể bắt đầu trò chơi mới: {reason}",
  "無法讀取存檔：{reason}": "Không thể đọc kho lưu trữ: {reason}",
  "數位競技場": "đấu trường kỹ thuật số",
  "請輸入馴獸師姓名": "Vui lòng nhập tên huấn luyện viên",
  "保存失敗": "Lưu thất bại",
  "請替數碼蛋取名字": "Hãy đặt tên cho quả trứng",
  "請輸入一至五個字。": "Vui lòng nhập từ một đến năm ký tự.",
  "馴獸師姓名使用「{name}」嗎？": "Tên của người huấn luyện có nên là \"{name}\" không?",
  "從現在起，你也是數碼獸馴獸師了。\n與夥伴一起，朝冠軍賽優勝邁進吧！\n贈禮應該就快送到了。": "Từ giờ trở đi, bạn cũng là một người đồng hành thuần hóa.\nLàm việc với bạn bè của bạn để giành chức vô địch!\nMón quà sẽ được giao sớm.",
  "這顆數碼蛋送給你。\n請替牠取個名字。": "Trứng nuôi cấy này được trao cho bạn.\nXin vui lòng đặt cho nó một cái tên.",
  "歡迎來到數位世界。\n首先，請輸入姓名，完成馴獸師登錄。": "Chào mừng đến với thế giới.\nĐầu tiên, vui lòng nhập tên của bạn để hoàn tất đăng nhập huấn luyện viên.",
  "每四年舉辦一次的\n數碼獸冠軍賽。": "Được tổ chức bốn năm một lần\nGiải vô địch đối tác.",
  "取得參賽資格，\n正是身為真正數碼獸馴獸師的證明。": "Đạt được trình độ chuyên môn để tham gia,\nChỉ là bằng chứng về việc là một huấn luyện viên đồng hành thực sự.",
  "而今天，你也迎來了\n參加數碼獸冠軍賽的機會。\n\n奪下勝利吧！\n數碼獸冠軍賽！": "Và hôm nay, các bạn cũng được chào đón\nCơ hội cạnh tranh trong Giải vô địch đối tác.\n\nHãy chiến thắng!\nGiải vô địch đối tác!",
  "好像已經收到郵件了。": "Có vẻ như email đã được nhận.",
  "開場故事，閱讀後點按繼續": "Mở đầu câu chuyện, bấm vào để tiếp tục sau khi đọc",
  "保存中": "Đang lưu",
  "已存到本機": "Đã lưu vào máy này",
  "保存失敗，點一下查看": "Không lưu được, bấm vào để xem",
  "遊戲狀態": "Trạng thái trò chơi",
  "第 {n} 日": "Ngày {n}",
  "目前沒有進行中的遊戲。": "Hiện không có ván chơi nào đang diễn ra.",
  "今日有 {count} 場頭銜賽，開啟對戰選單": "Hôm nay có {count} trận tranh đai, mở menu chiến đấu",
  "上次保存失敗；可在畫面上方的保存狀態重試。": "Lần lưu cuối cùng không thành công; bạn có thể thử lại ở trạng thái lưu ở đầu màn hình.",
  "已存到本機（{time}）。": "Nó đã được lưu vào máy này ({time}).",
  "已存到本機。": "Đã lưu vào máy này.",
  "上次寫入後遊戲又有進展，重要操作或離開頁面時會保存。": "Trò chơi đã tiến triển kể từ lần viết cuối cùng và các thao tác quan trọng hoặc khi rời khỏi trang sẽ được lưu lại.",
  "存檔只保存在這台裝置的這個瀏覽器。目前沒有帳號或雲端同步，換裝置或清除網站資料後無法取回。": "Lưu trữ chỉ được lưu trong trình duyệt này trên thiết bị này. Hiện tại không có đồng bộ hóa tài khoản hoặc đám mây và không thể truy xuất nó sau khi thay đổi thiết bị hoặc xóa dữ liệu trang web.",
  "購買、改名、確認設施配置、報名與對戰結算後會自動保存；離開頁面、換日與「保存並結束」也會保存。": "Các giao dịch mua, thay đổi tên, xác nhận cấu hình cơ sở, đăng ký và giải quyết trận chiến sẽ được lưu tự động; rời khỏi trang, thay đổi ngày và \"Lưu và kết thúc\" cũng sẽ được lưu.",
  "另一個分頁已寫入較新的存檔，這個分頁不會覆蓋它。請關閉其他分頁後重新開啟遊戲。": "Một tab khác đã được ghi vào kho lưu trữ mới hơn, tab này sẽ không ghi đè lên nó. Vui lòng đóng các tab khác và mở lại trò chơi.",
  "這次沒有寫入本機存檔。可以再試一次；若仍失敗，請確認瀏覽器沒有封鎖網站資料或處於私密瀏覽。": "Lần này không có kho lưu trữ địa phương nào được viết. Bạn có thể thử lại; nếu vẫn không thành công, vui lòng đảm bảo rằng trình duyệt không chặn dữ liệu trang web hoặc đang duyệt ở chế độ riêng tư.",
  "再試一次": "thử lại",
  "有變更正在等待寫入。": "Có những thay đổi đang chờ được viết.",
  "上次寫入後遊戲又有進展（上次：{time}）。": "Trò chơi đã tiến triển kể từ lần ghi cuối cùng (lần trước: {time}).",
  "上次寫入後遊戲又有進展。": "Trò chơi đã tiến triển kể từ lần viết cuối cùng.",
  "存檔狀態": "trạng thái lưu trữ",
  "知道了": "Hiểu rồi",
  "階級、戰績與收納容量": "Xếp hạng, hiệu suất và dung lượng lưu trữ",
  "全年頭銜賽與登錄": "Cạnh tranh danh hiệu quanh năm và đăng nhập",
  "調整牧場設施位置": "Điều chỉnh vị trí các cơ sở đồng cỏ",
  "夥伴名單與能力值": "Danh sách đối tác và giá trị khả năng",
  "結束今天，進入隔天": "Kết thúc hôm nay và vào ngày hôm sau",
  "操作與規則說明": "Mô tả hoạt động và quy tắc",
  "儲存進度並回到標題": "Lưu tiến trình và quay lại tiêu đề",
  "已登錄的數碼獸": "Đã đăng nhập đối tác",
  "前往傳送門捕捉數碼獸": "Đi đến cổng để bắt đồng đội của bạn",
  "參加比賽贏得獎金": "Tham gia các cuộc thi và giành giải thưởng",
  "購買食物、道具與設施": "Mua thực phẩm, đạo cụ và cơ sở vật chất",
  "主題、畫質、聲音與語言": "Chủ đề, đồ họa, âm thanh và ngôn ngữ",
  "春季": "Mùa xuân",
  "夏季": "Mùa hè",
  "秋季": "Mùa thu",
  "冬季": "Mùa đông",
  "夥伴與牧場": "Đối tác và trang trại",
  "紀錄": "ghi lại",
  "出發": "khởi hành",
  "另一個分頁已更新存檔。請先匯出這裡的進度，再重新載入並選擇繼續遊戲。": "Một tab khác đã cập nhật kho lưu trữ. Vui lòng xuất tiến trình của bạn tại đây trước, sau đó tải lại và chọn tiếp tục trò chơi.",
  "點選數碼獸查看狀態・左右滑動查看牧場": "Nhấp vào đối tác để xem trạng thái・Vuốt sang trái hoặc phải để xem trang trại",
  "選取的數碼獸": "Đối tác được chọn",
  "詳細": "Chi tiết",
  "上一隻數碼獸": "Đối tác trước đây",
  "下一隻數碼獸": "đối tác tiếp theo",
  "取消選取": "Bỏ chọn",
  "匯出未存成功的進度": "Tiến trình xuất chưa được lưu thành công",
  "收合詳細資料": "Thu gọn chi tiết",
  "收合": "đóng",
  "夥伴名單": "Danh sách đối tác",
  "確認新日期，返回育成": "Xác nhận ngày mới và quay lại Ủ",
  "結束今天": "kết thúc ngày hôm nay",
  "要結束今天嗎？": "Bạn muốn gọi nó là một ngày?",
  "病毒": "virus",
  "疫苗": "vắc xin",
  "龍": "Rồng",
  "獸": "con thú",
  "水": "nước",
  "鳥": "chim",
  "機械": "máy móc",
  "聖": "thánh thiện",
  "昆蟲植物": "cây côn trùng",
  "暗": "tối",
  "耐熱": "chịu nhiệt",
  "耐寒": "Chống lạnh",
  "耐雷": "Chống được sấm sét",
  "耐暗": "Chống tối",
  "耐光": "Nhẹ nhàng",
  "飽足": "no nê",
  "壓力": "áp lực",
  "親密": "sự thân mật",
  "友情": "tình bạn",
  "疲勞": "mệt mỏi",
  "這隻數碼獸的詳細資料暫時無法顯示。": "Thông tin chi tiết về người bạn đồng hành này hiện không thể được hiển thị.",
  "{name}，查看詳細資料": "{name}, xem chi tiết",
  "新的通知已送達。": "Một thông báo mới đã được gửi.",
  "{season}　{day} 日": "{season} {day} ngày",
  "{name} 進化成了{species}。": "{name} đã phát triển thành {species}.",
  "{name} 回到了數碼蛋。": "{name} trở lại trứng sinh sản.",
  "數碼獸消失了。": "Đối tác biến mất.",
  "進化!!": "Tiến hóa!!",
  "熱": "nóng bức",
  "寒": "lạnh",
  "雷": "sấm sét",
  "光": "ánh sáng",
  "闇": "tối",
  "暱稱": "Biệt hiệu",
  "容量": "Công suất",
  "攻擊": "tấn công",
  "防禦": "phòng thủ",
  "智力": "Tình báo",
  "速度": "tốc độ",
  "勝率": "Tỷ lệ thắng",
  "特殊技能Ⅰ": "Kỹ năng đặc biệt Ⅰ",
  "特殊技能Ⅱ": "Kỹ năng đặc biệt Ⅱ",
  "戰鬥次數": "Số trận chiến",
  "退化次數": "Thời gian thoái hóa",
  "性格": "nhân vật",
  "抗性": "Kháng cự",
  "移除與報名尚未開放。": "Việc xóa và đăng ký vẫn chưa được mở.",
  "新的暱稱": "biệt danh mới",
  "儲存名稱": "Lưu tên",
  "初始夥伴的名字在開場時決定，無法更改。": "Tên của đối tác ban đầu được xác định khi bắt đầu trò chơi và không thể thay đổi.",
  "名稱需為 1 至 {max} 個字。": "Tên cần phải có từ 1 đến {max} ký tự.",
  "這隻數碼獸的名字無法更改。": "Tên của người bạn đồng hành này không thể thay đổi.",
  "系統": "hệ thống",
  "說明": "Mô tả",
  "未確認欄位": "Ô chưa xác nhận",
  "持有金額": "Số tiền hiện có",
  "點選主題閱讀說明。分類與主題依原作順序排列。": "Click vào chủ đề để đọc hướng dẫn. Các danh mục và chủ đề được sắp xếp theo thứ tự của tác phẩm gốc.",
  "說明內容": "Nội dung mô tả",
  "依原作順序列出 {topics} 個說明主題與 {headings} 個分類標題。分類與主題的從屬關係尚待確認。": "Liệt kê các chủ đề mô tả {topics} và tiêu đề danh mục {headings} theo thứ tự của tác phẩm gốc. Sự phụ thuộc của các danh mục vào chủ đề vẫn chưa được xác nhận.",
  "共 {total} 個欄位，其中 {unsourced} 個欄位的資料來源尚待確認，以橫線表示，並非零。": "Tổng cộng có các trường {total}, trong đó nguồn dữ liệu của các trường {unsourced} vẫn chưa được xác nhận, được biểu thị bằng các đường ngang và không phải bằng 0.",
  "點選賽事查看報名費、獎金與參賽階級。今天可參加的賽事會標示出來。": "Nhấp vào sự kiện để xem phí đăng ký, tiền thưởng và cấp độ tham gia. Các sự kiện có sẵn ngày hôm nay sẽ được đánh dấu.",
  "賽事詳細": "Chi tiết sự kiện",
  "{rank} 以上": "{rank} trở lên",
  "不限": "Không giới hạn",
  "參賽階級": "Mức độ tham gia",
  "持有金額不足以支付報名費。": "Số tiền nắm giữ không đủ để trả phí đăng ký.",
  "馴獸師階級達到 {rank} 後才能登錄這場比賽。": "Cần đạt cấp bậc huấn luyện viên {rank} để đăng ký giải đấu này.",
  "已獲勝": "Đã thắng",
  "取消登錄": "Hủy đăng ký",
  "登錄比賽": "Đăng ký thi đấu",
  "四季共 {count} 場預定賽事。": "Có tất cả {count} sự kiện thi đấu được lên lịch trong cả bốn mùa.",
  "取消登錄世界冠軍賽": "Hủy đăng ký Giải vô địch thế giới",
  "取消登錄冠軍賽": "Hủy đăng ký giải vô địch",
  "登錄世界冠軍賽": "Đăng ký Giải vô địch thế giới",
  "登錄冠軍賽": "Đăng ký giải vô địch",
  "{event} 預賽第 {round} 戰 / 共 {total} 戰": "{event} Vòng sơ loại Trận chiến {round} / Trận chiến tổng {total}",
  "世界大會": "Đại hội thế giới",
  "冠軍大會": "Hội nghị vô địch",
  "贏得冠軍大會後開放。": "Mở sau khi giành chiến thắng trong Hội nghị vô địch.",
  "馴獸師階級到達後開放。": "Lớp Tamer sẽ được mở khi đến nơi.",
  "尚未報名。請在賽程登記後再來。": "Chưa đăng ký. Vui lòng quay lại sau khi đăng ký lịch trình.",
  "多輪賽事": "Nhiều vòng",
  "返回對戰選單": "Quay lại menu chiến đấu",
  "{count} 輪": "bánh xe {count}",
  "無法開始這場賽事。": "Sự kiện này không thể được bắt đầu.",
  "賽事結束": "Kết thúc sự kiện",
  "勝": "thắng",
  "敗": "đánh bại",
  "選擇本輪參賽數碼獸；確認後抽出對手。": "Chọn đối tác tham gia của bạn cho vòng này; vẽ đối thủ của bạn sau khi xác nhận.",
  "開始第 {round} 戰": "Bắt đầu trận chiến {round}",
  "選擇參賽數碼獸": "Chọn đối tác tham gia",
  "最多 {limit} 隻": "Nhiều nhất chỉ {limit}",
  "目前沒有可以參賽的數碼獸。": "Hiện tại không có đối tác nào có thể tham gia.",
  "隊伍資料讀取失敗，請返回後再試。": "Không đọc được thông tin đội, vui lòng quay lại và thử lại.",
  "目前無法開始這一輪。": "Vòng này không thể bắt đầu vào lúc này.",
  "領取 {bits} 位元幣": "Nhận xu bit {bits}",
  "結束賽事": "kết thúc sự kiện",
  "獲得 {bits} 位元幣。": "Nhận được đồng xu bit {bits}.",
  "本次沒有獎金。": "Lần này không có tiền thưởng.",
  "無法結算這場賽事。": "Trận đấu này không thể giải quyết được.",
  "隊伍或遊戲進度已更新，請重新選擇。": "Đội hoặc tiến trình trận đấu đã được cập nhật, vui lòng chọn lại.",
  "另一個分頁正在遊玩。請先關閉該分頁，再開始遊戲。": "Một tab khác đang phát. Vui lòng đóng tab này trước khi bắt đầu trò chơi.",
  "另一個分頁正在遊玩。請先關閉該分頁，再繼續遊戲。": "Một tab khác đang phát. Vui lòng đóng tab này trước khi tiếp tục trò chơi.",
  "這場對戰最多 {count} 隻。": "Trận đấu này chỉ có nhiều {count} nhất.",
  "同一隻數碼獸只能加入一隊。": "Người bạn đồng hành giống nhau chỉ có thể tham gia một đội.",
  "無法建立通訊邀請碼，請重新選擇隊伍。": "Không thể tạo mã mời giao tiếp, vui lòng chọn lại nhóm.",
  "通訊碼內含不能參戰的數碼獸。": "Mã liên lạc chứa các đối tác không thể tham gia trận chiến.",
  "通訊碼無法辨識、已損壞，或不是同一場邀請。": "Mã liên lạc không thể nhận dạng được, bị hỏng hoặc không giống với lời mời.",
  "通訊對戰準備失敗，請重新交換通訊碼。": "Chuẩn bị trận chiến liên lạc không thành công, vui lòng trao đổi lại mã liên lạc.",
  "請選擇 1 至 3 隻數碼獸。": "Hãy chọn từ 1 đến 3 người bạn đồng hành.",
  "請輸入 A 隊與 B 隊的密碼。": "Vui lòng nhập mật khẩu của Đội A và Đội B.",
  "密碼無法辨識或校驗不正確，請確認後再輸入。": "Mật khẩu không thể được nhận dạng hoặc xác minh không chính xác. Vui lòng xác nhận trước khi nhập lại.",
  "密碼隊伍準備失敗，請重新輸入。": "Nhóm mật khẩu không chuẩn bị được, vui lòng nhập lại.",
  "隊伍或遊戲進度已更新，請重新選擇參賽隊伍。": "Đội hoặc tiến trình trận đấu đã được cập nhật, vui lòng chọn đội mới.",
  "請選擇 1 至 {limit} 隻符合條件的數碼獸。": "Vui lòng chọn 1 đến {limit} chỉ các đối tác đủ điều kiện.",
  "選擇的數碼獸已不在目前名冊。": "Đối tác được chọn không còn trong danh sách hiện tại.",
  "這場比賽不符合目前日期或資格，請重新選擇。": "Trận đấu này không khớp với ngày thi đấu hoặc trình độ hiện tại, vui lòng chọn lại.",
  "遊戲進度已更新，請重新選擇參賽隊伍。": "Diễn biến trận đấu đã được cập nhật, vui lòng chọn lại đội tham gia.",
  "遊戲場景尚未就緒，請返回牧場後重試。": "Cảnh trò chơi vẫn chưa sẵn sàng, vui lòng quay lại trang trại và thử lại.",
  "目前日期或參賽資格已改變，請重新選擇賽事。": "Ngày hiện tại hoặc tính đủ điều kiện đã thay đổi, vui lòng chọn một sự kiện khác.",
  "這隻數碼獸的個體資料尚未完整。": "Dữ liệu cá nhân về người bạn đồng hành này vẫn chưa đầy đủ.",
  "這隻數碼獸還太幼小，暫時無法參賽。": "Người bạn đồng hành này vẫn còn quá trẻ và chưa thể cạnh tranh trong thời điểm hiện tại.",
  "這隻數碼獸目前的身體狀況無法參賽。": "Tình trạng thể chất hiện tại của người bạn đồng hành này khiến anh ta không thể thi đấu.",
  "這隻數碼獸不符合本場比賽的參賽條件。": "Người bạn đồng hành này không đủ điều kiện tham gia cuộc thi này.",
  "密碼中沒有可參戰的數碼獸。": "Không có đối tác có sẵn trong mật khẩu.",
  "密碼中含有目前不能參戰的數碼獸。": "Mật khẩu chứa các đối tác hiện không thể tham gia trận chiến.",
  "這隻數碼獸還不能密碼化。": "Người bạn đồng hành này chưa thể được mã hóa.",
  "單隻對戰": "Chiến đấu một mình",
  "三隻對戰": "Ba vs.",
  "頭銜 {id}": "Tiêu đề {id}",
  "通訊對戰": "Trận chiến truyền thông",
  "密碼對戰": "cuộc chiến mật khẩu",
  "練習對戰": "luyện tập chiến đấu",
  "自由對戰": "trận chiến miễn phí",
  "{event} 第 {round} 戰": "Trận chiến {event} {round}",
  "返回賽事": "Quay lại sự kiện",
  "戰鬥選單立方體，拖曳或使用左右方向鍵旋轉": "Khối menu chiến đấu, kéo hoặc xoay bằng phím mũi tên trái và phải",
  "對戰模式": "Chế độ so với",
  "此模式尚未開放": "Chế độ này chưa mở",
  "對戰清單載入失敗，請重新選擇模式。": "Danh sách trận chiến không tải được, vui lòng chọn lại chế độ.",
  "對戰場地": "Chiến trường",
  "隨機場地": "địa điểm ngẫu nhiên",
  "持有金額不足。報名費 {fee} 位元幣；持有 {wallet} 位元幣。": "Số tiền nắm giữ không đủ. Phí đăng ký đồng xu bit {fee}; nắm giữ đồng xu bit {wallet}.",
  "持有金額不足。 報名費 {fee} 位元幣；持有 {wallet} 位元幣。": "Số tiền nắm giữ không đủ. Phí đăng ký đồng xu bit {fee}; nắm giữ đồng xu bit {wallet}.",
  "目前無法參加這場對戰。": "Hiện tại không thể tham gia trận đấu này.",
  "參賽隊伍載入失敗，請再試一次。": "Các đội tham gia không tải được, vui lòng thử lại.",
  "HP {hp}／{maxHp}　TP {tp}／{maxTp}": "HP {hp}／{maxHp} TP {tp}／{maxTp}",
  "目前沒有符合這場比賽條件的數碼獸。": "Hiện tại không có bạn đồng hành nào đủ điều kiện cho trận đấu này.",
  "對戰準備失敗，請再試一次。": "Việc chuẩn bị chiến đấu không thành công, vui lòng thử lại.",
  "返回賽事選擇": "Quay lại lựa chọn sự kiện",
  "將自己培育的數碼獸分成兩隊，每隊最多 3 隻。": "Chia những người bạn đồng hành mà bạn đã nhân giống thành hai đội, mỗi đội có tối đa 3 con.",
  "開始練習": "Bắt đầu luyện tập",
  "A 隊 {a}／3　B 隊 {b}／3": "Đội A {a}／3 Đội B {b}／3",
  "{team} 隊": "Đội ngũ {team}",
  "{name} {team} 隊": "Đội ngũ {name} {team}",
  "練習對戰需要至少兩隻可以參賽的數碼獸。": "Các trận chiến luyện tập cần có ít nhất hai đối tác có thể tham gia.",
  "密碼對戰載入失敗，請再試一次。": "Trận chiến mật khẩu không tải được, vui lòng thử lại.",
  "輸入兩組隊伍密碼。每組密碼可還原最多 3 隻數碼獸。": "Nhập hai bộ mật khẩu nhóm. Mỗi bộ mật khẩu có thể khôi phục tối đa 3 đối tác.",
  "{team} 隊密碼": "Mật khẩu đội {team}",
  "開始密碼對戰": "Bắt đầu cuộc chiến mật khẩu",
  "密碼對戰準備失敗，請再試一次。": "Việc chuẩn bị mật khẩu không thành công, vui lòng thử lại.",
  "我的隊伍密碼": "Mật khẩu đội của tôi",
  "選擇最多 3 隻自己的數碼獸，產生可以分享給朋友的密碼。密碼保存的是現在的狀態。": "Chọn tối đa 3 đối tác của riêng bạn và tạo mật khẩu có thể chia sẻ với bạn bè. Mật khẩu được lưu ở trạng thái hiện tại.",
  "產生密碼": "tạo mật khẩu",
  "複製密碼": "Sao chép mật khẩu",
  "目前沒有可以密碼化的數碼獸。": "Hiện tại không có đối tác mật mã nào có sẵn.",
  "密碼產生失敗，請再試一次。": "Tạo mật khẩu không thành công, vui lòng thử lại.",
  "已複製密碼。": "Đã sao chép mật khẩu.",
  "請長按密碼欄位手動複製。": "Vui lòng nhấn và giữ trường mật khẩu để sao chép thủ công.",
  "通訊對戰載入失敗，請再試一次。": "Trận chiến giao tiếp không tải được, vui lòng thử lại.",
  "兩台裝置交換邀請碼與回覆碼，完成後雙方會看到同一場對戰。": "Hai thiết bị trao đổi mã mời và mã trả lời. Sau khi hoàn thành, cả hai bên sẽ thấy trận chiến giống nhau.",
  "建立邀請": "Tạo lời mời",
  "加入邀請": "Lời mời tham gia",
  "選擇參賽數碼獸（1 至 3 隻）": "Chọn đối tác tham gia (1 đến 3)",
  "通訊對戰準備失敗，請再交換一次通訊碼。": "Chuẩn bị trận chiến liên lạc không thành công, vui lòng trao đổi lại mã liên lạc.",
  "邀請碼": "Mã mời",
  "對方回覆碼": "Mã trả lời của bên kia",
  "產生邀請碼": "Tạo mã mời",
  "讀取回覆並開始": "Đọc câu trả lời và bắt đầu",
  "對方邀請碼": "Mã mời của bên kia",
  "回覆碼": "mã trả lời",
  "產生回覆碼": "Tạo mã trả lời",
  "已分享回覆碼，開始對戰": "Mã trả lời đã được chia sẻ, bắt đầu trận chiến",
  "報名費 {bits} 位元幣": "Phí tham gia {bits} Bits",
  "獎金 {bits} 位元幣": "Tiền thưởng {bits} Bits",
  "獎金 {none}": "Tiền thưởng {none}",
  "進行中": "Đang tiến hành",
  "時間到": "hết giờ rồi",
  "一方全員倒下": "Mọi người ở một bên ngã xuống",
  "尚未分出勝負": "Chưa phân thắng bại",
  "我方獲勝": "Chiến thắng",
  "對手獲勝": "Thất bại",
  "雙方平手": "Hòa",
  "生命值 {hp} / {max}": "Sức khỏe {hp} / {max}",
  "正在準備對戰場地…": "Chuẩn bị chiến trường...",
  "對戰進行中": "Trận chiến đang diễn ra",
  "離開對戰": "Rời khỏi trận đấu",
  "要離開這場對戰嗎？": "Bạn có muốn rời khỏi trận đấu này không?",
  "離開後對戰會中止並記為放棄，不會獲得獎金；已支付的報名費不會退回。": "Sau khi rời đi, trận đấu sẽ bị tạm dừng và được ghi là bị hủy và không nhận được tiền thưởng; phí đăng ký đã nộp sẽ không được hoàn lại.",
  "繼續觀戰": "Tiếp tục theo dõi trận đấu",
  "對戰場地載入失敗，請返回牧場後再試。": "Đấu trường không tải được, vui lòng quay lại trang trại và thử lại.",
  "雙方都未取得領先。": "Không bên nào dẫn đầu.",
  "獎金 +": "Tiền thưởng +",
  "持有金額已達上限": "Số tiền nắm giữ đã đạt đến giới hạn trên",
  "獎金尚未入帳。": "Tiền thắng cược vẫn chưa được ghi có.",
  "獎金 {bits} 位元幣；持有金額已達上限。": "Tiền thưởng bit {bits}; số tiền nắm giữ đã đạt đến giới hạn trên.",
  "本場沒有獲得獎金。": "Không có giải thưởng nào được trao cho trò chơi này.",
  "馴獸師升階": "Nâng cấp người thuần hóa quái thú",
  "階級 {before} → {after}": "Lớp {before} → {after}",
  "取得頭銜": "có được một danh hiệu",
  "戰績": "ghi lại",
  "對戰場次": "Số trận chiến",
  "頭銜數": "Số lượng danh hiệu",
  "新解鎖": "Mới được mở khóa",
  "下一頁": "Trang tiếp theo",
  "參賽數碼獸": "Đối tác tham gia",
  "輕觸畫面略過": "Chạm vào màn hình để bỏ qua",
  "馴獸師階級達到 {rank} 後開放。": "Cấp độ thuần hóa thú sẽ được mở sau khi đạt {rank}.",
  "取得對應比賽勝利後開放。": "Nó sẽ được mở sau khi giành chiến thắng trong cuộc thi tương ứng.",
  "持有金額不足，入場需要 {bits} 位元幣。": "Nếu số lượng nắm giữ không đủ, cần phải có đồng bit {bits} để tham gia.",
  "選擇狩獵場": "Chọn nơi săn bắn",
  "轉動地球，選擇要前往的場地。": "Xoay quả địa cầu và chọn nơi bạn muốn đến.",
  "場地列表": "Danh sách địa điểm",
  "拖曳轉動 · 輕觸地點選擇": "Kéo để xoay · Nhấn để chọn vị trí",
  "狩獵場資訊": "Thông tin địa điểm săn bắn",
  "請選擇目的地": "Vui lòng chọn điểm đến",
  "入場費": "Phí nhập học",
  "選擇目的地": "Chọn điểm đến",
  "前往狩獵設定": "Đi tới cài đặt săn bắn",
  "返回地球": "trở lại trái đất",
  "{gate}・日間場地預覽": "{gate}・Xem trước địa điểm trong ngày",
  "狩獵設定": "cài đặt săn bắn",
  "選擇攜帶的工具與外掛。": "Chọn các công cụ và plug-in bạn mang theo.",
  "目的地": "điểm đến",
  "返回選場": "Quay lại lựa chọn",
  "開始狩獵": "bắt đầu săn bắn",
  "繩索": "dây thừng",
  "射擊": "bắn",
  "鋼索": "dây thép",
  "誘引道具": "đạo cụ thu hút",
  "傷害陷阱": "bẫy thiệt hại",
  "尚未持有": "Chưa được tổ chức",
  "外掛 {n}": "Trình cắm {n}",
  "入場費 {fee} 位元幣 · 持有 {wallet} 位元幣": "Phí vào cửa {fee} bitcoin · Giữ {wallet} bitcoin",
  "此存檔缺少狩獵歷史，暫時無法進入狩獵。": "Kho lưu trữ này thiếu lịch sử săn bắn và tạm thời không có sẵn để săn bắn.",
  "狩獵進場未完成，遊戲狀態已保留。請重試。": "Mục săn bắn chưa hoàn thành và trạng thái trò chơi vẫn được giữ nguyên. Vui lòng thử lại.",
  "正在準備狩獵場…": "Chuẩn bị bãi săn…",
  "狩獵場下載進度": "Tiến trình tải xuống Hunting Ground",
  "狩獵目標資訊": "Thông tin mục tiêu săn lùng",
  "輕觸數碼獸查看": "Nhấn vào đối tác để xem",
  "世代": "thế hệ",
  "種族": "cuộc đua",
  "屬性": "Thuộc tính",
  "記憶卡容量": "Dung lượng thẻ nhớ",
  "狩獵雷達": "radar săn bắn",
  "狩獵工具": "công cụ săn bắn",
  "拖曳地面移動視野 · 輕觸數碼獸選取": "Kéo mặt đất để di chuyển trường nhìn · Nhấn để chọn đối tác",
  "正在返回牧場…": "Trở lại trang trại…",
  "正在下載狩獵場 {percent}%": "Đang tải xuống Hunting Ground {percent}%",
  "已下載 {size}": "Đã tải xuống {size}",
  "正在下載狩獵場…": "Đang tải xuống Hunting Ground…",
  "網路較慢，仍在下載中；也可以先返回牧場。": "Mạng chậm và vẫn đang tải xuống; bạn cũng có thể quay lại trang trại trước.",
  "狩獵場下載沒有回應，請返回牧場後再試一次。": "Không có phản hồi từ việc tải xuống trang trại săn bắn. Vui lòng quay lại trang trại và thử lại.",
  "狩獵場載入時間過長，請返回牧場後再試一次。": "Thời gian tải bãi săn quá lâu, vui lòng quay lại trang trại và thử lại.",
  "剩餘 {time}": "{time} còn lại",
  "野生數碼獸": "bạn đồng hành hoang dã",
  "記憶卡容量不足": "Dung lượng thẻ nhớ không đủ",
  "繩索斷了": "Dây bị đứt",
  "已收入記憶卡": "Đã được lưu trong thẻ nhớ",
  "道具已用完": "Đạo cụ đã được sử dụng hết",
  "無法放在這個位置": "Không thể đặt ở vị trí này",
  "場上的肉餌已滿": "Cánh đồng đầy mồi thịt",
  "場上的道具已滿": "Đạo cụ trên sân đầy đủ",
  "快速畫圈綑綁 · 按住目標拉動繩索 · 放鬆可恢復耐久": "Nhanh chóng vẽ một vòng tròn để trói · Nhấn và giữ mục tiêu để kéo dây · Thư giãn để phục hồi độ bền",
  "按住目標射擊": "Giữ mục tiêu để bắn",
  "拖曳拉出鋼索 · 放手完成": "Kéo để rút cáp · Buông và hoàn thành",
  "輕觸地面放置肉餌": "Đặt nhẹ mồi thịt xuống đất",
  "輕觸放置玩具 · 再輕觸指定移動方向": "Chạm để đặt đồ chơi · Chạm lại để xác định hướng di chuyển",
  "輕觸放置誘引燈 · 夜間吸引目標": "Nhấn để đặt đèn mồi · Thu hút mục tiêu vào ban đêm",
  "輕觸放置陷阱 · 困住目標後切換手掌收取": "Nhấn để đặt bẫy · Sau khi bẫy mục tiêu, hãy chuyển lòng bàn tay của bạn để thu thập nó",
  "輕觸放置炸彈": "Nhấn để đặt bom",
  "輕觸放置地雷 · 目標經過時引爆": "Nhấn để đặt mìn · Phát nổ khi mục tiêu đi ngang qua",
  "拖曳地面移動視野 · 目標倒地後輕觸抓取": "Kéo mặt đất để di chuyển trường nhìn · Nhấn để tóm lấy mục tiêu sau khi nó rơi xuống đất",
  "手": "tay",
  "基礎捕捉繩 α": "Dây bắt cơ bản α",
  "基礎捕捉繩 β": "Dây bắt cơ bản β",
  "基礎捕捉繩 γ": "Dây Chụp Cơ Bản |",
  "強化捕捉繩 α": "Dây chụp gia cố α",
  "強化捕捉繩 β": "Dây chụp gia cố β",
  "強化捕捉繩 γ": "Dây Chụp Gia Cố |",
  "高階捕捉繩 α": "Dây chụp tiên tiến α",
  "高階捕捉繩 β": "Dây bắt nâng cao β",
  "高階捕捉繩 γ": "Dây chụp nâng cao γ",
  "頂級捕捉繩 α": "Dây bắt đỉnh α",
  "頂級捕捉繩 β": "Dây bắt hàng đầu β",
  "頂級捕捉繩 γ": "Dây Bắt Hàng Đầu |",
  "普通射擊 α": "Chụp bình thường α",
  "普通射擊 β": "Beta bắn súng thông thường",
  "連發射擊 α": "nổ lửa α",
  "連發射擊 β": "Bùng cháy β",
  "睡眠射擊 α": "ảnh chụp giấc ngủ alpha",
  "睡眠射擊 β": "bản beta thuốc ngủ",
  "麻痺射擊 α": "Cú bắn làm tê liệt α",
  "麻痺射擊 β": "Cú bắn gây tê liệt β",
  "散彈 α": "Súng săn α",
  "散彈 β": "phiên bản beta súng ngắn",
  "麻痺散彈 α": "Cú đánh tê liệt α",
  "麻痺散彈 β": "Cú đánh tê liệt β",
  "阻擋鋼索 α": "Chặn dây α",
  "阻擋鋼索 β": "Chặn cáp β",
  "磁力鋼索 α": "Cáp thép từ tính α",
  "磁力鋼索 β": "Cáp thép từ tính β",
  "電擊鋼索 α": "Cáp sốc α",
  "電擊鋼索 β": "Cáp điện giật β",
  "肉餌": "mồi thịt",
  "大型肉餌": "Mồi thịt lớn",
  "毒肉餌": "mồi thịt độc",
  "麻痺肉餌": "Mồi thịt làm tê liệt",
  "誘導玩具": "đồ chơi kích thích",
  "強化誘導玩具": "Đồ chơi tăng cường cảm ứng",
  "黃色誘引燈": "Đèn thu hút màu vàng",
  "藍色誘引燈": "ánh sáng thu hút màu xanh",
  "爆破彈": "Bom nổ",
  "睡眠彈": "quả bom ngủ",
  "麻痺彈": "viên đạn tê liệt",
  "閃光彈": "flashbang",
  "地雷": "mỏ",
  "大型地雷": "mỏ lớn",
  "捕捉陷阱": "bắt bẫy",
  "強化捕捉陷阱": "Tăng cường bẫy bắt",
  "世代分析": "phân tích thế hệ",
  "種族分析": "hồ sơ chủng tộc",
  "屬性分析": "Phân tích thuộc tính",
  "HP 分析": "phân tích HP",
  "性格分析": "phân tích tính cách",
  "容量分析": "phân tích năng lực",
  "世代／種族分析": "Phân tích thế hệ/dân tộc",
  "世代／種族／屬性分析": "Phân tích thế hệ/chủng tộc/thuộc tính",
  "完整分析": "phân tích đầy đủ",
  "射擊數量": "Số lần chụp",
  "鋼索數量": "Số lượng dây cáp",
  "誘引道具數量": "Số lượng đạo cụ thu hút",
  "傷害陷阱數量": "Số lượng bẫy sát thương",
  "全部道具數量": "Số lượng của tất cả các đạo cụ",
  "幼年期雷達": "radar sơ sinh",
  "成長期雷達": "radar tăng trưởng",
  "成熟期雷達": "radar trưởng thành",
  "完全體雷達": "radar cơ thể hoàn chỉnh",
  "資料／自由屬性雷達": "Radar dữ liệu/thuộc tính tự do",
  "疫苗屬性雷達": "Radar đặc tính vắc xin",
  "病毒屬性雷達": "Radar đặc tính virus",
  "龍族雷達": "Radar rồng",
  "獸族雷達": "Radar Orc",
  "鳥族雷達": "radar chim",
  "水族雷達": "radar hồ cá",
  "聖族雷達": "Ra-đa thần thánh",
  "暗黑族雷達": "Radar của bộ lạc bóng tối",
  "昆蟲植物雷達": "Radar thực vật côn trùng",
  "機械族雷達": "Radar cơ học",
  "記憶卡容量顯示": "Hiển thị dung lượng thẻ nhớ",
  "記憶卡 32G": "Thẻ nhớ 32G",
  "記憶卡 64G": "Thẻ nhớ 64G",
  "記憶卡 96G": "Thẻ nhớ 96G",
  "數碼蛋": "trứng nuôi",
  "幼年期 I": "Thời thơ ấu tôi",
  "幼年期 II": "Giai đoạn sơ sinh II",
  "幼年期Ⅰ": "Giai đoạn sơ sinh I",
  "幼年期Ⅱ": "Giai đoạn sơ sinh II",
  "成長期": "thời kỳ tăng trưởng",
  "成熟期": "giai đoạn trưởng thành",
  "完全體": "cơ thể hoàn hảo",
  "究極體": "cơ thể cuối cùng",
  "昆蟲／植物": "Côn trùng/Thực vật",
  "暗黑": "tối",
  "自由": "sự tự do",
  "坦率": "thẳng thắn",
  "任性": "cố ý",
  "急躁": "thiếu kiên nhẫn",
  "悠閒": "nhàn nhã",
  "熱血": "đam mê",
  "冷靜": "bình tĩnh",
  "大膽": "Đậm",
  "膽小": "rụt rè",
  "養成用品": "Vật dụng nuôi dưỡng",
  "外掛": "trình cắm thêm",
  "籠子設施": "cơ sở lồng",
  "購買完成。": "Mua hàng đã hoàn tất.",
  "持有金額不足。": "Số tiền nắm giữ không đủ.",
  "已達持有上限。": "Đã đạt đến giới hạn nắm giữ.",
  "此商品目前不販售。": "Sản phẩm này hiện không được bán.",
  "無法購買這個數量。": "Số lượng này không thể mua được.",
  "用品": "Vật tư",
  "工具": "Công cụ",
  "設施": "cơ sở vật chất",
  "商品說明無法顯示。": "Mô tả sản phẩm không thể được hiển thị.",
  "商店": "cửa hàng",
  "養成用品・狩獵裝備・牧場設施": "Vật tư chăn nuôi, thiết bị săn bắn, trang trại chăn nuôi",
  "商品分類": "Phân loại sản phẩm",
  "上一項商品": "Mục trước",
  "商品選擇": "Lựa chọn sản phẩm",
  "下一項商品": "mục tiếp theo",
  "購買": "mua",
  "商品": "hàng hóa",
  "已購買「{item}」，持有 {owned}/{max}。": "Đã mua \"{item}\" và giữ {owned}/{max}.",
  "這個分類目前沒有販售商品。": "Hiện tại không có sản phẩm nào được bán trong danh mục này.",
  "{bits} 位元幣 · 持有 {owned}/{max}": "{bits} Bit Coin · Giữ {owned}/{max}",
  "已持有": "Đã tổ chức",
  "已達上限": "Đã đạt đến giới hạn",
  "{item}已達持有上限": "{item} đã đạt đến giới hạn nắm giữ",
  "購買{item}": "Mua {item}",
  "已經持有，無法再購買。": "Đã được giữ và không thể mua được nữa.",
  "已達持有上限 {max}。": "Đã đạt đến giới hạn nắm giữ {max}.",
  "持有金額不足，還差 {bits} 位元幣。": "Số lượng nắm giữ không đủ và số dư là đồng xu bit {bits}.",
  "數碼獸圖鑑": "Sách minh họa của đối tác",
  "已登錄 {count} / {total}": "Đăng nhập {count} / {total}",
  "未登錄 {n}": "Chưa đăng nhập {n}",
  "已登錄": "Đã đăng nhập",
  "尚未登錄這隻數碼獸。": "Đối tác này chưa được đăng nhập.",
  "配置已套用。": "Cấu hình đã được áp dụng.",
  "設施配置": "Cấu hình cơ sở",
  "待機區固定。點選設施取回，再選擇空格放置。": "Khu vực chờ đã được cố định. Bấm vào cơ sở để lấy nó, sau đó chọn một khoảng trống để đặt nó.",
  "已放置設施": "Cơ sở vật chất được đặt",
  "牧場平面配置 · 左右滑動查看所有格位": "Sơ đồ mặt bằng trang trại · Vuốt sang trái và phải để xem tất cả không gian",
  "確認配置": "Xác nhận cấu hình",
  "配置還沒有套用": "Cấu hình chưa được áp dụng",
  "這次調整的設施位置尚未確認。要套用後返回牧場，還是放棄這些變更？": "Vị trí của cơ sở cho sự điều chỉnh này vẫn chưa được xác nhận. Bạn muốn đăng ký và quay lại đồng cỏ hay loại bỏ các thay đổi?",
  "繼續編輯": "Tiếp tục chỉnh sửa",
  "放棄變更": "Hủy thay đổi",
  "套用並返回": "Áp dụng và trả lại",
  "階級 {rank} · {used} / {total} 格": "Lớp {rank} · Lưới {used} / {total}",
  "第 {n} 格：{cage}。{effect}": "Ô {n}: {cage}. {effect}",
  "可放置": "Có thể được đặt",
  "尚未開放": "Chưa mở",
  "取回 {cage}": "Truy xuất {cage}",
  "已持有的設施皆已放置。": "Tất cả các cơ sở hiện có đã được đặt.",
  "選擇{cage}。{effect}": "Chọn {cage}. {effect}",
  "飼料": "thức ăn",
  "蛋白質": "chất đạm",
  "傷藥": "thuốc trị vết thương",
  "藥品": "Thuốc",
  "防禦上升": "Phòng thủ tăng lên",
  "生命值上升": "Tăng cường sức khỏe",
  "技力上升": "Tăng kỹ năng",
  "攻擊上升": "Tấn công tăng lên",
  "速度上升": "tăng tốc độ",
  "智力上升": "Trí tuệ tăng lên",
  "回復生命值與壓力": "Phục hồi sức khỏe và áp lực",
  "自動餵食與清潔": "Tự động cho ăn và làm sạch",
  "對戰次數上升": "Tăng số lượng trận chiến",
  "資料屬性上升": "Thuộc tính dữ liệu tăng",
  "龍屬性上升": "Thuộc tính rồng tăng",
  "獸屬性上升": "Thuộc tính quái vật tăng",
  "水棲屬性上升": "Thuộc tính thủy sinh tăng",
  "鳥屬性上升": "Thuộc tính chim tăng",
  "蟲草屬性上升": "Thuộc tính đông trùng hạ thảo tăng",
  "暗黑屬性上升": "Thuộc tính bóng tối tăng",
  "機械屬性上升": "Tăng tính chất cơ học",
  "疫苗屬性上升": "Tính chất của vắc xin tăng lên",
  "聖屬性上升": "Thuộc tính thánh tăng lên",
  "病毒屬性上升": "Đặc tính virus tăng lên",
  "光耐性上升": "Tăng khả năng chịu ánh sáng",
  "熱耐性上升": "Tăng khả năng chịu nhiệt",
  "冷耐性上升": "Tăng khả năng chịu lạnh",
  "雷耐性上升": "Tăng khả năng chống sét",
  "闇耐性上升": "Sức đề kháng tối tăng",
  "建議 {count} 隻": "Chỉ đề xuất {count}",
  "固定待機區": "Khu vực chờ cố định",
  "戴納草原": "thảo nguyên dyna",
  "驅動莽原": "lái xe nơi hoang dã",
  "模組之森": "Rừng mod",
  "啟動叢林": "Bắt đầu đi rừng",
  "黏滑沼澤": "đầm lầy nhầy nhụa",
  "波浪海岸": "Bờ biển gợn sóng",
  "南橋峽谷": "hẻm núi cầu nam",
  "頭銜完成度": "Tiến độ danh hiệu",
  "圖鑑完成度": "Tiến độ thư viện",
  "地圖完成度": "Tiến độ bản đồ",
  "對戰次數": "Số trận đấu",
  "名稱": "Tên",
  "克隆礦坑": "mỏ nhân bản",
  "杜比工廠": "Nhà máy Dolby",
  "下水道路": "đường cống",
  "雪之國度": "xứ tuyết",
  "裂岩地帶": "vùng đá nứt",
  "岩漿山脈": "núi magma",
  "灼熱沙漠": "sa mạc thiêu đốt",
  "澄澈綠洲": "Ốc đảo của sự rõ ràng",
  "臨界遺跡": "di tích quan trọng",
  "教學關卡": "Trình độ giảng dạy",
  "階級": "Cấp bậc",
  "遊玩時間": "Thời gian chơi",
  "育成執照": "Giấy phép nuôi",
  "收納容量": "Dung lượng chứa",
  "設施格數": "Số ô chuồng",
  "外觀與顯示": "Ngoại hình và hiển thị",
  "畫面品質": "Chất lượng hình ảnh",
  "聲音": "âm thanh",
  "語言": "ngôn ngữ",
  "操作與輔助": "Vận hành và hỗ trợ",
  "資料與帳號": "Thông tin và Tài khoản",
  "深色夜景": "khung cảnh đêm tối",
  "深色背景，適合夜間與長時間遊玩。": "Nền tối, thích hợp chơi ban đêm và chơi nhiều giờ.",
  "藍白清爽": "Màu xanh và trắng tươi mát",
  "明亮的藍白配色，適合白天與戶外。": "Phối màu xanh trắng sáng phù hợp sử dụng ban ngày và ngoài trời.",
  "經典暖黃": "Màu vàng ấm áp cổ điển",
  "米黃紙色與琥珀色，柔和的暖色調。": "Màu giấy be và hổ phách, tông màu ấm nhẹ nhàng.",
  "跟隨系統": "Theo dõi hệ thống",
  "系統深色時用深色夜景，淺色時用藍白清爽。": "Khi hệ thống tối, hãy sử dụng cảnh đêm tối và khi hệ thống sáng, hãy sử dụng màu xanh lam và trắng sảng khoái.",
  "標準": "Tiêu chuẩn",
  "較大": "lớn hơn",
  "大": "lớn",
  "顯示全部說明與提示。": "Hiển thị tất cả các hướng dẫn và lời khuyên.",
  "精簡": "Hợp lý hóa",
  "隱藏操作提示與次要說明，數值與按鈕不變。": "Các mẹo thao tác và hướng dẫn phụ bị ẩn, đồng thời các giá trị và nút vẫn không thay đổi.",
  "自動": "tự động",
  "依裝置條件選擇；持續卡頓時只會往下調一次，不會來回切換。": "Chọn theo điều kiện thiết bị; nếu tình trạng lag kéo dài thì chỉ điều chỉnh giảm xuống một lần và không được chuyển qua chuyển lại.",
  "省電": "Tiết kiệm điện",
  "降低解析度與特效，保留所有必要回饋。": "Giảm độ phân giải và các hiệu ứng đặc biệt, giữ lại tất cả các phản hồi cần thiết.",
  "平衡": "THĂNG BẰNG",
  "目前的標準畫質。": "Chất lượng hình ảnh chuẩn hiện nay.",
  "高品質": "chất lượng cao",
  "較高解析度與較多高光碎片，耗電較多。": "Độ phân giải cao hơn và nhiều đoạn nổi bật hơn sẽ tiêu thụ nhiều năng lượng hơn.",
  "依裝置的「減少動態效果」設定。": "Tùy thuộc vào cài đặt \"Giảm hiệu ứng chuyển động\" của thiết bị.",
  "減少移動、縮放與閃光，只保留短暫淡入淡出。": "Giảm chuyển động, thu phóng và nhấp nháy, chỉ để lại những khoảng mờ ngắn.",
  "播放完整動畫。": "Chơi hoạt hình đầy đủ.",
  "柔和": "Mềm mại",
  "閃光亮度降到約三分之一。": "Độ sáng của đèn flash giảm xuống còn khoảng một phần ba.",
  "完整": "hoàn thành",
  "約 3.7 秒的完整演出。": "Khoảng 3,7 giây cho hiệu suất đầy đủ.",
  "約 2.4 秒；結果與獎勵完全相同。": "Khoảng 2,4 giây; kết quả hoàn toàn giống với phần thưởng.",
  "此裝置": "thiết bị này",
  "帳號偏好": "Tùy chọn tài khoản",
  "自動（目前：{tier}）": "Tự động (hiện tại: {tier})",
  "靜音": "tắt tiếng",
  "總音量 {volume}%": "Tổng khối lượng {volume}%",
  "減少動態：{state}": "Giảm động lực: {state}",
  "存檔只在本機": "Chỉ lưu trữ trên máy này",
  "恢復本分類預設": "Khôi phục mặc định cho danh mục này",
  "已恢復「{name}」的預設值。遊戲進度不受影響。": "Giá trị mặc định của \"{name}\" đã được khôi phục. Tiến trình trò chơi không bị ảnh hưởng.",
  "主題": "chủ đề",
  "只改變介面顏色，不會改變角色與場景的原圖。": "Chỉ có màu sắc giao diện được thay đổi, hình ảnh gốc của nhân vật, cảnh vật sẽ không bị thay đổi.",
  "目前系統為{mode}，使用「{theme}」。": "Hệ thống hiện tại là {mode} và sử dụng \"{theme}\".",
  "深色": "Tối",
  "淺色": "màu sáng",
  "文字大小": "kích thước văn bản",
  "這是文字大小的預覽：生命值 128／技力 64。": "Đây là bản xem trước có kích thước văn bản: HP 128/Skill 64.",
  "資訊密度": "mật độ thông tin",
  "畫質": "Chất lượng hình ảnh",
  "畫面解析度上限": "Giới hạn trên của độ phân giải màn hình",
  "立即生效": "Có hiệu lực ngay lập tức",
  "立體場景解析度上限": "Giới hạn trên của độ phân giải cảnh lập thể",
  "下次進入該畫面時生效": "Nó sẽ có hiệu lực vào lần tiếp theo bạn vào màn hình này.",
  "抗鋸齒": "Khử răng cưa",
  "下次開啟遊戲時生效": "Nó sẽ có hiệu lực vào lần tiếp theo bạn bắt đầu trò chơi",
  "高光碎片數": "Số đoạn nổi bật",
  "下一次演出生效": "Có hiệu lực cho lần biểu diễn tiếp theo",
  "模糊與光暈": "Mờ và hào quang",
  "目前實際使用的參數（{tier}）：": "Các tham số hiện đang được sử dụng ({tier}):",
  "像素美術在任何畫質下都以最近點取樣放大，不會變糊。": "Pixel art được phóng to ở điểm gần nhất ở bất kỳ chất lượng hình ảnh nào mà không bị mờ.",
  "不提供 30／60 FPS 選項：對戰與育成時間跟著畫面更新前進，限制幀率會改變遊戲速度。": "Không có tùy chọn 30/60 FPS: tiến trình thời gian chiến đấu và sinh sản với các bản cập nhật đồ họa và việc giới hạn tốc độ khung hình sẽ thay đổi tốc độ của trò chơi.",
  "全部靜音": "tắt tiếng tất cả",
  "總音量": "tổng khối lượng",
  "遊戲音效": "Hiệu ứng âm thanh trò chơi",
  "對戰音效與高光演出音效。": "Hiệu ứng âm thanh chiến đấu và hiệu ứng âm thanh biểu diễn nổi bật.",
  "實際音量 = 總音量 × 遊戲音效（目前 {level}%）；靜音時為 0。": "Âm lượng thực tế = tổng âm lượng × hiệu ứng âm thanh trò chơi (hiện tại là {level}%); nó là 0 khi bị tắt tiếng.",
  "試聽": "buổi thử giọng",
  "正在播放試聽音效。": "Âm thanh xem trước đang phát.",
  "目前為靜音。": "Hiện đang tắt tiếng.",
  "瀏覽器尚未允許播放聲音，請再點一次。": "Trình duyệt chưa cho phát âm thanh, vui lòng click lại.",
  "本版本沒有背景音樂、介面音效與角色語音，所以不提供這些音量。": "Phiên bản này không có nhạc nền, hiệu ứng âm thanh giao diện và giọng nói nhân vật nên các tập này không được cung cấp.",
  "顯示語言": "Ngôn ngữ hiển thị",
  "切換後立即生效，不會重新開始或改變目前進度。": "Việc chuyển đổi có hiệu lực ngay lập tức và sẽ không khởi động lại hoặc thay đổi tiến trình hiện tại.",
  "英文翻譯尚未經母語編輯審校。": "Bản dịch tiếng Anh chưa được biên tập viên bản xứ xem xét.",
  "數碼獸物種名稱與初始夥伴的自動名稱在英文正式名稱核定前，沿用已核定的繁體中文名稱；你取的名字不會被翻譯。": "Tên loài đối tác và tên tự động của đối tác ban đầu sẽ sử dụng tên tiếng Trung phồn thể đã được phê duyệt trước khi tên tiếng Anh chính thức được phê duyệt; tên bạn chọn sẽ không được dịch.",
  "減少動態": "Giảm động lực",
  "目前：{state}": "Hiện tại: {state}",
  "完整動態": "Tin tức hoàn chỉnh",
  "閃光強度": "Cường độ đèn flash",
  "高光演出": "Điểm nổi bật",
  "重要勝利的演出長度。": "Hiển thị độ dài cho những chiến thắng quan trọng.",
  "鍵盤：Tab 移動、方向鍵切換選項、Esc 返回或關閉。": "Bàn phím: Tab để di chuyển, phím mũi tên để chuyển đổi tùy chọn, Esc để quay lại hoặc đóng.",
  "存檔": "Lưu trữ",
  "存檔保存在這台裝置的這個瀏覽器（本機）。重要操作後會自動保存；清除網站資料後無法取回。": "Kho lưu trữ được lưu trong trình duyệt này trên thiết bị này (máy cục bộ). Nó sẽ được lưu tự động sau các thao tác quan trọng; nó không thể được lấy lại sau khi xóa dữ liệu trang web.",
  "帳號": "Số tài khoản",
  "尚未提供帳號登入與雲端同步，這台裝置的資料不會上傳。": "Đăng nhập tài khoản và đồng bộ hóa đám mây chưa được cung cấp và dữ liệu của thiết bị này sẽ không được tải lên.",
  "標示為「帳號偏好」的設定將來可隨帳號同步；目前與「此裝置」設定一樣只保存在本機。": "Cài đặt có nhãn \"Tùy chọn tài khoản\" sẽ được đồng bộ hóa với tài khoản trong tương lai; hiện tại, giống như cài đặt \"Thiết bị này\", chúng chỉ được lưu cục bộ.",
  "偏好設定": "Tùy chọn",
  "恢復全部設定": "Khôi phục tất cả cài đặt",
  "要恢復全部設定嗎？": "Bạn có muốn khôi phục tất cả cài đặt không?",
  "主題、畫質、聲音、語言與輔助設定會回到預設值。只會重設設定，不會影響遊戲進度與存檔。": "Cài đặt chủ đề, chất lượng hình ảnh, âm thanh, ngôn ngữ và khả năng truy cập sẽ trở về giá trị mặc định. Nó sẽ chỉ đặt lại cài đặt và sẽ không ảnh hưởng đến tiến trình hoặc lưu trò chơi.",
  "恢復預設": "Khôi phục mặc định",
  "全部設定已恢復預設。遊戲進度不受影響。": "Tất cả các cài đặt đã được khôi phục về mặc định. Tiến trình trò chơi không bị ảnh hưởng.",
  "設定未能保存到本機（本次遊玩仍然有效）。": "Không thể lưu cài đặt vào máy này (vẫn hợp lệ cho trò chơi này).",
  "設定由較新的版本建立；這個版本不會覆寫它，變更只在本次遊玩有效。": "Cài đặt được tạo bởi phiên bản mới hơn; phiên bản này sẽ không ghi đè lên nó và những thay đổi sẽ chỉ có hiệu lực đối với cách chơi này.",
  "瀏覽器不允許保存網站資料，設定只在本次遊玩有效。": "Trình duyệt không cho phép lưu dữ liệu trang web và cài đặt chỉ có hiệu lực đối với trò chơi này.",
  "正在保存設定…": "Đang lưu cài đặt…",
  "設定已保存到本機（{time}）。": "Các cài đặt đã được lưu vào thiết bị này ({time}).",
  "目前使用預設設定。": "Hiện đang sử dụng cài đặt mặc định.",
  "設定已從本機讀取。": "Các cài đặt đã được đọc từ máy này.",
  "返回設定分類": "Quay lại danh mục cài đặt",
  "關閉設定": "Đóng cài đặt",
  "設定分類": "Đặt danh mục",
  "裝置開啟了省流量模式，自動使用省電。": "Máy đã bật chế độ tiết kiệm dữ liệu và tự động sử dụng để tiết kiệm điện.",
  "裝置記憶體較少，自動使用省電。": "Thiết bị có ít bộ nhớ hơn và tự động sử dụng nó để tiết kiệm điện.",
  "裝置處理器核心較少，自動使用省電。": "Thiết bị có ít lõi xử lý hơn và tự động sử dụng chúng để tiết kiệm điện năng.",
  "自動使用平衡。": "Tự động sử dụng số dư.",
  "畫面持續低於約 35 FPS，已自動改用省電（本次遊玩不會再改回）。": "Màn hình luôn ở mức dưới khoảng 35 FPS và đã được tự động chuyển sang chế độ tiết kiệm năng lượng (nó sẽ không được thay đổi trở lại đối với trò chơi này)."
});

export const UNTRANSLATED_PROPER_NOUNS_VI = Object.freeze(new Set([
  // Owner-confirmed original egg names; localized note states they retain zh-Hant.
  "星絮蛋", "焰脈蛋", "潮環蛋", "森芽蛋", "雷紋蛋", "月霧蛋", "晶棘蛋", "聖耀蛋",
  ...Object.values(SPECIES_NAMES_ZH),
  ...Object.values(STARTER_NAMES_ZH),
  "浩司", "惠子"
]));
