"""ROM numeric math tables and original ARM9 direction/vector oracle (no art)."""
import argparse, hashlib, json, random, struct
from pathlib import Path
from ndspy.rom import NintendoDSRom
from ndspy.codeCompression import decompress
from unicorn import Uc, UC_ARCH_ARM, UC_MODE_ARM, UC_HOOK_MEM_READ
from unicorn.arm_const import *


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--rom', required=True)
    p.add_argument('--out', required=True)
    p.add_argument('--tables', required=True)
    args = p.parse_args()
    raw = Path(args.rom).read_bytes()
    sha = hashlib.sha256(raw).hexdigest()
    assert sha == '8ad375ba0bd9b652a25f72dead2b47f78da401e188a8f3e1b7a6f2867ee0c5d1'
    arm = bytes(decompress(NintendoDSRom(raw).arm9))
    tables = {}
    for key, at, count, fmt in [('atanQ12', 0x9dd6c, 129, 'h'), ('atanIndex', 0x9de70, 129, 'h'),
                              ('sinCoefficients', 0x2cd4, 5, 'I'), ('cosCoefficients', 0x2da4, 4, 'I')]:
        tables[key] = list(struct.unpack_from('<' + fmt * count, arm, at))
    source = '// Numeric ARM9 math constants. Generated by trace-battle-native-math-cpu.py.\n'
    source += '// ROM SHA-256: ' + sha + '\n'
    source += 'export const BATTLE_NATIVE_MATH_TABLES = Object.freeze(' + json.dumps(tables, indent=2) + ');\n'
    Path(args.tables).write_text(source, encoding='utf-8', newline='\n')
    u = Uc(UC_ARCH_ARM, UC_MODE_ARM)
    u.mem_map(0x2000000, 0x400000)
    u.mem_map(0x4000000, 0x1000)
    u.mem_write(0x2000000, arm)
    put = lambda at, n: u.mem_write(at, struct.pack('<I', n & 0xffffffff))
    signed = lambda n: n if n < 0x80000000 else n - 0x100000000

    def divider(uc, access, address, size, value, data):
        if 0x40002a0 <= address < 0x40002b0:
            mode = int.from_bytes(u.mem_read(0x4000280, 2), 'little') & 3
            n = int.from_bytes(u.mem_read(0x4000290, 4 if mode == 0 else 8), 'little', signed=True)
            d = int.from_bytes(u.mem_read(0x4000298, 8 if mode == 2 else 4), 'little', signed=True)
            assert d != 0
            q = (abs(n) // abs(d)) * (-1 if (n < 0) != (d < 0) else 1)
            u.mem_write(0x40002a0, (q & 0xffffffffffffffff).to_bytes(8, 'little'))
            u.mem_write(0x40002a8, ((n - q * d) & 0xffffffffffffffff).to_bytes(8, 'little'))
    u.hook_add(UC_HOOK_MEM_READ, divider, begin=0x4000280, end=0x40002bf)

    def call(address, *values):
        for reg, value in zip([UC_ARM_REG_R0, UC_ARM_REG_R1, UC_ARM_REG_R2], values):
            u.reg_write(reg, value & 0xffffffff)
        u.reg_write(UC_ARM_REG_SP, 0x23e0000)
        u.reg_write(UC_ARM_REG_LR, 0x23f0000)
        u.emu_start(address, 0x23f0000, count=10000)
        assert u.reg_read(UC_ARM_REG_PC) == 0x23f0000
        return signed(u.reg_read(UC_ARM_REG_R0))

    # Exhaust every integer angle reached by atan Q12 plus the reverse offset.
    vectors = []
    for angle in range(-12868, 25737):
        call(0x2066a40, angle, 4096, 0x2300000)
        vectors.append(list(struct.unpack('<iii', u.mem_read(0x2300000, 12))))
    rng = random.Random(20260907)
    scaled = []
    for i in range(1000):
        angle = rng.randrange(-12868, 25737)
        length = rng.randrange(-1048576, 1048577)
        call(0x2066a40, angle, length, 0x2300000)
        scaled.append([angle, length, list(struct.unpack('<iii', u.mem_read(0x2300000, 12)))])
    pairs = [(y, x) for y in [-1048576, -4096, -1, 0, 1, 4096, 1048576]
             for x in [-1048576, -4096, -1, 0, 1, 4096, 1048576]]
    # Ratios immediately before/at/after every lookup transition, all quadrants.
    pairs += [(sy * (i * 32 + edge), sx * 4096) for i in range(129) for edge in [-1, 0, 1]
              for sy in [-1, 1] for sx in [-1, 1]]
    pairs += [(rng.randrange(-1048576, 1048577), rng.randrange(-1048576, 1048577)) for _ in range(1000)]
    angles = [[y, x, call(0x2002ee0, y, x), call(0x2003098, y, x)] for y, x in pairs]
    report = {'romSha256': sha, 'arm9Sha256': hashlib.sha256(arm).hexdigest(),
              'boundary': 'Original ARM9 helper bodies; only NDS integer divider hardware is emulated.',
              'firstAngle': -12868, 'unitVectors': vectors, 'scaledVectors': scaled, 'angles': angles}
    Path(args.out).write_text(json.dumps(report, separators=(',', ':')) + '\n', encoding='utf-8', newline='\n')
    print(f'{len(vectors)} unit vectors, {len(scaled)} scaled vectors, {len(angles)} angle pairs')


if __name__ == '__main__':
    main()
